### ISSUE TITLE
add middleware to actions

### ISSUE THREAD

**Issue by disintegrator** [senecajs/seneca#104]
I'm finding I need some common prerequisite code to run before executing actions. For example, verifying a JWT signature (authorization). I could not find any documentation explaining how to achieve this and a cursory look through the code does not seem to indicate it is possible.

I propose copying the way middleware is applied in express.js. e.g.
```
var jwt = require('jsonwebtoken');
var seneca = require('seneca');

var verifyJWT = function(args, next) {
    jwt.verify(args.bearer, 'some-secret', {}, function(err, payload) {
        if (err) { return next(err); }
        this.bearer = payload;  // assuming we can attach extra context for actions here
        next();
    }.bind(this));
};

var fetchIdentity = function(args, next) {
    var client = seneca()
        .client()
        .act({role: 'identity', cmd: 'fetch', uid: this.bearer.uid}, function(err, identity) {
            if (err) { return next(err); }
            this.user = identity;
        }.bind(this));
};

var seneca = require('seneca')()
    .add({role: 'orders', cmd: 'retrieve' },
        verifyJWT,
        fetchIdentity,
        function(args, done) {
                Orders.find({user: this.user.id}, done);
        })
    .listen();
```

**Comment by rjrodger** [comment]
yes, the docs for this need to be written

it is in fact possible - you can call .add with the same pattern as many times as you like - the implementation functions stack up in "middleware" layers, and you can can call the previous layer with:

`this.prior`

for example:

```js
seneca.add("foo:1",function(args,done){ done({a:1,b:args.b}) })
seneca.add("foo:1",function(args,done){
  args.b=2
  this.prior(args,function(err,out){
    if(err) return done(err);
    out.c = 3
    done(null,out)
  })
})

seneca.act("foo:1") // output: a:1,b:2,c:3
```

**Comment by mcdonnelldean** [comment]
We know have some docs on this yay! http://senecajs.org/tutorials/understanding-prior-actions.html
