### ISSUE TITLE
Seneca 0.6.1 still have problems with curl

### ISSUE THREAD

**Issue by cleuton** [senecajs/seneca#107]
require('seneca')()                       
  .add( 
        { generate:'id'},                 
        function( message, done ) {
          done( null, 
                {id:''+Math.random()} )
        })
  .listen()

curl -d '{"generate":"id"}' http://localhost:10101/act

ERROR: 

2015-03-09T18:20:16.178Z        hzaafl7rjkkt/1425924904610/5604/-       WARN
plugin  transport               ACT     eplzlpl5bye7/xq2g06yizxt4       role:tra
nsport,hook:listen,type:web     json-parse      req-body        '{generate:id}'
SyntaxError: Unexpected token '
    at Object.parse (native)

[Trello Card](https://trello.com/c/GGUhnqJo/88-seneca-seneca-0-6-1-still-have-problems-with-curl)

**Comment by boxxxie** [comment]
i have not had any issues with curl and seneca
here is some sample code
```
curl -d '{"cmd":"dump-assets","role":"AS"}' http://localhost:4444/act
```

```
var eventMatcher = {
        role : "AS",
        cmd: "dump-assets"
      };

      var handler = Meteor.bindEnvironment(function handler(args, cb){
        cb(null, Assets.find({}).fetch());
      });

      seneca.add(eventMatcher, handler);
```

**Comment by rjrodger** [comment]
for some reason the input characters are: '{generate:id}' - which is not valid JSON
having difficulty reproducing, could you describe your test case in more detail, thanks

**Comment by geek** [comment]
Closing for now, please add more test details and reopen if its still an issue @cleuton
