### ISSUE TITLE
Documentation issue: "client()" does not work without a "host" property

### ISSUE THREAD

**Issue by cleuton** [senecajs/seneca#108]
This sample does not work: 

require('seneca')()
  .client()
  .act( { generate:'id' },
        function( err, result ) {
          console.log(JSON.stringify(result))
        })

You have to pass at least the "host" property: 

require('seneca')()
  .client({host: "localhost"})
  .act( { generate:'id' },
        function( err, result ) {
          console.log(JSON.stringify(result))
        })

Is it the expected way? 

[Trello Card](https://trello.com/c/bAJJ1XqB/89-seneca-documentation-issue-client-does-not-work-without-a-host-property)

**Comment by rjrodger** [comment]
host should not be required... what was the error message?

**Comment by tigerswithguitars** [comment]
I had the same issue while going through the examples. The binding was to 0.0.0.0 by default and without specifying localhost I was getting action timeouts from the client. Thought it might be a firewall or something, but wasn't.

**Comment by albertosantini** [comment]
This is the error `errno=EADDRNOTAVAIL`:


2015-05-13T08:36:25.916Z        v53soakned3j/1431506185698/6244/-       ERROR   plugin  transport       ACT     y0li8z5klkep/9pc48i08iy98       role:transport,hook:client,type:web client  no-message-id   {type=web,port=10101,host=0.0.0.0,path=/act,protocol=http,timeout=32778,msgprefix=seneca_,callmax=111111,msgidlen=12,role=transport,hook=client}        {kind=res,res=,error={code=EADDRNOTAVAIL,errno=EADDRNOTAVAIL,syscall=connect,address=0.0.0.0,port=10101},time={client_recv=1431506185916}}

As suggested, `.client({host: "localhost"})` is the workaround (on Windows).

**Comment by mcdonnelldean** [comment]
I checked this last night and it does work on OSX as expected.

@cleuton @tigerswithguitars @albertosantini Are ye using Windows? I'd like to see if we can target what went wrong.

0.0.0.0 and localhost are slightly different. 0.0.0.0 tells the service to listen on all network interfaces.

**Comment by albertosantini** [comment]
@mcdonnelldean Here Windows 7 (64 bit).

**Comment by robert52** [comment]
- When a service is listening on 0.0.0.0 this that is listening on all the configured network interfaces.
- When a service is listening on 127.0.0.1, it is only bound to the loopback interface, it's only available on the local machine.

For Windows platforms I suggest "localhost" or 127.0.0.1

**Comment by mcdonnelldean** [comment]
This has now landed I believe.
