### ISSUE TITLE
seneca.delegate({perm$: ..., user$: ....}) are lost in transition

### ISSUE THREAD

**Issue by nherment** [senecajs/seneca#111]
I'm not sure if this is a documentation gap, a deprecated API or a regression/bug.

We've been following the pattern `variableName$` for the fixed arguments used in delegate (as used in the permissions through perm$) to pass context information to all microservices.

This context information includes the current user, access controls (perm$), options passed to some microservices (join$, bypassValidation$) etc.

seneca-transport does a seneca.util.clean() before sending the args which removes any field with the `$` suffix. Also, the server side does not resume the context (fixed args) through `.delegate()`.

A suggestion is that we define a convention for the fixed args so that they can get resumed through transports.

[Trello Card](https://trello.com/c/MOSj3UCh/90-seneca-seneca-delegate-perm-user-are-lost-in-transition)

**Comment by rjrodger** [comment]
needs some for a whitelisting i think

**Comment by mcdonnelldean** [comment]
I'll see can I get this in for v3. I don't think it's a big change.
