### ISSUE TITLE
To ensure the ability to work accross transports, prevent non serializable args

### ISSUE THREAD

**Issue by nherment** [senecajs/seneca#113]
it'd be great to have a safety check that developers can't pass non serializable args unless they enable a specific flag.

We built the application without that and now moving towards a better microservices architecture can be painful.

[Trello Card](https://trello.com/c/x4MJ1cf8/91-seneca-to-ensure-the-ability-to-work-accross-transports-prevent-non-serializable-args)

**Comment by rjrodger** [comment]
good idea - how would such a check work?

**Comment by nherment** [comment]
huh, good point :/ wrote this without thinking much about the actual fix.

I don't think it smart to try and serialize every args... Goodbye performance. At best, this could be enabled with a debug flag of some sort to check the sanity of the system in continuous testing cycles.

The alternative is to allow circular references to be passed through transports by using a different format than JSON.

Now that I think about it, we're also likely going to have problems with Dates as I don't think the server side transports unserialize these properly. A decent serializer seem to be the cheapest and most elegant way of fixing this.

**Comment by rjrodger** [comment]
ok, so we need to allow for custom serialization, that should provide enough flexibility

**Comment by AdrianRossouw** [comment]
unless all of the callbacks are purely functional (you rely on being able to do use things like `this.ent`), you are still going to be passing things that aren't being serialized and rely on the same seneca instance being used.

So I think that there is no way to fix this while keeping compatibility with existing code.

**Comment by rjrodger** [comment]
@AdrianRossouw there's a kludge to deal with entities: https://github.com/rjrodger/seneca-transport/blob/master/lib/transport-utils.js#L446

**Comment by mcdonnelldean** [comment]
@mcollina @davidmarkclements @AdrianRossouw Important to consider in V3 roundtable. Merged with #399
