### ISSUE TITLE
Mail plugin: Node process dies on ECONNREFUSED

### ISSUE THREAD

**Issue by Arsca** [senecajs/seneca#119]
Hi,
I have an situation when I would like to gracefully handle the ECONNREFUSED, like in case when the remote smtp server is down. With the version of 0.6.1 of SENECA it is difficult as with this error the "instance.die" will be called. What would be the best way to handle this particular error condition?
 
See the following line: 1422@seneca.js
```javascript
 if( args.fatal$ ) {
           return instance.die(out.err)
          }
```

regards,

[Trello Card](https://trello.com/c/aNsgGIeQ/92-seneca-mail-plugin-node-process-dies-on-econnrefused)

**Comment by rjrodger** [comment]
How would the graceful handling work exactly? Can you give a step-by-step outline.
It may be better to use a separate microservice to achieve this - I need to understand how you'd like it to work first.

**Comment by AdrianRossouw** [comment]
we've seen this happen too. on invalid emails.

if it's using streams at all (since it's using sockets), this usually is a sign that there is a .pipe that doesn't have an error handler registered.

I think this is more of a bug for seneca-mail, or even the library it uses to talk to the server.

**Comment by AdrianRossouw** [comment]
and @Arsca, you could set up an uncaught error handler, but I recommend putting this stuff in a separate process (although that may imply some kind of queue, like maybe redis).

I've had my node apps be brought down by things like users trying to send emails generated from content pasted in from ms word. you just never know with email.

**Comment by geek** [comment]
Closing for now, @Arsca reopen if this is still an issue.
