### ISSUE TITLE
fine-grained action timeouts

### ISSUE THREAD

**Issue by rjrodger** [senecajs/seneca#121]
per act call: use timeout$ to override
per act: accept timeout$ in definition
 

[Trello Card](https://trello.com/c/kFIgpBF2/93-seneca-fine-grained-action-timeouts)

**Comment by geek** [comment]
We should also add this to the plugin `use` function, to allow for plugin initialization timeouts.

**Comment by geek** [comment]
Related: https://github.com/senecajs/gate-executor/pull/6
