### ISSUE TITLE
Easier approach for callback chains

### ISSUE THREAD

**Issue by asaf** [senecajs/seneca#129]
Hey,

Is there a well known approach you guys are using to avoid ugly callback chains (Assuming every call is seneca action invocation) ?

I guess paradigms such async waterfall / parallel but I wonder if there's anything recommended to chain actions (serial / parallel modes)

Thanks.

[Trello Card](https://trello.com/c/VgNFgONG/99-seneca-easier-approach-for-callback-chains)

**Comment by rjrodger** [comment]
yes, not documented yet, but see: 
https://github.com/rjrodger/zig
seneca API for this: https://github.com/rjrodger/seneca/blob/master/seneca.js#L2062
example: https://github.com/rjrodger/seneca/blob/master/test/seneca.test.js#L1141

Leaving issue open as reminder to document!

**Comment by mcdonnelldean** [comment]
@geek Do we need to look at this further? Because the linked code says depreciated. If it's still valid I'll move this to a documentation task on Senecajs.org

**Comment by geek** [comment]
Seems like something we shouldn't prescribe in our seneca docs.  We could link to different control flow options like fastparallel and zig, but then we will need to maintain a list.  I am closing for now.
