### ISSUE TITLE
repl also available direct from command line

### ISSUE THREAD

**Issue by rjrodger** [senecajs/seneca#140]
ie the way the node repl works, not just over network

[Trello Card](https://trello.com/c/thpJ8sHc/103-seneca-repl-also-available-direct-from-command-line)

**Comment by mcdonnelldean** [comment]
@rjrodger Quick question. Is this something that needs to be in seneca-repl or to light this up does it need to be in Seneca? If not I want to move the issue to the right repo.

**Comment by mcdonnelldean** [comment]
Moved to: https://github.com/senecajs/seneca-repl/issues/6
