### ISSUE TITLE
Cleaning up a Seneca instance

### ISSUE THREAD

**Issue by toboid** [senecajs/seneca#142]
Is there any means of cleaning up a Seneca instance without killing the entire process?

Whilst writing some tests that each create a new Seneca instance and add some test actions I receive the following warning: 
`(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.`

Which can be re-created with the following (contrived) code:

```javascript
var Seneca = require('seneca');

for(var i = 0; i < 11; ++i) {
  var seneca = new Seneca();
}
```

I can't find anything in the docs but wondered if there is a means of unbinding the handlers being set in function `action_options_get()` and any other necessary clean-up? The most likely scenario where it would be useful seems to be testing.

[Trello Card](https://trello.com/c/OrjahmZn/104-seneca-cleaning-up-a-seneca-instance)

**Comment by rjrodger** [comment]
good idea!

as an interim workaround, use `process.setMaxListeners(0)`
https://github.com/rjrodger/seneca/blob/master/test/seneca.test.js#L43

**Comment by geek** [comment]
@toboid if you call `seneca.close()` it will cleanup many of the listeners
