### ISSUE TITLE
expose plugin's init() for testing

### ISSUE THREAD

**Issue by psnider** [senecajs/seneca#154]
I've written my first seneca plugin.
Now I want to test its init().
How can I get at init() for testing it alone?

**Comment by psnider** [comment]
I'm working with seneca again, and noticed that I can't find a (seneca) way to expose internal helper functions for testing. Is there a method for accessing functions that are internal to a plugin?

For now, I'm moving to a pattern of:
- writing a module that contains my business logic (as usual)
- creating a seneca plugin that *require*s my business logic modules,  
and provides a thin wrapper around the the functions to be mapped to the seneca message dispatch system

**Comment by mcdonnelldean** [comment]
This is not a bug. @psnider your way of doing it is the soundest way. I've come to the opinion that testing the logic in plugins using a full seneca instance is not a good way to go; it breaks the system under test ideal. Your way is the best way to remove external influences from your test.

I'm going to go ahead and close, please reopen if you have any more questions. Cheers!
