### ISSUE TITLE
Create declaration files for TypeScript

### ISSUE THREAD

**Issue by psnider** [senecajs/seneca#159]
I use TypeScript, and seneca has a fairly complex interface,
so I want TypeScript declaration files following best practices.

I will start on these, and add to them as I learn the details of the interface,
and while the API docs are being updated, see https://github.com/rjrodger/seneca/issues/155

**Comment by psnider** [comment]
Here's a lame first pass at a declarations file. 
It needs more work!
This is just to give an idea, and this is not correct yet...
... and it will be much larger!

declare module "seneca" {

    interface Options {
        log?: any;
    }

    function s(options: Options): s.Seneca;


    // what does seneca do about logging?
    function log(): void;


    module s {

         interface PluginOptions {
         }

         interface ClientOptions {
         }

         interface ListenOptions {
         }

        type Pattern = string | any;
        type AddCallback = (error: Error, what: any) => void;
        type ActCallback = (error: Error, result: any) => void;
        type CloseCallback = (optional: any, done: (error: Error) => void) => void;

        interface Seneca {

            version: string;

            (options: Options): s.Seneca;
            error(done: () => void): void;
            on(eventName: string, callback: (error: Error) => void);
            close()
            use(pluginName: string): void;
            use(quickplugin: (opts) => void): void;
            client(options: ClientOptions): void;
            listen(options: ListenOptions): void;

            ready(callback: (error: Error) => void);

            add(pattern: Pattern, action: AddCallback): void;
            add(pattern: Pattern, paramspec: any, action: AddCallback): void;

            act(pattern: Pattern, respond: ActCallback);

            make(entityType: string, entity: any): void;

            // @param name reference to plugin
            export(name: string): void;

            pin(pattern: Pattern): void;
        }
    }

    export = s;

}

**Comment by psnider** [comment]
I'm trying to sort out with the TypeScript team how this declaration file should best be packaged with seneca.

Normally, I add it to the **typings** directory, ./typings/seneca/seneca.d.ts
along with a test suitable for the [DefinitielyTyped](https://github.com/borisyankov/DefinitelyTyped) declarations repository.

**Comment by mcdonnelldean** [comment]
@psnider Looks awesome!

I don't know too much TS but I'll see can others jump in with you and help.

**Comment by psnider** [comment]
My plan is to convert my private copy of seneca to TypeScript so that I know the declarations file matches the code. This is fairly easy, as javascript is already valid TypeScript.

This will also help learn the details of the interfaces.

**Comment by psnider** [comment]
I created a Gist with the declaration file [seneca.d.ts](https://gist.github.com/psnider/0afa89e1bd2992756e55)

I would appreciate help with the items typed as **UnknownType**.

**Comment by psnider** [comment]
I just updated the above Gist, and the declarations file seems quite usable.
It's also now the first place I go for API documentation, followed by the on-line docs http://senecajs.org/api.html

I'm sure there are mistakes in the declarations file.
Please let me know if you find any!

**Comment by psnider** [comment]
I've been away from seneca for a little while,
and am now trying to prepare the this TypeScript declaration file for publishing.

I have the declaration file working with a test file containing the code examples from http://senecajs.org/get-started/

I could use some help to correct some details in [seneca.d.ts](https://gist.github.com/psnider/0afa89e1bd2992756e55).
In particular, I want to make sure:
- Type naming agrees with authors' intentions.  
- Function signatures and return types are correct.
- All important public elements have been typed.
- That private elements aren't declared.

If you prefer, you can email me at snider.peter at gmail.com

**Comment by mcdonnelldean** [comment]
@psnider I'm going to close this. I think it's really good but I don't think we can officially support it (person power). I'd say your next best step is to create a repo, ping us on Gitter of course if you get it started, best of luck!

**Comment by psnider** [comment]
No problem. 
I'll just submit it to the DefinitelyTyped repository.
Other seneca users can then help with any necessary corrections.

**Comment by keerthivasan-r** [comment]
@psnider I would like to make use of it. Can you help me out?

**Comment by psnider** [comment]
I'll try to push this to DefinitelyTyped today.
See my example project for how to use this declaration file: https://github.com/psnider/people-service/blob/master/src/server/ts/people-plugin.ts

**Comment by keerthivasan-r** [comment]
Thanks man, I did try the way you have done. i am able to build it successfully. but, it throws error during runtime.

```
TypeError: seneca.add is not a function
    at Object.<anonymous> (e:\Karmasoc\karmasoc-user\build\server.js:5:8)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

What might be the problem? I'm a newbie. Could you help?

**Comment by psnider** [comment]
You didn't initialize seneca.
Take a look at: https://github.com/psnider/people-service/blob/master/src/server/js/people-app.js#L5-8

**Comment by keerthivasan-r** [comment]
Thank you! I did it this way now! It works. Does that a correct way of doing?

```
var seneca : SENECA.Seneca = require('seneca')()
@
seneca.add({ role: 'user', cmd: 'signin' }, function (args, callback) {
    let userService = new UserService();
    let user = { email: args.email, pwd: args.pwd }
   userService.findUserByEmail(user.email).then(user => callback(null,user))
})
```

**Comment by psnider** [comment]
I pushed this to the TypeScript community repository for declaration files:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/seneca/seneca.d.ts

Please let me know if you find anything you want me to change.

**Comment by CelsoSantos** [comment]
I'm sorry to re-open this, but it's also important to have .d.ts files for all accompaning seneca-plugins, otherwise, typescript will always throw an error, which causes Docker builds to fails, for instance, with error TS2307

**Comment by mcdonnelldean** [comment]
@CelsoSantos this is why we didn't accept this one. In a plugin environment it's too much to support for us right now.
