### ISSUE TITLE
Validation using parambulator

### ISSUE THREAD

**Issue by baldmountain** [senecajs/seneca#164]
I ran into an issue using the built in parambulator validation. I have an api like:

```javascript 
seneca.add('"uid":hash' function(msg, done) {
  // do stuff
});
```

I added some validation like:

```javascript 
seneca.add('"uid":hash', {
  text: {type$: 'string'},
  type: {type$: 'string'}
  required$: 'test',
  notempty$: 'test'
}, function(msg, done) {
  // do stuff
});
```

The required$ and notempty$ validation didn't work. I traced through the code and there is a call to util.clean that removes variables that end with $. The required$ and nonempty$ rules are gone. So I changed the validation to:

```javascript 
seneca.add('"uid":hash', {
  text: {type$: 'string', required$: true, notempty$: true},
  type: {type$: 'string'}
}, function(msg, done) {
  // do stuff
});
```

The required$ validation works, but the notempty$ validation doesn't.  Finally I gave up and changed it to: 

```javascript 
seneca.add('"uid":hash', {
  text: {type$: 'string', required$: true},
  type: {type$: 'string'}
}, function(msg, done) {
  // do stuff
});
```

And check text to make sure it isn't an empty strings in the callback.

Am I misunderstanding how this validation is supposed to work?

**Comment by geek** [comment]
@baldmountain that may be a bug in parambulator.

Alternatively you can use Joi.

```js
var Joi = require('joi');

var schema = Joi.object().keys({
  uid: Joi.string(),
  text: Joi.string(),
  type: Joi.string(),
  test: Joi.string().required()
});
seneca.add({uid:'hash'}, function(msg, done) {
  // do stuff
}, { parambulator: schema );
```

**Comment by baldmountain** [comment]
I think perambulator is OK. Internally seneca is building a kind of reduced parameter validation using perambulator. What I was trying to do just isn't possible using the built in validation mechanism.

In any case, I converted everything to joi.

**Comment by StarpTech** [comment]
Hi @geek what is the status?  Can I safely built my service with perambulator?

**Comment by geek** [comment]
@StarpTech You are safe to use either parambulator or joi.  If you find a bug in either, please log with the respective project.

**Comment by StarpTech** [comment]
@geek thanks
