### ISSUE TITLE
"pluggable" validator

### ISSUE THREAD

**Issue by j** [senecajs/seneca#174]
Hapi caused me to look at seneca and I like what I see so far.  One of the pain points so far is that I have to learn all kinds of new stuff that isn't documented.  I've forced myself to not use validation and do it inside of my actions using Joi [https://github.com/hapijs/joi].  Which is extremely documented and tested and also does transformations, defaults, etc.

How difficult would it be to be able to use 3rd party validators when creating action patterns?

**Comment by geek** [comment]
@j powerful idea.  After an action is matched it then validates the object coming in against a joi schema?

**Comment by bjonica** [comment]
@geek That's how I'm using seneca. I could *almost* use parambulator, which is the built-in validator that runs during action matching, but it didn't work for me because I needed custom rules and seneca doesn't expose that feature of parambulator.

I think it's a good idea. It feels a bit dirty to have two different validators (built-in and joi) running against the same action.

**Comment by j** [comment]
@geek yeah, exactly.  Basically exactly how Hapi matches routes and does validation before hitting business logic.  Joi is so battle tested and super extremely simple.  IMO it's the best validator out there and so easy to use and learn with so little "magic".  It'll only get better when they figure out the correct way to allow more custom validations (i.e. param userId needs to be a valid MongoID string, then convert it to a MongoID object and pass it to the action method).

@bjonica Yeah, I removed parambulator after using it for a few minutes (that's how quick I ran into an issue).  Now I just set up actions (using objects instead of jsonic strings) and in my action, I prevalidate them.

**Comment by rjrodger** [comment]
So, in general, strict schemas are not considered advisable for microservice messages (at least, that's my opinion! ;) )

But of course each to their own, so a pluggable validation is perfectly OK - and in fact it should be joi based, as parambulator needs to be deprecated... however I believe the underlying block here is that joi does not work in the browser, and does not have a declarative (ie pure JSON) definition

/cc @geek

**Comment by geek** [comment]
@j I need to document it, but if you look at #238 you can see an example of using Joi instead of parambulator for validating action parameters

**Comment by AdrieanKhisbe** [comment]
> $ touch this

@geek: shall we move this to senecajs.org? (or create an attached issue for the documentation part?)

**Comment by geek** [comment]
Moved to https://github.com/senecajs/senecajs.org/issues/135
