### ISSUE TITLE
review full feature set and determine features to deprecate

### ISSUE THREAD

**Issue by rjrodger** [senecajs/seneca#180]
seneca.pin obviously!
but are there any more...

NOT for consideration: entities!

**Comment by AdrianRossouw** [comment]
I don't want them to be deprecated, but I do think they should live in a separate seneca-entity project.

I mean, we even have a separate repo just for their tests now:
 https://github.com/rjrodger/seneca-store-test

**Comment by AdrieanKhisbe** [comment]
@rjrodger, what is the motivation of `pin` deprecation?

It's a very useful feature to be able to bookmark some action patterns.
(for transversal features like auth, perms, *or* for dryness reasons)

**Comment by mcdonnelldean** [comment]
@AdrieanKhisbe It's works only some of the time, all of the time.

The problem is once you introduce transports it all goes a bit icky. There are other issues too.

Having said that, one item on my list is to create a decorator that does something similar.

**Comment by AdrieanKhisbe** [comment]
> Having said that, one item on my list is to create a decorator that does something similar.

Seems like it's the way to go :)

**Comment by AdrieanKhisbe** [comment]
```js
var pluginPin = seneca.pin({role: 'myPlugin', someVar:'someVal'});
var pluginPin2 = seneca.pin({role: 'myPlugin', someVar:'otherVal'});

pluginPin.act({ what: 'what' })
pluginPin2.act({ what: 'why' })

pluginPin.seneca // refer to the seneca instace
// should determine what fonction are accessible from the pin
```

**Comment by mcdonnelldean** [comment]
Closing this out in favour of a new issue in V.next. Once we have errors and logging in place we will be in a much better position vis a vis deprecating features.
