### ISSUE TITLE
"Annotated Source Code" link in readme.md is 404

### ISSUE THREAD

**Issue by SteveALee** [senecajs/seneca#184]
The subject says it all :)

**Comment by mcdonnelldean** [comment]
@SteveALee Thanks for reporting.

Yup we noticed this on the site move. We are currently working to fix this and also make it easier to work with.

I'm hoping we can end up with the annotations on the site and also locally via `npm run annotate` :D

**Comment by SteveALee** [comment]
Sounds interesting.

PS why this repo not in sencajs? Took me a little while to find. I know, should raise another issue but lazy.

**Comment by mcdonnelldean** [comment]
@SteveALee The org is only new :D

We are moving towards getting everything in. I think Seneca proper is moving in a week or so. Lots to do :D

**Comment by SteveALee** [comment]
@mcdonnelldean I should have checked the dates. So you are getting ready for the big time!? :)

I'm certainly very interested. Thanks

**Comment by mcdonnelldean** [comment]
@SteveALee Are we ok to close this?

We now have: http://senecajs.org/annotations/seneca.html and local annotations are easy to run too :D

**Comment by SteveALee** [comment]
Of course, it's great resource, especially as such a big single file. I wasn't able to discover it on the website but followed the broken link reported here.

**Comment by mcdonnelldean** [comment]
@SteveALee Noted! I have a task to complete that will see the link added to the website.
