### ISSUE TITLE
Arrays are  not allowed as default answer

### ISSUE THREAD

**Issue by maxired** [senecajs/seneca#185]
Hi,

We cannot currently provide an array as defaults answer of act if no matching pattern is found.
This lead to issue with `seneca-jsonrest-api`, when we use the `list` method with `aspect:true` but no `after` aspect is launch.

Here is the link matching object only : https://github.com/rjrodger/seneca/blob/44d9aec1e05a2642dfcc42e36f59dbf37e87e0b3/seneca.js#L1139

Should we also accept arrays as default answer ? I thinks so because looks like arrays are valid answers usually : https://github.com/rjrodger/seneca/blob/44d9aec1e05a2642dfcc42e36f59dbf37e87e0b3/seneca.js#L1483L1484

**Comment by mcdonnelldean** [comment]
@geek @rjrodger thoughts on this one?

**Comment by geek** [comment]
Makes sense to me to allow an array

**Comment by mcdonnelldean** [comment]
@maxired Do you want to do a PR so we can have a look?

**Comment by maxired** [comment]
@mcdonnelldean , yes I will, but not today ;)

**Comment by mcdonnelldean** [comment]
@maxired Awesome! Thanks :dancer:

**Comment by geek** [comment]
Fixed by https://github.com/senecajs/seneca/pull/210
