### ISSUE TITLE
What versions of node to support?

### ISSUE THREAD

**Issue by thekemkid** [senecajs/seneca#191]
As per the discussion over here: https://github.com/senecajs/contrib/issues/36

We need to decide and clarify a support system for node versions.

From the discussion I referenced, it seems that we want an LTS version which keeps support and compatibility with all ​_current_​ node LTS versions (which includes those in maintenance, currently `0.10`, `0.12` and `4.x`), and when those versions are deprecated we can drop our LTS's version support for them.

and then it seems we should keep a "latest" version, which supports and optimizes for the latest LTS version of node. (currently `4.x`).

If we started work on the latest version, with optimizations for es6 features now, we would probably shift the current `4.x` latest version to the LTS version in December 2016, as that is when 0.12 drops off its LTS.

How does this sound?

[Refer to here to see the LTS timeline.](https://github.com/nodejs/LTS/blob/master/README.md)

**Comment by rjrodger** [comment]
1.0 will support 0.10+ forever :)
2.0 will be the move to es6 - looking at q2 2016 for this
