### ISSUE TITLE
Latest release 'no matching action pattern found'

### ISSUE THREAD

**Issue by edimoldovan** [senecajs/seneca#199]
Hi,

I updated seneca to the latest and I am getting this error. Has anything changed in the api with the latest release, or possibly the previous one?

`seneca: No matching action pattern found for { data: null, role: 'products', cmd: 'list' }, and no default result provided (using a default$ property).	act_not_found	{args:{ data: null, role: 'products', cmd: 'list' },plugin:{}}	Error: seneca: No matching action pattern found for { data: null, role: 'products', cmd: 'list' }, and no default result provided (using a default$ property).`

**Comment by mcdonnelldean** [comment]
Hey @edimuldovan.

Nothing functionality wise has changed that I am aware of. Could you pop up some code?

In the meantime I'll have a chat with @geek later on and we will take a look. Thanks for reporting.

**Comment by edimoldovan** [comment]
Hi @mcdonnelldean 

Sure, I will try to reproduce that in a separate codebase today.

**Comment by mcdonnelldean** [comment]
Awesome!

Thanks a mil!

**Comment by edimoldovan** [comment]
I created a repo with an example https://github.com/edimoldovan/seneca-debug . You should be able to reproduce it like this:
- npm install
- node server.js
- node client.js
Last one should say something very similar to the above.

**Comment by mcdonnelldean** [comment]
Awesome, traveling right now so I will check this out later on this evening. Again thanks for the additional info :D

**Comment by mcdonnelldean** [comment]
@edimoldovan just a heads up. I'll be sorting this out today. I'll ping you when there is an update for you to do 😊

**Comment by mcdonnelldean** [comment]
@edimoldovan So we are just running through now. For now, if you use pin. So in your client change the .client line, like so:

```
seneca.client({port: 10005, pin: {role: 'products'}})
 ```

It should work without this though but right now this will get you out of a hole if you need it.

**Comment by edimoldovan** [comment]
Will try it soon and give feedback. Thanks!

**Comment by mcollina** [comment]
This is fixed on 0.7.2.

**Comment by mcdonnelldean** [comment]
@edimoldovan We checked it with your sample so this should be good for you now :D Thanks a mil for reporting :+1:

**Comment by edimoldovan** [comment]
Thanks everyone, will check it out this evening and give feedback.

--
ed
himself@eduardmoldovan.com
@edimoldovan

**Comment by edimoldovan** [comment]
The reported error is gone in 0.7.2. Thanks a lot!
