### ISSUE TITLE
api_use() should throw on failure

### ISSUE THREAD

**Issue by boneskull** [senecajs/seneca#202]
I cannot assert my plugin has loaded via a test.

In `seneca.js`, we have the `api_use()` function.  In this function is the following:

```js
    try {
      plugindesc = private$.use( arg0, arg1, arg2 )
    }
    catch(e) {
      self.die( error(e,'plugin_'+e.code) );
      return self;
    }
```

Because `self.die()` eventually causes a `process.exit()` *and never throws*, this test is a false positive:

```js
it('should load my plugin', function() {
  expect(function() {
    require('seneca')().use('/wrong/path/to/my/plugin');
  }).not.to.throw();
});
```

**Comment by rjrodger** [comment]
plugin errors may be asynchronous, so may never be thrown in any case

to keep the seneca instance alive, try:

`
seneca({debug:{undead:true}})
  .error( ... your error handler, called for all errors, including plugin fails ... )
`

but but but ... do you really want a process with a failed plugin to keep running? better to die and restart

**Comment by yuanotes** [comment]
I have a related issue. 

When a duplicated key is inserted to mysql, seneca DIE for that. 

But I want to catch it and response to client that the request is bad instead of kill the server.

**Comment by geek** [comment]
@yuanotes what plugins are you using?  You will want to make sure you are handling any `'error'` events from seneca and the mysql driver you are using.  Also, when calling an action in seneca you can set `fatal$: false` in the options.

**Comment by boneskull** [comment]
@rjrodger sorry, just seeing this now.

> but but but ... do you really want a process with a failed plugin to keep running? better to die and restart

well, yeah, but if I'm writing a *test*, how am I to assert my plugin doesn't cause an exception?

**Comment by boneskull** [comment]
regardless, I don't understand why `process.exit()` must be called--can seneca just `throw new Error()` instead?

**Comment by geek** [comment]
@boneskull you can call your plugin independently of seneca and assert that there aren't any throws.

Another option is to handle `seneca.on('error'` and throw when that event is executed when you think its a programmer error that should throw.

**Comment by boneskull** [comment]
> @boneskull you can call your plugin independently of seneca and assert that there aren't any throws.

Sure, but the point of this is integration testing.  The original issue was "I cannot assert my plugin has loaded via a test".

> Another option is to handle seneca.on('error' and throw when that event is executed when you think its a programmer error that should throw.

This isn't an option, because my test would run indefinitely if it *didn't* fail and I was waiting for seneca to emit `error`.

Respectfully, my question hasn't been addressed.  Why must `process.exit()` be called, and why can't seneca `throw new Error()` instead?  If I can assert a bit of code (such as `use()`) does not throw an error, then I can assert my plugin works in context.
