### ISSUE TITLE
Seneca in cluster mode

### ISSUE THREAD

**Issue by edimoldovan** [senecajs/seneca#209]
If I try to run seneca with `pm2 start` and set max instances, I get an error saying `EADDRINUSE 127.0.0.1:10001`
I might not be doing things properly here, but `pm2` has proven to be a nice tool so far, how should I use it with `seneca`?

**Comment by rjrodger** [comment]
Hi Eduárd - could you post the code you are using to run the service?

In general, a better approach to scaling is to use containers, rather than clustering.

**Comment by edimoldovan** [comment]
@rjrodger I would appreciate a scaling example using containers, a simple post would suffice if you have anything at hand.
For the pm2 example, I’ll try putting together an example tonight and sharing the link here (will be a github repo).

**Comment by mcdonnelldean** [comment]
@edimoldovan It's not exactly what you want but this shows how to dockerize some Seneca services: https://github.com/nearform/developing-microservices.

Generally a thing I have been playing with is to have multiple containers with the same service running. Messages are then sent / picked to FIFO queues (take your pick of queue) This was I get a sort of round robin. If you show your example we may be able to sort it but I would second what Richard said, adding multiple versions on containers tends to be a better way to do it, it gives you a lot more options too in terms of tearing up and down services based on load.

**Comment by edimoldovan** [comment]
Will have a look at the example, thanks.

For pm2, I need to look into it a bit more because it looks like it works if I do it like this `pm2 start app.js-i 0` but if I put together a `processes.json` with the app config, it gives me the error I originally reported.

**Comment by mcdonnelldean** [comment]
@edimoldovan I would say Nodezoo is the best sample we have now. https://github.com/nodezoo It shows how to build a complete seneca system.
