### ISSUE TITLE
eslint cleanup to use eslint-seneca-config

### ISSUE THREAD

**Issue by rjrodger** [senecajs/seneca#211]
.eslintrc contains rules that should really be in seneca config

**Comment by ckiss** [comment]
I've started working on this

**Comment by geek** [comment]
@ckiss please take a look at the 0.8 branch.  I have most of it done, but the tests still need to be corrected.

**Comment by ckiss** [comment]
@geek cool. I haven't seen that. I was checking master. Should I do a PR with this against branch 0.7 too since this issue is labeled 0.7, or change the label to 0.8?

**Comment by geek** [comment]
@ckiss at this point please PR against 0.8.  We are going to try and switch to a master branch style following this idea: https://github.com/senecajs/discuss/issues/2

**Comment by ckiss** [comment]
@geek it seems that all the tests are corrected so I don't have to do a PR at this moment.
