### ISSUE TITLE
How do you call an act without act_not_found being fatal?

### ISSUE THREAD

**Issue by thekemkid** [senecajs/seneca#219]
I tried calling an act today. act_not_found: seneca must die now.

I tried calling that same act with the fatal$: true in it.  act_not_found: seneca must die now.

Can we create another method for simple emit-and-forget behaviour expected of microservices? Maybe I'm just emitting something I want to use later in my life.

I would suggest a `seneca.emit(input[, callback])` where an act_not_found is never fatal, and the callback is always optional.

**Comment by bjonica** [comment]
One thing you can do is pass 
```js
{ debug: { undead: true } } // ...not for production
```
in your options. Unfortunately this treats all fatal errors as non-fatal. Understandably, not a permanent solution.

**Comment by geek** [comment]
Thoughts on adding a `publish` method

**Comment by jacktuck** [comment]
I ended up doing the following:

`
seneca.use(function () {
    this.fixedargs['fatal$'] = false
    this.act('service:notifications', {
        type: `achievement`
    })
})
`

**Comment by jacktuck** [comment]
Any thoughts on the above?

**Comment by mcdonnelldean** [comment]
@jacktuck Added in 1.1.0 https://github.com/senecajs/seneca/issues/334

**Comment by jacktuck** [comment]
@mcdonnelldean Nice! Thank you.

**Comment by geek** [comment]
Added by #333

**Comment by jacktuck** [comment]
How about timeouts are they still considered fatal errors (using the rabbitmq transport)? I don't think they should be!

**Comment by geek** [comment]
@jacktuck you can set a `default$` value for the response and set `fatal$` to false to avoid it being fatal.  I will add a test case to seneca as well, timeouts being fatal or not are a good case to test.

**Comment by jacktuck** [comment]
@geek Great. How would that look?

I have tried (to no avail): 
```
seneca.act('service:notifications,req:apn', {
    default$: {
        fatal$: false
    }
}, function (err, result) {
    debug('Notifications err:: ', err)
    debug('Notifications result:: ', result)
})
```

**Comment by geek** [comment]
@jacktuck try the following:

```js
seneca.act('service:notifications,req:apn', {
    default$: {},
    fatal$: false
}, function (err, result) {
    debug('Notifications err:: ', err)
    debug('Notifications result:: ', result)
})
```

**Comment by jacktuck** [comment]
@geek 

```
Seneca Fatal Error
==================

Message: seneca: Action req:*,service:notifications failed: [TIMEOUT:qsr0nhnkv4xj/jvub644qw20j:11111<1455873780661-1455873769550:undefined].

Code: act_execute

Details: { id: 'qsr0nhnkv4xj/jvub644qw20j',
  gate: false,
  ungate: true,
  desc: undefined,
  cb: [Function],
  fn: { [Function: transport_client] id: 'fqjmtw' },
  time: { start: 1455873769550, end: 1455873780661 },
  'orig$': { [Error: [TIMEOUT:qsr0nhnkv4xj/jvub644qw20j:11111<1455873780661-1455873769550:undefined]] timeout: true },
  'message$': '[TIMEOUT:qsr0nhnkv4xj/jvub644qw20j:11111<1455873780661-1455873769550:undefined]',
  message: '[TIMEOUT:qsr0nhnkv4xj/jvub644qw20j:11111<1455873780661-1455873769550:undefined]',
  pattern: 'req:*,service:notifications',
  instance: 'Seneca/1.2.0/yoc2qvbsg3sw/1455873768021/8739/-',
  plugin: {} }

Stack:
    at null._onTimeout (/Users/JackTuck/Repos/vlog/vlog-achievements/node_modules/seneca/node_modules/gate-executor/gate-executor.js:111:21)
    at Timer.listOnTimeout (timers.js:89:15)

Instance: Seneca/1.2.0/yoc2qvbsg3sw/1455873768021/8739/-
  ALL ERRORS FATAL: action called with argument fatal$:true (probably a plugin init error, or using a plugin seneca instance, see senecajs.org/fatal.html)
    at act_done (/Users/JackTuck/Repos/vlog/vlog-achievements/node_modules/seneca/seneca.js:1185:29)
```

**Comment by geek** [comment]
Here is a better example:

```js
Seneca({ log: 'silent' })
      .listen({ port: 10000 })
      .ready(function () {
        var client = Seneca({ timeout: 5, log: 'silent' })
        client.client({ port: 10000 })

        client.ready(function () {
          client.act({ foo: 1, fatal$: false }, function (err, result) {
            expect(err).to.exist()
            done()
          })
        })
      })
```

It will timeout and just return an error instead of exiting.

Another option is to remove the `error` handler `seneca.die` and add your own custom one.
