### ISSUE TITLE
--seneca.log readability with filters

### ISSUE THREAD

**Issue by CodeWriterWriter** [senecajs/seneca#221]
Could someone explain why for expanding or shrinking the log the notation is
--seneca.log.quiet or --seneca.log.print

but for filtering it the notation is

--seneca.log=type:  or --seneca.log=plugin:

Seems cumbersome to use dot notation for some log commands and = notation for others 
@mcdonnelldean

**Comment by geek** [comment]
Agreed... @CodeWriterWriter any preference on using `=` vs `.` only?

**Comment by CodeWriterWriter** [comment]
@geek My preference personally would be for dot notation, if only because the log is dot notation, i.e. seneca.log, not: seneca=log. But I don't think it matters too much either way so long as it's consistent throughout

**Comment by rjrodger** [comment]
Logging needs a complete overhaul.

To answer your question, the dot notations are abbreviations of full property define filters.

**Comment by mcdonnelldean** [comment]
Merged with #397
