### ISSUE TITLE
seneca.use loading behaviour varies depends on first seneca require

### ISSUE THREAD

**Issue by eoinsha** [senecajs/seneca#222]
The search order for seneca plugins is driven by the module provided to `use`. Seneca passes the current `module` instance to `makeuse` (https://github.com/senecajs/seneca/blob/master/seneca.js#L337). This is not bound to the seneca instance but to the seneca module and whatever parent module required it first. As a result, adding a `require('seneca')` from a new module can affect the plugin loading behaviour and cause load failures.

For example, an application normally performs its seneca initialisation in a module, `seneca-init.js`:
```
...
const seneca = require('seneca')(options);

seneca.use('user').use('redis-sync-transport').use('./lib/theme/theme.js')
...
```

When this module is the first to `require`, loading of plugins in relative paths works fine, as for `require`.

If you instead load this from a test module in a different folder, `./lib/theme/theme.js` will fail to resolve.

e.g. `./test/lib/themes/theme.test.js`:
```
const seneca = require('seneca') // This changes the 'module' provided for 'use' in all seneca instances
seneca.act(.....) 
....
require('../../../seneca-init.js')
....
// use seneca to test stuff
```

**Comment by bjonica** [comment]
To offer a workaround, one can also pass around the loaded module to `.use`, rather than the name of the plugin. For example:
```js
const plugin = require('./lib/plugin');
seneca
  .use(plugin, pluginOptions)
  .use(require('redis-sync-transport'), {port: 3212});
```

I prefer this method as it prevents issues in the future where the plugin maintainer may at one point change the name of the plugin.

**Comment by geek** [comment]
We should document to `require` the modules first and then pass the loaded module to `use`.  Using the name of the module is too brittle.

**Comment by eoinsha** [comment]
Sounds like the perfect outcome. There's no other way to fix it and this would make it clear as `require` behaviour is well understood.

**Comment by rjrodger** [comment]
The string abbreviation for plugins is a trade-off decision. hapi had similar issues at one point, and went with `require` only.

We have a very strong use case for microservice setup scripts to be as concise as possible, and the string abbreviation works well there, so I feel the trade-off is justified.

That said, we should definitely have a more explanatory error message when a plugin cannot be found, explaining that require is the best way to handle this issue.

Also: it's not great structure to be requireing in seneca all over the place, so not sure we should make our api more verbose just to enable sphagetti

Q: is it possible to get current module in some way - it wasn't when I last looked at this

**Comment by rjrodger** [comment]
See also: http://senecajs.org/faq.html#what-is-the-recommended-structure-for-seneca-apps-
