### ISSUE TITLE
npm package 0.7.2 is not the same as master?

### ISSUE THREAD

**Issue by technicallyjosh** [senecajs/seneca#231]
When doing an `npm install seneca` or `npm install seneca@latest` the package.json in seneca shows a dependency of seneca-transport of version 0.7.2. On the master branch here it shows 0.8.2.

Any ideas?

Mainly wondering because the install of the old seneca-transport had bugs.

**Comment by mcdonnelldean** [comment]
Our original branch model had master as a stable branch and a whole load of branches off it for v.next. After deliberation we decided to merge all branches together and follow branching and tagging best practices so all new work has been merged into master.

There is an update going out soon once we complete a bit more tidy work around releases, branches and other fun stuff. That will have the version of transport you are looking for. (0.8.x)

Releases should be move faster and smoother post v1.0 when we moved to releasing smaller stricter semver versions.

**Comment by technicallyjosh** [comment]
Good to know! Until it gets updated I have it pointed to the repo for latest. Hopefully my PR in transport will make it into the newest version as a dependency

**Comment by mcdonnelldean** [comment]
I think it should as far as I can see.

**Comment by geek** [comment]
@technicallyjosh please refer to https://github.com/senecajs/seneca/releases to find the branch for a specific version.  We are moving to the master being the latest and greatest.
