### ISSUE TITLE
Visual tree flag is not working (--seneca.print.tree)

### ISSUE THREAD

**Issue by kulakowka** [senecajs/seneca#235]
I'm trying to follow the examples in the [documentation](http://senecajs.org/get-started/#writing-microservices), but when i trying to see a visual tree of the patterns I have a problem.

I copied the contents of the files from the example:

```javascript
// index.js

require('seneca')()
  .use('math')
```

```javascript
// math.js

module.exports = function math( options ) { 

  this.add( 'role:math,cmd:sum', function sum( msg, respond ) {
    respond( null, { answer: msg.left + msg.right } )
  })

  this.add( 'role:math,cmd:product', function product( msg, respond ) {
    respond( null, { answer: msg.left * msg.right } )
  })

  this.wrap( 'role:math', function( msg, respond ) {
    msg.left  = Number(msg.left).valueOf()
    msg.right = Number(msg.right).valueOf()
    this.prior( msg, respond )
  })

}
```

Now when I run the command `node index.js --seneca.print.tree`, the console displays nothing.

```
» node index.js --seneca.print.tree
2015-11-19T15:39:46.984Z of6zm3o6z40i/1447947586965/70183/- INFO	hello	Seneca/0.7.2/of6zm3o6z40i/1447947586965/70183/-
```

Perhaps documentation is outdated?

**Comment by tfoutrein** [comment]
The bug is always present in the last version of Seneca ("seneca": "^2.0.0",) 
when I put the --seneca.print.tree flag i have no tree in the console

**Comment by umidjons** [comment]
I'm using seneca version 2.0.1 and mentioned example from documentation doesn't print any tree. Will this be fixed?
