### ISSUE TITLE
PUB/SUB

### ISSUE THREAD

**Issue by oliverzy** [senecajs/seneca#25]
How about implement something like PUB/SUB mechanism to handle use cases that the ONE event producer and N event consumers needs to be connected?

The commands in seneca seems much more like ONE to ONE request/reply pattern.

**Comment by IRT-fbachmann** [comment]
Hi, how's pub/sub done today? It's not included in seneca-transport since version 0.2.0 (April 2014) and "seneca-redis-pubsub-transport" seems not to be available on npm anymore...
