### ISSUE TITLE
Promise support for common API

### ISSUE THREAD

**Issue by oliverzy** [senecajs/seneca#26]
Hi,

When I experiments with Seneca, I found two much callback needed especially about data entity.

Promise is a very good way to improve callback hell and provide robust error handling mechanism.

What about adding promise support for seneca.act and data entity api like save$/load$ and so on?

[Trello Card](https://trello.com/c/vTgPfa46/81-seneca-promise-support-for-common-api)

**Comment by boxxxie** [comment]
does `bluebird.promisfyAll()` not work for seneca?

**Comment by sc0ttyd** [comment]
Would it be possible to add this single line to seneca.js so that https://github.com/tasinet/seneca-bluebird would work without having to modify seneca.js manually? This would allow us to use Bluebird based promises.
```
private$.exports.Entity = Entity;
```

**Comment by sc0ttyd** [comment]
Ignore my query. I've just seen the legacy callback message in my console output from seneca. :-)

**Comment by sc0ttyd** [comment]
seneca-bluebird will work by modifying 3 files.

Add the following to the end of seneca/lib/entity.js:
```
module.exports.Entity = Entity;
```
Add the following to seneca/seneca.js, in make_seneca(), before it returns:
```
private$.exports.Entity = make_entity.Entity;
```
Change seneca-bluebird/promisify.js to remove the done argument from the main exported function.

**Comment by cheshirecatalyst** [comment]
Any word on this? I'd prefer not to have to use a module that has to modify seneca to get support for bluebird, and the arcane nature of seneca has made it resist my attempts to promisify entity / save$ or anything I have attempted.

**Comment by genexp** [comment]
+1

**Comment by genexp** [comment]
This bluebird module is pretty close.  Unfortunately it requires some hacking to core modules.  Would be nice to just drag this in.

**Comment by reidrankin** [comment]
I've submitted PRs to seneca and seneca-bluebird to implement the changes @sc0ttyd identified. Hopefully we can get seneca-bluebird into a proper npm package soon. I've really taken to a promisified seneca-bluebird! My main code is all inside a generator function lifted with bluebird's Promise.coroutine, and it lets me do a one-liner like "yield seneca.readyAsync();" to wait for seneca's initialization intead of unwieldy callback nesting.

**Comment by sc0ttyd** [comment]
Thanks @reidrankin :+1:

**Comment by genexp** [comment]
Very nice!

On Monday, September 14, 2015, Scott Donnelly <notifications@github.com>
wrote:

> Thanks @reidrankin <https://github.com/reidrankin> [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rjrodger/seneca/issues/26#issuecomment-140219133>.
>


-- 

---
Brian Corrigan
Managing Partner / Principal Engineer at MadGlory
<https://www.linkedin.com/company/2657284>
Wb: http://madglory.com <http://www.madglory.com>
Tw: @madglory
Ph: 518.867.1439

**Comment by faceleg** [comment]
For what it's worth, I've been using 

```JS
seneca.actAsync = Promise.promisify(seneca.act);
```

With much success.

**Comment by genexp** [comment]
I think I saw @kixxauth or @blainsmith do something similar

**Comment by blainsmith** [comment]
Yes, what @faceleg said. Works like a charm.

**Comment by mcdonnelldean** [comment]
@faceleg @blainsmith Does this work ok? Could we get the basis of a simple guide going here to put on the site? I think this is the best way to handle this until we get to the stage where we can explore it further.

**Comment by blainsmith** [comment]
Sure. I can add a new tutorial to this page (http://senecajs.org/tutorials) "Promisified Seneca" or something along those lines. It'll be a fairly short one, but at least it will be something.

**Comment by mcdonnelldean** [comment]
@blainsmith Oh this would be awesome. If you add it here: https://github.com/senecajs/senecajs.org/tree/master/src/pages/drafts I can even get our resident write to do magic on it for you afterwards!!

**Comment by AdrianRossouw** [comment]
how do promises tie into the 'gating' stuff i have seen in the api?

**Comment by mcdonnelldean** [comment]
@AdrianRossouw good question.

**Comment by AdrianRossouw** [comment]
https://github.com/rjrodger/gate-executor

that has promises written all over it.

**Comment by mcdonnelldean** [comment]
From what I read about this will be a thing at some stage but for now at least having documents explaining how to do it is good middle ground :D

**Comment by blainsmith** [comment]
@AdrianRossouw If you promisify `seneca.act` and the gate executer times out then the promise is treated as rejected and caught. I just verified this while wiring the tutorial. I will polish this up and PR it soon.

**Comment by faceleg** [comment]
@blainsmith I love you

**Comment by blainsmith** [comment]
:boom: https://github.com/senecajs/senecajs.org/pull/87

**Comment by mcdonnelldean** [comment]
@blainsmith Your so epic :D

**Comment by nfantone** [comment]
Any updates or plans on this? I'd love to see not only this baked into the core, but a tutorial on promisifying entities methods (such as `save$`). [Some hacky attempts](https://github.com/tasinet/seneca-bluebird/blob/master/promisify.js) were made before, but it seems they have become obsolete by now.

**Comment by geek** [comment]
@nfantone I think we are definitely open to it.  It hasn't become a major priority though, as there are ways around it, as Blain wrote about in his tutorial.  But, we are definitely happy to consider a PR to add in promises.

**Comment by nfantone** [comment]
@geek The thing is, the tutorial only approaches "promisification" of `seneca.act`. What's the "way around" entities' API? I don't think there's such a straight forward way for those, is there?

**Comment by nfantone** [comment]
@geek @oliverzy Also, would you consider opening up the Trello board for the community? That way, anyone could see progress and/or vote up/down features and see what others would like to see implemented. It'd help re-organize priorities, as well.

**Comment by nfantone** [comment]
Just wanted to say, for future reference, that this:

```js
  var entity = seneca.make(base, name, payload);
  var save$ = Promise.promisify(entity.save$, { context: entity });
  return save$();
```

Works wonders. Maybe we could include a mention in the tutorial?

**Comment by geek** [comment]
@nfantone we have moved away from the trello board to plain old github issues and milestones!

Please fix the tutorial, its at https://github.com/senecajs/senecajs.org/blob/master/src/pages/tutorials/seneca-with-promises.md

**Comment by nfantone** [comment]
@geek Will do!

**Comment by japel** [comment]
@geek was just trying out the example at:
https://github.com/senecajs/senecajs.org/blob/master/src/pages/tutorials/seneca-with-promises.md#advanced-example

and got:
```javascript
2016-03-11T11:42:40.685Z b5tr3kr5vzx8/1457696560620/1544/- INFO	hello	Seneca/1.3.0/b5tr3kr5vzx8/1457696560620/1544/-	
[TypeError: Object #<Object> has no method 'idgen']
```

**Comment by geek** [comment]
@japel looks like a bug, opened an issue here: https://github.com/senecajs/seneca/issues/370

**Comment by mcdonnelldean** [comment]
Issue on bug is open, see tutorial for how to enable.
