### ISSUE TITLE
Support decoration via plugins

### ISSUE THREAD

**Issue by mcdonnelldean** [senecajs/seneca#264]
Right now, this won't work:

```js
'use strict'

var Varo = require('varo')

var defaults = {

}

module.exports = function (options) {
  var seneca = this
  var extend = seneca.util.deepextend

  options = extend(defaults, options)
  var varo = new Varo(options)

  seneca.decorate('publish', varo.emit)
  seneca.decorate('subscribe', varo.observe)

    return {
      name: 'seneca-pubsub-decorator'
    }
  }
}
```

I think the use case for pluggable decorations makes a lot of sense. This one for instance, would allow me to have pub/sub on seneca without adding additional load to the msg flow rate.

**Comment by mcdonnelldean** [comment]
@rjrodger @geek What are your thoughts on this?

**Comment by rjrodger** [comment]
yes yes yes

**Comment by mcdonnelldean** [comment]
@geek How much work do you think would be in this? I can publish the above as soon as it's ready. It will also remove a big lump of workaround crud from vidi :D

**Comment by geek** [comment]
@mcdonnelldean have you tried with seneca 0.9.0 yet?  I pulled out cluster and repl as plugins are am decorating the same way, both are working on 0.9.0.

**Comment by mcdonnelldean** [comment]
@geek I'm on 0.8, let me upgrade and see what happens.

**Comment by mcdonnelldean** [comment]
@rjrodger @geek This works on 0.9 HUZZAH!

I'll package up seneca-pupsub-decorator this evening for all to enjoy!
