### ISSUE TITLE
a seneca-core-client dist?

### ISSUE THREAD

**Issue by dynnamitt** [senecajs/seneca#265]
Would a smaller core dist be smart to offer?
Say if someone need to integrate a legacy nodejs express app and an out-of-proc seneca-service.

If so ; strip down dependencies and features to "a bare minimum client"

Or is http/request the way to attack legacy code-> seneca service?

**Comment by rjrodger** [comment]
this is the way we will go with seneca 2.0 in q1 2016
right now we want to get 1.0 out the door early jan, and lock down the 1.0 api, which is backwards compatible
most extra features (e.g repl) will be available via decorations in 2.0

**Comment by dynnamitt** [comment]
:+1: good to know
