### ISSUE TITLE
Plugin loading on ES6/ES2015 with Babel

### ISSUE THREAD

**Issue by quangv** [senecajs/seneca#267]
```
 this.use( 'math' ) // finds ./math.js in local folder
```

This signature doesn't work when transpiling with Babel.

You can load plugins normally:

```
import math from './math'
... this.use(math)
```

However things get hairy when you use something like `seneca-mongo-store`

```
import mongoStore from 'seneca-mongo-store'
... this.use(mongoStore)
```

You currently get error: (when transpiling under Babel)

```
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
```

Just an FYI. Loving Seneca. :)

**Comment by geek** [comment]
@quangv good catch.  I am hoping that we can deprecate the `use('math')` signature at some point, in favor of `use(Math)`.  Marking as a bug, but I recommend using the normal import/require for math and other modules.

**Comment by rjrodger** [comment]
We will move to standard module mechanisms as the recommended approached.

That said, the short cut will remain as an abbreviation for advanced users.

#hoistingownpetard

**Comment by mcdonnelldean** [comment]
... and for lazy people like me who have grown to love it :D

**Comment by mcdonnelldean** [comment]
Closing as we are going to keep the feature for now. Regular require is our recommend way to go when using babel or other similar tools.
