### ISSUE TITLE
act() will be removed from plugin initialization

### ISSUE THREAD

**Issue by cmfatih** [senecajs/seneca#272]
Is there any explanation about `act() will be removed from plugin initialization` ?

I see https://github.com/senecajs/seneca/pull/254 but it doesn't say neither why it is deprecated OR how to work around it...

**Comment by faceleg** [comment]
Came here to ask this. I did look through some of the official seneca plugins, assuming they would have been updated as examples, but wasn't able to see any differences.

**Comment by AdrieanKhisbe** [comment]
If I'm not mistaken, the way to work around this is to use the 
`ready` function to register a callback to execute after all plugins initialize.

I guess it have been deprecated to ensure that everything is set up correctly before to start sending commands with `act`

**Comment by mcdonnelldean** [comment]
Related to https://github.com/senecajs/seneca/issues/269

@geek @rjrodger

**Comment by quangv** [comment]
I've been experimenting on how to structure the code to get rid of these deprecation messages.

My conclusions is that you can't get rid of them. Only with the `--no-deprecation` flag.

How would you not show a warning for a plugin like
```
// entry.js
import addmore from './addmore'

seneca.use(addmore);
```
```
// addmore.js
import add from './add'

export default function send(options){
  this.use(add);

  this.add('role:math, cmd:addmore', function(msg, res){
    this.act('role:math, cmd:add', res);
  });
}
```

I tried the `.ready` suggestion, but I couldn't figure it out.

**Comment by bjonica** [comment]
@quangv Does wrapping the .act not work?

```
this.ready(function() {
  this.add('role:math, cmd:addmore', function(msg, res){
    this.act('role:math, cmd:add', res);
  });
});
```

**Comment by rjrodger** [comment]
seneca.act inside plugin _definition_ (i.e. the body of the module.exports function) is indeed deprecated, but is just fine elsewhere. Unfortunately this deprecation notice overreached, and applied to all plugin .act calls.

The seneca instance in the definition phase considers errors fatal - microservices should start cleanly or not at all. Errors in normal action processing are of course not fatal. The problem arises when the plugin definition instance of seneca is used inside actions, and then causes fatal errors.

**Comment by quangv** [comment]
@bjonica yeah that doesn't work...

In fact, the warning message pops up for me even if I don't call `.act`

```
  this.add('role:math, cmd:addmore', function(msg, res){
  });
```

**Comment by quangv** [comment]
Also I don't think the `--no-deprecation` works...

**Comment by geek** [comment]
We will revert this change in 0.9.2.   `--no-deprecation` will remove the warning, which comes from the node core `util.deprecate` function.

**Comment by faceleg** [comment]
Thanks for all of the info here.

It would be very helpful if someone could post the recommended way to add actions to plugins given the rules described above.
