### ISSUE TITLE
Seneca Governance in a Hapi way

### ISSUE THREAD

**Issue by AdrieanKhisbe** [senecajs/seneca#277]
Few days ago I discussed with @geek about @senecajs inner working,
and he told me he was considering for moving to a more of a hapi community style of governance.

Here is the description of such a governance from @hueniverse
- https://github.com/hapijs/hapi/issues/1836
- http://hapijs.com/governance

I think it's a very good starting point for seneca one's.

What do you think?
this is just a starter for discussion. :smiley:  :statue_of_liberty: 
@rjrodger @mcollina @mcdonnelldean @geek

**Comment by blainsmith** [comment]
Short and sweet. I like this.

**Comment by geek** [comment]
@AdrieanKhisbe and @blainsmith how does this look: https://github.com/senecajs/contrib/blob/master/governance.md

As part of this, we need to make it clearer on each of the repos who the lead maintainers are, if they have one... are there any repos that either of you want to help with? ;)

**Comment by AdrieanKhisbe** [comment]
haha, should have dig a bit more.

@geek Shall I use it to built a page on the website?

**Comment by AdrieanKhisbe** [comment]
About being lead maintainer, I'm really interested :)

Depends also, which specifically need a lead maintainer.

**Comment by blainsmith** [comment]
This is great!

And yes, I would be more than happy to lead maintain. Any would be fine with me really. Is there a list of "core" plugins that we think require it immediately? Then we can divide and conquer that list.

**Comment by AdrieanKhisbe** [comment]
A good way to do this, is to have a trello board with one card per plugin, 
labels for core, plugin, functionnality (transport, general, data)
and discussion for attribution occuring there.

@geek @rjrodger, jow does it sound? :smiley:

**Comment by geek** [comment]
@AdrieanKhisbe thanks for driving this.  At this point we should update all of repos in https://github.com/senecajs to make it clear who the lead maintainer is.  For any that the lead maintainer wants to hand over control to someone else they should open an issue asking for a new maintainer.

@AdrieanKhisbe and @blainsmith feel free to message me or open an issue for any of the repos on https://github.com/senecajs that don't have a maintainer that you want to help with.  Here are a few that are good candidates: generator-seneca-plugin, seneca-redis-queue-transport, seneca-rabbitmq-transport, seneca-stripe-pay, seneca-import-csv, getting-started, salestax-example, seneca-redis-sync-transport, seneca-level-store

**Comment by AdrieanKhisbe** [comment]
@geek, you're welcome :)

For starter I would say: generator-seneca-plugin, getting-starter

**Comment by blainsmith** [comment]
I made issues for salestax and level-store.

**Comment by AdrieanKhisbe** [comment]
:+1:

**Comment by geek** [comment]
I am closing this issue.  We can continue any updates on /discuss or /contrib.  @AdrieanKhisbe and @blainsmith are now lead maintainers of a couple of projects.  Thank you both for helping us all.
