### ISSUE TITLE
How to extend seneca entity action

### ISSUE THREAD

**Issue by longweiquan** [senecajs/seneca#284]
Hello Team Seneca,

I'm new to seneca. Could you tell me how to extend the seneca entity action ? For example, I want to add an action "paginate" to seneca-store-mongo entity. For example, I expect the usage like this,

```
var users = seneca.make('user');
users.paginate(QUERY, PAGINATION_OPTION, CALLBACK).
```

Thank you in advance.

**Comment by geek** [comment]
I don't have an amazing solution, but this should work.  You can add to the Entity prototype from the export we have exposed on your seneca instance:

```js
var Seneca = require('seneca');

var seneca = Seneca();
seneca.private$.exports.Entity.prototype.paginate$ = function (query, options, callback) {


};

var users = seneca.make('user');
users.paginate$(QUERY, PAGINATION_OPTION, CALLBACK);
```
