### ISSUE TITLE
How to add middleware

### ISSUE THREAD

**Issue by longweiquan** [senecajs/seneca#287]
Hello Seneca Team,

Is there some kind of feature like middleware in seneca ? I hope some features like this,

```
seneca.add('role:bar, cmd:test1', (args, response) => {
   console.log('test1');  
   response();
});
seneca.pre('role:bar', (args, next)) => {
  console.log('middleware');
  next();
}

seneca.act('role:bar, cmd:test1')
// console result
// middleware
// test1
```

Thank you in advance.

**Comment by geek** [comment]
At the moment, we do not.  However, if you want to handle all actions you subscribe to the act-in and act-out events:

```js
seneca.on('act-on', (actionArgs) => { });
```

**Comment by AdrieanKhisbe** [comment]
The way to go is to us prior. cf tutorial https://senecajs.org/tutorials/understanding-prior-actions.html

There are seneca way, to intercept some request to add behavior.

(@geek, think u can close ;) )
