### ISSUE TITLE
fat arrow support in seneca 1.0, via msg.meta$.seneca

### ISSUE THREAD

**Issue by rjrodger** [senecajs/seneca#288]
The problem is that the `this` reference is not correct when using `=>` (it's not the current seneca context).

Instead, provide it via the meta$ message property:

``
seneca.add( 'foo:1', (msg, done) => {
  msg.meta$.seneca.prior( ... )
})
``

**Comment by geek** [comment]
To avoid a major breaking change, we can add seneca to the meta properties.  But we will also need to add a backwards compatible way to unbind/not call the `(msg, done)` function.  To do this, I will add a `bind: { add: true/false, act: true/false }` option to seneca.  The default will keep the bind so as not to break current implementations.  But if a developer wants to use fat arrows for add/act they can disable the bind and use the seneca instance in msg.meta$

**Comment by geek** [comment]
After further thought, I am going to add the instance to the callback function.  The reason for this is that the meta$ object should be serializable, plus its a reserved property.

```
const Seneca = require('seneca');

const seneca = Seneca({ bind: { act: false, add: false } });
seneca.add('foo: 1', (msg, reply) => { 
  reply.seneca.act('foo: 2', (err, result) => {
    
  });
}); 
```

**Comment by mcollina** [comment]
Following [chairo](http://npm.im/chairo):

```js
const Seneca = require('seneca');

const seneca = Seneca();
seneca.add('foo: 1', (msg, reply) => { 
  reply.act('foo: 2', function (err, result) {
    reply(err, result + 2);
  });
});

seneca.add('foo: 2', (msg, reply) => { 
  reply.act('foo: 3'); // meaningless, but helpful
}); 
```

**Comment by rjrodger** [comment]
Ah good catch! Agreed

**Comment by mcdonnelldean** [comment]
Damn, I JUST came here to raise this point! As you were...
