### ISSUE TITLE
Asynchronous options

### ISSUE THREAD

**Issue by rjrodger** [senecajs/seneca#293]
The plugin lifecycle is currently:

0. Resolve global options, synchronously
1. Definition phase: call the plugin definition function *synchronously*, passing the resolved options
2. Initialization phase: call the plugin init:<name>,tag:<tag> action *asynchronously*

This prevents architectures where the microservice options are provided dynamically via consul etc.

We need to support an operational mode where you can say:

require('seneca')()
  .use('plugin-foo')  // gets synchronous options as per current version
  .use('consul-options') // grabs options from a consul service, async
  .use('plugin-bar') // gets merged local and consul options

Which suggests that define_plugin in lib/plugins.js needs to be called in series with the init actions, under the gate execution mechanism.

**Comment by mcollina** [comment]
I completely agree. However I would put this in v2. It might result in an
updated plugin API...
Il giorno gio 7 gen 2016 alle 17:44 Richard Rodger <notifications@github.com>
ha scritto:

**Comment by rjrodger** [comment]
It won't require an API change, as the call to define stays the same from the plugin perspective.

**Comment by mcollina** [comment]
Oh, yes, you are right.

**Comment by rjrodger** [comment]
In further discussion, this is a bug fix for 1.0.
The core issue is that seneca.act calls seneca.find synchronously, and this needs to be made async, so that action patterns defined async are not missing when used later

**Comment by geek** [comment]
Fixed by https://github.com/senecajs/seneca/commit/a2dbfbb8d99ba961bfce1d7d80fd11d7d774586d
