### ISSUE TITLE
Deprecate seneca.use('module') format

### ISSUE THREAD

**Issue by AdrianRossouw** [senecajs/seneca#295]
One of the most common gotchas with using seneca is that the most commonly recommended format for seneca.use is actually very unreliable and can lead to incredibly difficult to debug issues that present themselves differently on different machines.

I've lost days due to this, and I've seen many people suffer the same fate.

The crux is : `seneca.use('some-module')` instructs seneca to try and require() the module itself, but it does so from a different \_\_FILENAME\_\_ than your call. This means that the node_module resolution has a different starting point, and can very often end up resolving to a completely different file than you expect.

This in turn means that whether the code you are trying to debug is actually using the correct versions of modules you intend it to, is completely dependent on what else the developer has installed in his system in parts of the filesystem your code shouldn't even be looking at.

Additionally, this makes it impossible to browserify this code, might not be possible to webpack it (without some serious kludges) which means it can't possibly be properly supported in the new seneca 2.0 codebase, which is built with the ability to run on the client as one of it's goals.

The format that always works and always explicitly does what you tell it to, is to do:

```js
seneca.use(require('seneca-some-module'))
```

It doesn't quite roll off the tongue as nicely, but it doesn't break randomly in unexpected ways.

I'm of the opinion that we should act now, before we release 1.0 : 

1. by replacing all of the instances of the unreliable format in the documentation and site.
2. printing out a warning during application startup about this format being deprecated.
3. having that error message print out the file that is actually being included.
4. putting together an upgrade doc that explains how to change to the reliable format.

**Comment by rjrodger** [comment]
Absolutely not for 1.0 Adrian, sorry - the change is too big, and we need to get 1.0 out.

**Comment by mcollina** [comment]
I like `seneca.use('module')`, it's simple and used everywhere.

What I do not like, and I think it is a _bug_ that we should flag as deprecated is the fact that `seneca.use('local')` would try to do `require('./local')`. This is unintuitive and can possibly lead to obscure behavior.

If we can still support that, but trigger a deprecation warning in 1.0.0, that would help clarify the situation.

**Comment by mcdonnelldean** [comment]
Lol! and a couple of days before release no less.

My opinion on this one is it can wait until next version. I actually don't mind it to be fair, the only change I would really make is to sort what @mcollina  is saying, in that it probably shouldn't try to require locally as it's unintuitive.

Again though, I just don't think this is priority for V1 release.

**Comment by mcollina** [comment]
I agree that is not a priority for v1, but I think this is an issue we should tackle at some point in the near future.

**Comment by rjrodger** [comment]
Oh for sure my original implementation of the idea is pretty naff, so work is needed to improve the dev experience, provide better errors etc. I'm sure we'll have fun with this.

I know hapi decided not to tackle this problem, but I would like to. I think the nicer developer experience is worth it, and it fits with the Seneca principle of accepting harder work internally to make the API cleaner (by which I mean as small and simpe as possible).

**Comment by mcdonnelldean** [comment]
@geek @rjrodger Do we have an under-consideration or in-future tag? I'll make a note saying we should revisit the feature to make it a little sleeker in the future.

**Comment by AdrianRossouw** [comment]
Well, my distrust of this feature comes from not only the bugs it has caused for myself and others, but also from trying to work around the underlying problem in several previous systems I built.

It comes down to not having access to \_\_filename in the requiring code, so you can't even accurately reproduce the node_modules logic. I've never been able to get access to the right things at the right time,
without explicitly passing in the __dirname everywhere. (something like `seneca.use('something', __dirname)`). I liked that solution even less.

I should also mention that because this is very much dependent on the file system layout, this will get triggered differently based on the order you installed modules, whether you are using npm 3 or not, or many other variables.

Any message we print out has to print out the file it actually loaded, to give you enough context to debug with.

and lastly, any changes we make to this algorithm can result in code that is already working suddenly stop working. so we add another variable to the mix about how it behaves.

**Comment by mcollina** [comment]
I agree with @AdrianRossouw, I did not thought of the difference between npm 2 and 3.

However, I also see Richard's point on v1 vs v2. I would point that this is one of the first thing where we should break compatibility.

I would also note that changing the docs so that external modules are required using `require()`, makes no compatibility breakage.

**Comment by geek** [comment]
@mcdonnelldean anything labeled `request` is under consideration
