### ISSUE TITLE
suggest add a tell which donot need response

### ISSUE THREAD

**Issue by For-Eleven** [senecajs/seneca#299]
now the act function is always waiting the response.
suggest add a tell function just call the service.  like  [scala akka](http://akka.io/) actor's tell and ask.

is possible add some akka's features?

**Comment by mcdonnelldean** [comment]
@For-Eleven You mean fire and forget on act? I believe @geek has something in the pipeline for this soon.

**Comment by rjrodger** [comment]
A response is not needed - you are allowed to say:
`seneca.act('foo:bar')` with no callback.

In the definition of the action, you are still required to call the callback - a result is not required - `done()` is sufficient. The callback is needed to signal that you are complete - you are allowed to make async calls inside the action, so a simple return is not enough.
