### ISSUE TITLE
Instance continues to live after role:seneca,cmd:close is sent

### ISSUE THREAD

**Issue by bjonica** [senecajs/seneca#308]
To preface, I don't know if this is a bug or just something I need clarification on. 

I played around with the actions in [this block](https://github.com/senecajs/seneca/blob/master/seneca.js#L1654-L1658) and discovered a couple of issues.

I set up a seneca instance with stats logging: 
```javascript
var service = seneca({
  status: {running: true},
  stats: {running: true}
}).listen({path: '/test-plugin/act', port: 8080});
```

As is expected, I get status updates every 60 seconds in the logs.
I can hit `$HOST/test-plugin/act?role=seneca&cmd=stats` to get more detailed status

Then, I hit `$HOST/test-plugin/act?role=seneca&cmd=close` and after a short delay, the `cmd:stats` action stopped working. As is expected, since the instance should have closed. However,

1. The instance is still up and running, just not listening to any port
2. The instance is still logging a status with an increasing alive property:  
```
2016-01-13T16:57:56.180Z g3dslpig4hb2/1452703256037/30130/- INFO	status	{alive:1020144,act:{calls:17,done:17,fails:0,cache:0}}
2016-01-13T16:58:56.187Z g3dslpig4hb2/1452703256037/30130/- INFO	status	{alive:1080151,act:{calls:17,done:17,fails:0,cache:0}}
```

Should the service have died after the close action? Should alive stop incrementing?

**Comment by rjrodger** [comment]
Seneca.close does not call process.exit, as it may not be appropriate depending on the use case.

You can provide a callback to Seneca.close and call it yourself - this would work
