### ISSUE TITLE
Api to api calls using seneca.js server

### ISSUE THREAD

**Issue by atownup** [senecajs/seneca#309]
Hello,

I am trying to make an outbound http call to a different api from a seneca micro service's action, but not having any luck.  Is there a reason why I wouldn't be able to do this?  In essence the micro-service needs to call out to many others to get back data, aggregate it, and return it to the client.

**Comment by rjrodger** [comment]
See rjrodger/nodezoo-search for an example of calling out to elasticsearch over http 

Which http client module are you using?

**Comment by mcdonnelldean** [comment]
@atownup Nodezoo is a pretty good example of using seneca in different context. If you have any other questions feel free to open.
