### ISSUE TITLE
npm warnings on clean install

### ISSUE THREAD

**Issue by rjrodger** [senecajs/seneca#313]
npm WARN peerDependencies The peer dependency eslint-plugin-hapi@x.x.x included from eslint-config-seneca will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.

we need to get rid of these - broken windows and all that...

**Comment by wprl** [comment]
I tested this and received no warning messages when running these commands:

```bash
cd project
npm init
npm install seneca
```

There is a warning generated by the installation of the `marked` package when running these commands in the current master branch commit (https://github.com/senecajs/seneca/commit/4f22c7d136fc78ac25a22c7730025d4482ae7716):

```bash
cd project
git clone https://github.com/senecajs/seneca.git .
npm install
```

The warning message is `npm WARN prefer global marked@0.3.5 should be installed with -g`.  I left a comment about this on a closed ticket in that project: https://github.com/chjj/marked/issues/652#issuecomment-193307524 .  My opinion is the `preferGlobal` flag should be deprecated, but some projects use it.

seneca@1.3.0
npm@3.8.0
node@5.4.1

**Comment by mcdonnelldean** [comment]
This should be good now, it will be for next release if not.
