### ISSUE TITLE
Does Seneca provide 'filters'

### ISSUE THREAD

**Issue by jhyland87** [senecajs/seneca#316]
Im looking for a new plugin system, and Seneca looks like the best one so far, the only question I have, is does it provide filters? Something similar to WordPresses [add_filter()](https://codex.wordpress.org/Function_Reference/add_filter) functionality, where I can add actions to my code that are specified via tags (or something similar), and plugins can add filters to interact/alter that content specified by the same tag.

Thanks

**Comment by mcdonnelldean** [comment]
We are a pattern matched system so it's pretty much filters the whole way down :D You can even get access to the less specific action handler that would have handled the message had you not overridden it via `this.prior` in the action handler.

**Comment by jhyland87** [comment]
Nice, is there a way to set priorities?

**Comment by jhyland87** [comment]
Also, I was playing around with some of the demo code, and I was just trying to simulate two plugins both pushing an element to an array:
```javascript
var seneca = require('seneca')()

seneca.add({ cmd: 'array_push' }, function (args, callback) {
    var arr = args.arr
    arr.push('b')
    callback(null, { arr: arr })
})

seneca.add({ cmd: 'array_push' }, function (args, callback) {
    var arr = args.arr
    arr.push('c')
    callback(null, { arr: arr })
})

seneca.act({ cmd: 'array_push', arr: ['a'] }, function (err, result) {
    console.log('Array', result.arr)
})
```
The result is `Array [ 'a', 'c' ]`, I was expecting `Array [ 'a','b', 'c' ]`. Am I doing something wrong?

**Comment by n321203** [comment]
You have added two services with identical patterns, Seneca will choose and run one of them. 
(In general, the more specific pattern always wins, so the pattern with the highest number of matching attributes has precedence. In this case the patterns are identical).

**Comment by jhyland87** [comment]
Oh, I was trying to interact with the array two different times, (as if two different plugins were), is there a way to do that?
