### ISSUE TITLE
Check for Priors inside callback when adding actions to patterns

### ISSUE THREAD

**Issue by jhyland87** [senecajs/seneca#317]
Earlier I had a question regarding action priorities and having multiple actions for specific patterns, and that question seems to be answered by the *[prior](http://senecajs.org/tutorials/understanding-prior-actions.html)* property. 

However, when adding callbacks to patterns, is it possible to see *if* there is a prior action? I would think that when using a large amount of plugins, if some of the plugins operate off some common patterns, any given callback/function may not have a certain way of knowing if it is or isn't the first plugin to add an action to that pattern. Meaning its uncertain if it should or shouldn't check for priors.

In the tutorial above, it states:
> ... take care when adding plugins whose purpose is mainly to extend existing patterns. They should be added after the main plugin that adds functionality.
But how is the application to know what order the plugins should be added? Isn't that something the plugin should dictate?

I took some of the example JS from the snippets in the above article, and tried to check if there was/wasn't a prior via the `this.prior` when adding actions to a pattern, but that doesn't seem to work, because even if there *isn't* a prior, `this.prior` is a `function` (using typeof). 

Also, if you change line #6 to `false`, then the script will throw an error, obviously because the logic in checking for a prior isn't right.

**Question**: How can I check if theres already a prior action for a pattern, within the new action being added? And shouldn't that check be in nearly every action? Especially if its a 3rd party plugin to an application?

Thanks!

**Comment by rjrodger** [comment]
Seneca.has( pat ): bool
