### ISSUE TITLE
Behavour of system changes when --seneca.print.tree specified

### ISSUE THREAD

**Issue by andriy-zhelvachenko** [senecajs/seneca#321]
Code is posted here
https://gist.github.com/anonymous/fb326649051c788d24d4

**Comment by mcdonnelldean** [comment]
@andriy-zhelvachenko Could you provide me with a bit more context here?

**Comment by mcdonnelldean** [comment]
@andriy-zhelvachenko I've had a look over the sample but I can't figure out what the context of it is in relation to the reported issue. Also this,

```js
 s.add({init: plugin}, function(error, done){
    _.forEach(s.list(), function(act){
      s.add(act, checkPerms);
    });
    done();
  });
```

Is not a good idea. You would be better off using a known root in your patterns and star matching, eg,

```js
seneca.add('role:*', checkPerms)
```

Star matching is supported and priors work off of matches so anything that had role in the name would hit this pattern. 

I'm going to close this as needs more info. If you have any more context to add or have any questions please reopen and we can chat.
