### ISSUE TITLE
Seneca.handles(pin):  bool

### ISSUE THREAD

**Issue by mcdonnelldean** [senecajs/seneca#324]
@rjrodger @geek I've been thinking about this for a bit, is there a way to ask seneca if a handler is available for a particular message. It would need to work across transports to be of any use so I don't know if it's feasible.

My use case would decision based plugin loading. In the case of vidi, it would be super nice to control loading seneca-user locally based on whether 'role:user, cmd:*' could be handled or not. Eg

```js
const Seneca = require('seneca')()
 // .. some init bits

if (!Seneca.handles('role:user, cmd:*')) {
  Seneca.use('user')
}

Seneca.act({role: user, cmd: register, ...})
```

**Comment by rjrodger** [comment]
Seneca.find will work both for local and transport defined patterns.

If statements in general are bad news :)
And you have to wrap the .cliebt in an if statement too

Why not simply have separate start scripts?
These are very different deployment modes anyway, and will probably have other differences.

**Comment by rjrodger** [comment]
Also see Seneca.has(...) :)

**Comment by mcdonnelldean** [comment]
Points to note

- handles might not be the right name here
- This might be better as a function on seneca-mesh

**Comment by mcdonnelldean** [comment]
@rjrodger I actually went over the nodezoo stuff again just after writing this and I think discreet scripts are actually the way to go here. As I solved one issue another popped up. The correct way does seem to be compositional scripts. Closing, will add some bits to the FAQ once I update vidi.

**Comment by rjrodger** [comment]
And: this test will break if Seneca-user makes use of pre existing patterns as part of override functionality

**Comment by mcdonnelldean** [comment]
yup, it was at the point of overrides when I began to realise I was going down the completely wrong path here. There is only so much fighting against a path you can do before you realise you need to back up :D

@rjrodger Do you want to keep this open for a particular reason?

**Comment by rjrodger** [comment]
Fat fingered - on phone!

**Comment by mcdonnelldean** [comment]
Ha!
