### ISSUE TITLE
Improve default option handling in plugins.

### ISSUE THREAD

**Issue by rjrodger** [senecajs/seneca#325]
Seneca can then perform the deep override for the plugin, removing need for yucky Seneca.util.deepextend call

```
function foo( options ) {
  // prints "c b"
  console.log( options.x, options.y )
}
foo.defaults = {
  x: 'a',
  y: 'b'
}

seneca.use( foo, { x: 'c'})
```

**Comment by mcdonnelldean** [comment]
@rjrodger Is this to remove the boilerplate of having to declare defaults and extend using deepextend?

**Comment by mcdonnelldean** [comment]
Love it! I neeeed this. Brevity FTW!

**Comment by andriy-zhelvachenko** [comment]
I have one more question/request.

Is it possible also to incorporate config loading for plugin?

I.e. 

require('seneca')()
  .use('options', 'my-config.js')
  .use('my-plugin', {p1:'v1'})

Would it be possible to take plugins' section from config, mix it with passed params, and then mix it with deffaults?

**Comment by andriy-zhelvachenko** [comment]
otherwise i have to do
var loadedOpts = s.export('options')['my-plugin'];

and then mix it with passed params, and defaults

**Comment by mcdonnelldean** [comment]
@andriy-zhelvachenko I'd say open a new issue for that, it's worth exploring.

**Comment by rjrodger** [comment]
@andriy-zhelvachenko it should work this way already. needs a unit test to confirm

**Comment by rjrodger** [comment]
done
