### ISSUE TITLE
I wonder why Seneca throttles error returned by seneca service?

### ISSUE THREAD

**Issue by andriy-zhelvachenko** [senecajs/seneca#326]
I.e. i have developed seneca service (add) that connects to external system.
If external system is not available it returns error (object with details), however Seneca somewhat throttles that error object and it is not possible to retrieve it on the client side (act)

**Comment by mcdonnelldean** [comment]
@andriy-zhelvachenko Can you provide an example? I'm not clear on the issue?

**Comment by andriy-zhelvachenko** [comment]
if your service does the following

s.add('cmd:x', function(msg, reply){
  reply({status:'error', data:'xyz'}, null);
})

in client i never see that error object that service has sent

s.act('cmd:x', function(error, result){
  // here i want to extract error details
})

**Comment by mcdonnelldean** [comment]
That doesn't seem right, if you console.log both error and result in the act handler what do you see?

**Comment by andriy-zhelvachenko** [comment]
Here is the test

#!/opt/local/bin/node

require('seneca')()
  .use(function(opts){
    var s = this;
    s.add('some:action', function(msg, respond){
      //respond(null, {status:'ok', data:'abc'});
      respond({status:'error', data:'xyz'}, null);
    });
    return 'test-plugin';
  })
  .ready(function(){
    var s = this;
    s.act('some:action', function(error, data){
      console.log('Client|Error: ' + JSON.stringify(error));
      console.log('Client|Data: ' + JSON.stringify(data));
    })
  });

**Comment by andriy-zhelvachenko** [comment]
Here is the output (i cannot see my data there)

Client|Error: {"eraro":true,"orig":{"eraro":true,"orig":null,"code":"unknown","gate-executor":true,"package":"gate-executor","msg":"gate-executor: action-error","details":{"id":"m8uuqz0gmc4n/zgtp67j1blji","gate":false,"ungate":false,"desc":"some:action","plugin":{"name":"test-plugin","tag":"-"},"time":{"start":1454275174784,"end":1454275174784}},"callpoint":"at /Users/mypath/node_modules/gate-executor/gate-executor.js:122:23"},"code":"act_execute","gate-executor":true,"package":"seneca","msg":"seneca: Action some:action failed: gate-executor: action-error.","details":{"id":"m8uuqz0gmc4n/zgtp67j1blji","gate":false,"ungate":false,"desc":"some:action","plugin":{"name":"test-plugin","tag":"-"},"time":{"start":1454275174784,"end":1454275174784},"message":"gate-executor: action-error","pattern":"some:action","instance":"Seneca/1.0.0/efm13h1nb9qp/1454275174583/47933/-","orig$":{"eraro":true,"orig":null,"code":"unknown","gate-executor":true,"package":"gate-executor","msg":"gate-executor: action-error","details":{"id":"m8uuqz0gmc4n/zgtp67j1blji","gate":false,"ungate":false,"desc":"some:action","plugin":{"name":"test-plugin","tag":"-"},"time":{"start":1454275174784,"end":1454275174784}},"callpoint":"at /Users/mypath/node_modules/gate-executor/gate-executor.js:122:23"},"message$":"gate-executor: action-error"},"callpoint":"at /Users/mypath/node_modules/gate-executor/gate-executor.js:122:23","seneca":true}

**Comment by mcdonnelldean** [comment]
Huh, it should be in there, or so I thought. @geek Any ideas on this one.

**Comment by rjrodger** [comment]
@andriy-zhelvachenko better to use a full Error object: new Error('xyz')
or use https://www.npmjs.com/package/eraro module

We are painfully aware that error handling needs an overhaul

**Comment by mcdonnelldean** [comment]
@andriy-zhelvachenko This will be overhauled as part of #398. Right now you need to use a full error object to get it to work.

**Comment by knasher** [comment]
I know this has been closed, but I'm having the same issue when testing for errors in a unit test. It looks as though sending anything other than null in the place of an error in the response lambda results in a fatal error.

**Comment by knasher** [comment]
Further to this, I was able to check the global error object

```javascript
seneca.error((err) => {
    expect(err).to.be.exists();
});
```

Since the error was fatal and the test was to increase coverage, I've found that the lines I was testing will not be executed so I've removed them.
