### ISSUE TITLE
Is it possible for 3rd party seneca component to receive response of seneca service to seneca client?

### ISSUE THREAD

**Issue by andriy-zhelvachenko** [senecajs/seneca#328]
I have seneca service defined with s.add('cmd:x',...)
I have seneca client requesting s.act('cmd:x',...)

When 3rd seneca component subscribes to s.sub('cmd:x', ..)
Then it only receives requests/act messages.
 
Is there any way to receive response too?

**Comment by mcdonnelldean** [comment]
`.sub()` is used only as a listener, it won't ever return the response. Generally the response is only ever sent to the returning act. 

What is it you are trying to do, maybe we can see about helping you in doing it another way.

**Comment by andriy-zhelvachenko** [comment]
in this case sub() is the same as

add('same:pattern', function(msg, done){
  done();
})

Is this correct?

**Comment by andriy-zhelvachenko** [comment]
Generally i wanted to implemented multiple receivers for the same request
- primary receiver (who initiated the request) would display the result
- another receive would store the result (independently)

I understand that i can probably get the same behaviour by 
1) either by making service replying to request AND "fire"-ing out event
    - in this case secondary receiver would do the sub()
2) or initiator would "fire"-d the request to the service
    - service would "fire" the event
    - both primary and secondary receives can do "sub()"

Any other ways to do that?

**Comment by mcdonnelldean** [comment]
So the correct way to do this where it's the response you are looking for in multiple places is with multiple patterns because they are different concerns. so like,

`role: foo, cmd: do-stuff`
`role: foo, info: stuff-done`

Responses to actions can't be listened to by anyone else bar the initiator.

**Comment by mcdonnelldean** [comment]
In terms of sub, it's more for listening to what fired, not what was responded. Like an event emitter where each acted pattern is treated like an event.

**Comment by andriy-zhelvachenko** [comment]
Ok, tnx. I just thought that request-reply pattern works similar to HTTP. 

I.e. if you can intercept request, you can probably intercept response too

**Comment by mcdonnelldean** [comment]
@andriy-zhelvachenko It sort of is but instead of being coarse grained you instead be more finely grained. This leads you to have a bunch of override points later too so works really well. Generally every action should be a pattern.
