### ISSUE TITLE
Does seneca.sub() work?

### ISSUE THREAD

**Issue by andriy-zhelvachenko** [senecajs/seneca#330]
If replace sub() with add() it works normally. 

Any hint on what going on?

**Comment by andriy-zhelvachenko** [comment]
To generate event is this script

require('seneca')()
  .use('mesh', {auto:true})
  .use('fire-and-forget')
  .ready(function(){
    var s = this;
    setInterval(function(){
      s.fire({data:'xxx',secret:'yyy', 'default$': {status:'default'}});
    }, 10000);
  });

**Comment by andriy-zhelvachenko** [comment]
This works properly (receives events) 

#!/opt/local/bin/node

require('seneca')()
  .use('mesh', {auto:true, pin:'data:xxx'})
  .ready(function(){
    var s = this;
    s.add('data:xxx', function(msg, done){
      console.log('Client|Message: ' + JSON.stringify(msg));
      done(null, {status:'ok'});
    });
  });

**Comment by andriy-zhelvachenko** [comment]
This does not work (i just replaced add() with sub())

#!/opt/local/bin/node

require('seneca')()
  .use('mesh', {auto:true, pin:'data:xxx'})
  .ready(function(){
    var s = this;
    s.sub('data:xxx', function(msg, done){
      console.log('Client|Message: ' + JSON.stringify(msg));
      done(null, {status:'ok'});
    });
  });

**Comment by andriy-zhelvachenko** [comment]
Tested it without mesh. Same result! :(

**Comment by mcdonnelldean** [comment]
Sub does not work over the network as far as I am aware, only within the same process

**Comment by andriy-zhelvachenko** [comment]
Yes, all my tests were from different processes

Tnx
