### ISSUE TITLE
Use Keep A Changelog Format

### ISSUE THREAD

**Issue by AdrieanKhisbe** [senecajs/seneca#335]
We have a Changelog, CHAGES.Mmd in a custom format.
*What I suggest is to adopt the emerging http://keepachangelog.com/ format. :smiley:*

This give more readable changelogs, more structured, stating specificaly the version policy (semver), 
and with links to the diffs.
Here is one example https://github.com/AdrieanKhisbe/configue/blob/master/CHANGELOG.md

I can take care to apply it ;)

@senecajs/core your call :)

**Comment by AdrieanKhisbe** [comment]
(note, if we decide to do so, I'll add it to the plugin generator: https://github.com/senecajs/generator-seneca-plugin)

**Comment by geek** [comment]
@AdrieanKhisbe looks reasonable to me, go for it!

**Comment by AdrieanKhisbe** [comment]
@geek Okey Dokey 
![](http://manmashup.com/wp-content/uploads/2015/09/wait-for-it.jpg)

It's gonna be....
