### ISSUE TITLE
Can multiple seneca services (add) respond to same seneca client's request (act)?

### ISSUE THREAD

**Issue by andriy-zhelvachenko** [senecajs/seneca#337]
Context of question assumes that services pattern is the same & cleitn should receive all responses.

If yes, does any extra configuration needed?

P.S. These services will be running in different processes and located via mesh

**Comment by geek** [comment]
Is this the behavior you want to have happen?  

You should be able to execute `client()` multiple times for a single seneca instance and connect it to multiple services.

**Comment by andriy-zhelvachenko** [comment]
do i have to call s.client() in mesh context too?

**Comment by andriy-zhelvachenko** [comment]
I do not call client() or listen(). Instead i use mesh.

I want to mimic publish-subscribe behaviour.
Since fire()/sub() do not work out of box for distributed configuration.
I try to mimic it using "act() for pub()", and "add() for sub()"

What i noticed that "act/pub/client" will only receive one response (from add/sub).
All other responses are discarded

Is it possible to make seneca delivery responses of other "add/sub"-s too?

**Comment by geek** [comment]
There is a `seneca.sub` function you can use to be notified when a pattern is acted upon.  I don't see that we have documentation on this feature :/  Here is the code that creates the sub function: https://github.com/senecajs/seneca/blob/master/seneca.js#L611-L641

**Comment by andriy-zhelvachenko** [comment]
Yes, but "sub" cannot be used remotely. 
I can achieve the same but distributed "sub" behavior with "add"

But my question about receiving multiple responses (from multiple "add" on "act" side)

**Comment by mcdonnelldean** [comment]
@andriy-zhelvachenko add yes, respond no, not like that.

You can't have 3 acts and 3 responds. But you can get this sort of thing with priors. What happens if you load a prior is it will call each in turn and collect the answers and respond back.
