### ISSUE TITLE
Differing registration order between 1.0.0 and 1.1.0

### ISSUE THREAD

**Issue by chiefy** [senecajs/seneca#339]
[Here's a gist](https://gist.github.com/chiefy/a770c2cccd439e8bd915) 

Note the differing output between version `1.0.0` and `1.1.0` I am somewhat of a n00b to seneca, so I am not exactly sure which should "win" in this case?

**Comment by edimoldovan** [comment]
Would you like to detail your question a bit? I don’t see where you are getting at.

**Comment by mcdonnelldean** [comment]
@chiefy Yup, it has to do with working on on making plugins async. @geek Will be able to explain it better.

**Comment by chiefy** [comment]
@mcdonnelldean @geek this change broke our tests :cry: shouldn't it had been a major release `2.0.0`?

**Comment by blainsmith** [comment]
Chiming in as well. To follow up with what @chiefy said since we work together. When we have our test suite run we have a separate seneca instance set up that we re-`add` actions of plugins so we can mock out responses.

**seneca-test-helper.js**
```js
seneca.use('odd-catalog');

// Override pattern from odd-catalog with mock response
seneca.add({role: 'catalog', cmd: 'fetchVideo'}, function (args, done) {
  done(null, {id: 'mock-video', title: 'Mock Video'});
});
```

Would there be a better way to handle this in the future since the 1.0.0 update?

**Comment by cristianianto** [comment]
You can try moving the `seneca.add` call inside a `seneca.ready` callback.

**Comment by chiefy** [comment]
@cristianianto thank you! that totally worked. cc: @blainsmith

**Comment by geek** [comment]
@chiefy glad its all working now... please take a look at https://github.com/senecajs/seneca/issues/334 and let me know if there is anything I can do to make the upgrade easier for others.
