### ISSUE TITLE
seneca.act callback limited to two arguments

### ISSUE THREAD

**Issue by chesles** [senecajs/seneca#340]
I came across this while using [seneca-postgres-store](https://github.com/senecajs/seneca-postgres-store)'s `native` method. The callback to `native` expects 3 arguments: `err`, `client` and a `done` callback that is used to release the client back to the connection pool. When using the `native` method, the 3rd argument is not passed back, so there's no way to release the client when finished.

I traced the problem to where the callback gets called in [seneca.js](https://github.com/senecajs/seneca/blob/v1.1.0/seneca.js#L1231):

```js
actdone.apply(delegate, result.slice(0, 2)) // note: err == result[0]
```

I can't think of any problems that might arise from allowing 3+ arguments here; was there a good reason for slicing off the rest of the arguments? It looks like before 9397de63bcf seneca just passed everything along.

**Comment by chesles** [comment]
A simple example to demonstrate this:

```js
seneca.add({ role: 'sample', cmd: 'arity-test' }, function (args, done) {
  return done.apply(null, args.items)
})

var items =  [ null, { one: 1 }, { two: 2 }, { three: 3 }] 
seneca.act({ role: 'sample', cmd: 'arity-test', items: }, function () {
  console.log('Got %s arguments', arguments.length)
  // Got 2 arguments
})
```

**Comment by rjrodger** [comment]
sorry - this is by design - the response is ideally a JSON object containing everything you want to send back
