### ISSUE TITLE
best practice for handling sigterm ?

### ISSUE THREAD

**Issue by RamonDonnell** [senecajs/seneca#342]
Heroku kills apps gracefully with sigterm on a regular basis. Good practice is to handle sigterm and stop taking requests, finish or re-queue any current requests.

Whats the best practice with seneca. [Sigterm](https://github.com/senecajs/seneca/blob/d02bc9e08261f625e2b27ae383e19a436d57c599/seneca.js#L154) and other signals in seneca are [handled](https://github.com/senecajs/seneca/blob/d02bc9e08261f625e2b27ae383e19a436d57c599/seneca.js#L1783) and [exit the process](https://github.com/senecajs/seneca/blob/d02bc9e08261f625e2b27ae383e19a436d57c599/seneca.js#L871), although there is some log output before exit.

How do I stop a seneca client (web, redis or other) and do other processing after a sigterm?

**Comment by geek** [comment]
A good practice is to handle the `seneca.once('close'` event.  This should be triggered on a SIGTERM... then you can gracefully handle current requests.

**Comment by mcdonnelldean** [comment]
@geek This is one for the FAQ I think, I found out something new today :D

**Comment by nfantone** [comment]
So... is it wrong if I handle the signal and call `seneca.close()` manually? Is that called automatically on `SIGINT` or `SIGTERM`?

**Comment by cjnqt** [comment]
``A good practice is to handle the seneca.once('close' event. This should be triggered on a SIGTERM... then you can gracefully handle current requests.``

Any info available on the seneca.once('close' event?

**Comment by mcdonnelldean** [comment]
Related #398

**Comment by mcdonnelldean** [comment]
Folks we are redoing error's in the next version or too, this will come with proper docs. See https://github.com/senecajs/seneca/issues/398
