### ISSUE TITLE
How can one discard/unregister pattern registered with "add"?

### ISSUE THREAD

**Issue by andriy-zhelvachenko** [senecajs/seneca#344]
See subject.

**Comment by mcdonnelldean** [comment]
There isn't one as far as I know, could you describe your use case?

**Comment by andriy-zhelvachenko** [comment]
I implement pub-sub with act/add. I have multiple subscribers. I need for subscribers to be unsubscribe at some point

**Comment by andriy-zhelvachenko** [comment]
Subscribers and publishers are located in different process. And are finding each other via mesh.

**Comment by rjrodger** [comment]
@andriy-zhelvachenko the mesh will remove the subscribers when they terminate

**Comment by mcdonnelldean** [comment]
Yeah, so if you are using mesh it will handle it all for you. Generally the reason this isn't part of the API is,

1: It usually causes issues, so is not recommended
2: In pubsub cases (where it makes sense), it should be handled by the transport

I have a guide on mesh coming before the end of the month to coincide with 3.0 releasing, it will have more detail on this. I'm going to close but if you have any more issues feel free to reopen, cheers!
