### ISSUE TITLE
Listen unix socket

### ISSUE THREAD

**Issue by rumkin** [senecajs/seneca#346]
Is it possible to listen unix socket?

**Comment by geek** [comment]
At the moment we do not... This wouldn't require much effort.  We just need to support a `path` in the listen arguments.  A PR is welcome.  Here is the code that needs to change: https://github.com/senecajs/seneca-transport/blob/master/lib/tcp.js#L75

**Comment by rumkin** [comment]
Done https://github.com/senecajs/seneca-transport/pull/76
