### ISSUE TITLE
Why do errors in seneca cause app termination?

### ISSUE THREAD

**Issue by DigitalLeaves** [senecajs/seneca#356]
Hi, we were thinking in adopting seneca for our app. We are in the process of adapting the backend to seneca, and we have found some really weird behavior I would like to ask you about. We are using express to build our REST API and separate all entities, model, database, authentication, etc in different seneca services.

If I have a module with:
```
// This module is in charge of registering and authenticating the user
...
seneca.add({...}, function (args, done) {
   // imagine a parameter is missing for user registration, so I throw:
   done (new Error("Missing parameters for registering user"))
})
...
```
Then, this error causes app termination, and I get this error:
```
Seneca Fatal Error
==================
Message: seneca: Action cmd:add,role:user failed: Missing parameters for registering user.
```

Is this to be "expected"? I think this is a really weird behavior (errors are supposed to be controlled ways of declaring that something went wrong). What I would expect is the call returning the error to the "act" receiving client, so in the client:

```
seneca.act({...}, function (err, user) {
   // I would expect err here to have that "Missing parameters for registering user".
})
```

Please, let me know if I am missing something, because we cannot take a seneca environment into production if an error in one of the seneca actions will cause app termination. Maybe I'm missing something really obvious here.

**Comment by geek** [comment]
@DigitalLeaves the default is to make those errors fatal, which is not always the desired behavior.  You can change this by adding `fatal$: false` when you execute an action.

Your example would be changed to:

```js
seneca.act({..., fatal$: false }, function (err, user) {
   // I would expect err here to have that "Missing parameters for registering user".
})
```

**Comment by DigitalLeaves** [comment]
Hi @geek, thanks for your prompt response and for giving me a way of addressing this issue. Is there a way I can change that default behavior in Seneca? If not, I would strongly suggest you to add one, because I can possibly think of an scenario where app termination is preferred over a controlled response error.

**Comment by DigitalLeaves** [comment]
Hi Again @geek, I added the "fatal$: false" and still is exiting, so it seems it's not working. I am calling a seneca action (role: "auth", cmd: "register"), which in turn calls a seneca action (role: "user", cmd: "add")

```
seneca.act({role: "auth", cmd: "register", email: "xxxx@yyyyyyy.com", fatal$: false}, console.log)
```
This is the "register" function:
```
    seneca.add({role: "auth", cmd: "register"}, function (args, done) {
        // check parameters
        if (args.first_name && args.last_name && args.email && args.password && args.locale) {
            seneca.act({role: "user", cmd: constants.SENECA_CMD_ADD, object: args, fatal$: false}, done)
        } else { return done(new Error("Missing parameters for user registration")) }
    });
```

And the output is:
```
Message: seneca: Action cmd:add,role:user failed: Missing parameters for user registration.
...
Stack: 
    at Seneca.add (/.../model/user.js:65:26)
    at /.../node_modules/seneca/seneca.js:1123:22
    at act_param_check (/.../node_modules/seneca/seneca.js:1467:17)
    at Object.execute_action [as fn] (/.../node_modules/seneca/seneca.js:1067:7)
    at Immediate._onImmediate (/.../node_modules/seneca/node_modules/gate-executor/gate-executor.js:135:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
Instance: Seneca/1.2.0/llam3z4opvgy/1456824053249/64186/undefined
  ALL ERRORS FATAL: action called with argument fatal$:true (probably a plugin init error, or using a plugin seneca instance, see senecajs.org/fatal.html)
    at act_done (/.../node_modules/seneca/seneca.js:1185:29)
...
SENECA TERMINATED at 2016-03-01T09:21:05.330Z.
...
```
Any idea?

**Comment by geek** [comment]
@DigitalLeaves thanks, I am marking this as a request.  This means that we are definitely open to the change.  Feel free to submit a PR, otherwise it may be an iteration before the change makes it in.

**Comment by DigitalLeaves** [comment]
Hi @geek , thank you very much. I definitely want to be able to get familiar with the seneca code and being able to contribute, but I don't know if I will get to that point soon. Anyway, this is something I would love to do, because I think this is a great project.

**Comment by mcdonnelldean** [comment]
Related to #398

**Comment by mcdonnelldean** [comment]
@DigitalLeaves we are redoing error handling to make it more sensible as part of #398 I'm going to close this as a merge because we will be adding switches like above to make everything more sane.
