### ISSUE TITLE
Is actmeta.descdata properly respected?

### ISSUE THREAD

**Issue by brycereynolds** [senecajs/seneca#360]
I haven't seen any documentation as to the proper use of the `descdata` field but I've see that [seneca-user](https://github.com/senecajs/seneca-user/blob/master/user.js#L416-L418) makes use of it's syntax.

I want to alter my logs at the action level so I was hoping this would be a path to completing that (we have big objects, I want to log them).

When I print the value of `actmeta.descdata` at the point of logging for act_in I see this is the dump:

```
{ plugin_name: 'user',
  plugin_tag: '-',
  plugin_fullname: 'user',
  log:
   { [Function]
     debug: [Function],
     info: [Function],
     warn: [Function],
     error: [Function],
     fatal: [Function] },
  sub: false,
  client: false,
  deprecate: undefined,
  parambulator: { toString: [Function], validate: [Function] },
  args: { role: 'user', cmd: 'upsert' },
  pattern: 'cmd:upsert,role:user',
  argpattern: 'cmd:upsert,role:user',
  id: '(wy4g1)',
  func: { [Function: cmdUpsert], descdata: [Function] },
  priorpath: '' }
```
Here you can see that `actmeta.func.descdata` is actually the full path to the function.

Yet in the code for all of the logging methods it is looking in `actmeta.descdata`. Here is the `log_act_in` method that I am printing from:

Reference: https://github.com/senecajs/seneca/blob/master/lib/logging.js#L539-L566
```
exports.log_act_in = function (instance, actinfo, actmeta,
  args, prior_ctxt, act_callpoint) {
  if (actmeta.sub) {
    return
  }

  var origin = (actinfo.info && actinfo.info.origin)

  console.log("OUR ACTMETA", actmeta);

  if(actmeta.pattern == 'user:here'){
    console.log("actmeta.descdata", actmeta.descdata(args));
  }

  instance.log.debug(
    'act',
    minlen(actmeta.plugin_fullname || '-'),
    'IN',
    actinfo.actid,
    actmeta.pattern,
    function () {
      return [
        actmeta.descdata ? actmeta.descdata(args) : Jsonic.stringify(args),
        (prior_ctxt.entry
          ? 'ENTRY'
          : 'PRIOR;' + (prior_ctxt.chain.slice(0, prior_ctxt.depth)).join(',')),
        actmeta.id,
        actmeta.client ? 'CLIENT' : (origin ? 'LISTEN' : '-'),
        origin || '-',
        args.gate$ ? 'GATE' : '-',
        args.caller$ || act_callpoint
      ]
    })
}
```

Am I correctly setting up my action? This is the code for my action:

```
  _this.add({
    role: 'something',
    cmd: 'here',
  }, cmdUpsert);

  function cmdUpsert(args, done) {
    // Stuff here
  }
  cmdUpsert.descdata = function(args){
    console.log("OUR DESC DATA", args);
    return args;
  }
```

Again I see this pattern used in [seneca-user](https://github.com/senecajs/seneca-user/blob/master/user.js#L416-L418) but I have not verified that that library behaves as intended. Can you point me in the right direction or confirm that these are actually pointing to the incorrect value?

When I change the method to use the seemingly correct values it works as intended (and my `descdata` function gets picked up).

I am in the process of creating a pull request.

**Comment by brycereynolds** [comment]
Pull request submitted:

https://github.com/senecajs/seneca/pull/361

**Comment by rjrodger** [comment]
This is a valid, but undocumented (as yet) feature. It's purpose is to allow you to define custom data representations in logs. In the seneca-user case, you need to remove password hashes as you don't want those logged.

**Comment by mcdonnelldean** [comment]
Closing until there is movement on #361
