### ISSUE TITLE
subscribe is not a function

### ISSUE THREAD

**Issue by mananjadhav** [senecajs/seneca#363]
Hi,
I am trying to run use seneca-pubsub plugin but it gives me following error:

```
seneca.subscribe({role: 'foo'}, function (msg) {
       ^

TypeError: seneca.subscribe is not a function
    at Object.<anonymous> (C:\Project\Creanara\src\backend\services\authservice\test\example.js:5:8)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3
```

I see the plugin uses decoration and probably thats where it is failing. Earlier I had seneca 0.7 and learnt that decorator support was added after 0.9. Is there anything else that has to be done to get it working? I also tried using decorators for another function in my code but it was in vain.

My seneca version is 1.3 and seneca-pubsub is 0.1.0

Sample code that I am trying to run. 

```
var seneca = require('seneca')()
seneca.use(require('seneca-pubsub'))

seneca.subscribe({role: 'foo'}, function (msg) {
    console.log("F1");
    console.log(msg.data.value);    
})
seneca.subscribe({role: 'foo'}, function (msg) {
    console.log("F2");
    console.log(msg.data.value);    
})
seneca.publish({role: 'foo', data: {value: 10}})
seneca.publish({role: 'foo', data: {value: 20}})
seneca.publish({role: 'foo', data: {value: 30}})
```

**Comment by MananJ** [comment]
Opened it with seneca-pubusb as well. But not sure if its a seneca decorator issue or plugin.

senecajs/seneca-pubsub#5

**Comment by mcdonnelldean** [comment]
Closing here, it's an issue on pubsub side.
