### ISSUE TITLE
Interface to write prior actions (intercepts) before executing any action/pattern.

### ISSUE THREAD

**Issue by mananjadhav** [senecajs/seneca#365]
Is there is anyway that I can have a function wrapped across for all the plugins.

I'll explain the use-case. We maintain a  version in our microservices built with Seneca. Now before processing any action, I want to check if the version is satisfied.

I checked `seneca.on('act-in')` handler in the seneca codebase, but its calls a handle_sub (sub without callback).

I was wondering if we can have an act-in with callback (or any other we can achieve it)

```
seneca.on('act-in', function(msg,respond) {
     if(mycondtion) {
        continue processing
      } else { 
         respond(new Error("Invalid Condition")
      }
})

```

I also checked wrap function, but how can I use to work for multiple plugins. I have like 6-7 plugins and no similarities in their actions.

**Comment by mcdonnelldean** [comment]
@mananjadhav there is no easy way to do this unless your patterns allow it, for instance if you follow the `role:foo` pattern you could uses a prior on `role:*` and create a little plugin that is always loaded last. Load order is important. Priors are based on matches so it should work correctly but I've never tried it using that wide a case.

```js
seneca.add('role:*', function (msg, done) {
  // will call the action that would have handled it if there was no override.
  this.prior(msg, function(err, out) {
  }
})
