### ISSUE TITLE
Event emitter leak from Seneca

### ISSUE THREAD

**Issue by devotox** [senecajs/seneca#366]
```
api_1             | [ Nodemon ][ Error ] (node) warning: possible EventEmitter memory leak detected. 11 clear listeners added. Use emitter.setMaxListeners() to increase limit.
api_1             |
api_1             | [ Nodemon ][ Error ] Trace
api_1             |     at GateExecutor.addListener (events.js:252:17)
api_1             |     at GateExecutor.once (events.js:278:8)
api_1             |     at Seneca.api_ready [as ready] (/var/app/current/api/node_modules/seneca/seneca.js:923:30)
api_1             |     at meta.export (/var/app/current/api/node_modules/seneca-web/web.js:661:14)
api_1             |     at Layer.handle [as handle_request] (/var/app/current/api/node_modules/express/lib/router/layer.js:95:5)
api_1             |     at trim_prefix (/var/app/current/api/node_modules/express/lib/router/index.js:312:13)
api_1             |     at /var/app/current/api/node_modules/express/lib/router/index.js:280:7
api_1             |     at Function.process_params (/var/app/current/api/node_modules/express/lib/router/index.js:330:12)
api_1             |     at next (/var/app/current/api/node_modules/express/lib/router/index.js:271:10)
api_1             |     at Object.exports.log_api_request (/var/app/current/api/common/utils/api_response_handler.js:510:27)
api_1             |     at /var/app/current/api/app.js:105:23
api_1             |     at Layer.handle [as handle_request] (/var/app/current/api/node_modules/express/lib/router/layer.js:95:5)
api_1             |     at trim_prefix (/var/app/current/api/node_modules/express/lib/router/index.js:312:13)
api_1             |     at /var/app/current/api/node_modules/express/lib/router/index.js:280:7
api_1             |     at Function.process_params (/var/app/current/api/node_modules/express/lib/router/index.js:330:12)
api_1             |     at next (/var/app/current/api/node_modules/express/lib/router/index.js:271:10)
api_1             |
```

**Comment by devotox** [comment]
Definitely from seneca - confirmed

**Comment by jeltok** [comment]
We are experiencing the same problem.

> 2016-03-30 12:33:54 +00:00: (node) warning: possible EventEmitter memory leak detected. 11 clear listeners added. Use emitter.setMaxListeners() to increase limit.
2016-03-30 12:33:54 +00:00: Trace
    at GateExecutor.addListener (events.js:239:17)
    at GateExecutor.once (events.js:265:8)
    at Seneca.api_ready [as ready] (/home/ubuntu/hardwell/hardwell-inbound-api/node_modules/chairo/node_modules/seneca/seneca.js:923:30)
    at Seneca.api_close [as close] (/home/ubuntu/hardwell/hardwell-inbound-api/node_modules/chairo/node_modules/seneca/seneca.js:875:12)
    at Seneca.die (/home/ubuntu/hardwell/hardwell-inbound-api/node_modules/chairo/node_modules/seneca/lib/common.js:350:18)
    at act_done (/home/ubuntu/hardwell/hardwell-inbound-api/node_modules/chairo/node_modules/seneca/seneca.js:1185:29)
    at /home/ubuntu/hardwell/hardwell-inbound-api/node_modules/chairo/node_modules/seneca/node_modules/gate-executor/gate-executor.js:155:20
    at /home/ubuntu/hardwell/hardwell-inbound-api/lib/services/config.js:31:17
    at Query.<anonymous> (/home/ubuntu/hardwell/hardwell-inbound-api/node_modules/mongoose/lib/query.js:2149:28)
    at /home/ubuntu/hardwell/hardwell-inbound-api/node_modules/mongoose/node_modules/kareem/index.js:177:19
    at /home/ubuntu/hardwell/hardwell-inbound-api/node_modules/mongoose/node_modules/kareem/index.js:109:16
    at nextTickCallbackWith0Args (node.js:415:9)
    at process._tickDomainCallback (node.js:385:13)
2016-03-30 12:33:55 +00:00:

**Comment by mcdonnelldean** [comment]
Hey @devotox Can you show the code you are running? I've looked over the tests and I'm not getting leaks.

**Comment by devotox** [comment]
It spans multiple files but the GateExecutor.addListener does not seem to remove the listener in a timely fashion.

**Comment by mcdonnelldean** [comment]
@devotox Thanks a mill for the feedback. I'm down in the bowls of it for the next two weeks so I've marked this as being investigated. Let me see what I find.

**Comment by mcdonnelldean** [comment]
cc/ @mcollina

**Comment by mcdonnelldean** [comment]
@devotox We may have resolved this. Once 3.0 drops we will know for sure

**Comment by Mohamed-Habshey** [comment]
Hi @mcdonnelldean  i'm still having this issue with seneca@3.2.2 
any updates?
Thanks

**Comment by rjrodger** [comment]
@Mohamed-Habshey do you have code that can reproduce this? Thanks :)

**Comment by Mohamed-Habshey** [comment]
Hi @rjrodger  

well i think this issue is no longer happening to us with seneca@3.3.0 after switching from redis to rabbitmq as our transport, so it could be a transport problem not in Core seneca itself.

Regards. :)

**Comment by rjrodger** [comment]
@Mohamed-Habshey good to hear! Thank you :)

**Comment by devotox** [comment]
@Mohamed-Habshey I do believe that after upgrading to 3.x this has been fixed especially since the cache is no longer automatically enabled
