### ISSUE TITLE
Seneca JS HTTPS

### ISSUE THREAD

**Issue by cesarecontini** [senecajs/seneca#367]
Hello, 
does Seneca.js support SSL / HTTPS?

If so do you have any suggestion on how to configure it?

Regards,
Cesare

**Comment by geek** [comment]
@cesarecontini not at the moment, but there isn't a lot of work required to support them.  See https://github.com/senecajs/seneca-transport/blob/master/lib/http.js#L22 which is where the change will need to be made.  We are open to a pull request to add this functionality.

**Comment by cesarecontini** [comment]
Hello @geek I've made some amends to the file as suggested and other files. Please see the pull request outcome @ https://github.com/senecajs/seneca-transport/pull/85 

Regards,
Cesare

**Comment by mcdonnelldean** [comment]
Closed as complete. Awating merge and release
