### ISSUE TITLE
How to run different seneca microservices on different host with seneca-mesh?

### ISSUE THREAD

**Issue by manoj150283** [senecajs/seneca#368]
Someone please advice me as how to run difference microservices on different hosts with service discovery using seneca-mesh.

I understand base mesh runs on port 39999 but when i am deploying base on different host and deploying one micoroservice on different host, somehow it is not able to communicate.

I tried putting host in to the mesh configuration for base and bases into the mesh configuration for microservice.

Regards,
- Manoj

**Comment by mcdonnelldean** [comment]
Hey @manoj150283 Your best to ask plugin specific questions on the plugin repo, if you follow this link it will take you to a new issue on the correct issue.

- https://github.com/rjrodger/seneca-mesh/issues/new

Cheers!
