### ISSUE TITLE
Add act chaining in seneca

### ISSUE THREAD

**Issue by immanuel192** [senecajs/seneca#369]
Hi 

I would like to add something like act chaining in seneca. I dont know whether it is already supported or not. Please kindly advice. 

Let's say that we have 3 actions A,B,C which describe as below
{ cmd: "A" } => A
{ cmd: "B" } => B
{ cmd: "C" } => C

Normally we will invoke B in seneca by calling seneca.act({ cmd: "B" }, function (err, result) { } )

So if A wants to invoke B, then use the result from B to continue invoke C, we need to put that logic into A with something like below

seneca.act({ cmd: "B" }, function (err, result) { 
         // assume not erro 
         seneca.act({ cmd: "C", data: result }, function (err, result) {
             // do something here 
         });
} );

Now what if we add a property called nextChain in the pattern. 
In A, calling B with nextChain support will be like below:

seneca.act({ 
     cmd: "B" ,
     nextChain : {
           cmd: "C" 
     }
}, function (err, result) { 
    /// the result we have here is from C after processed by B
} );

B can modify the nextChain (enqueue chain) so that after C executed then it will invoke D for example.

I think we can modify the code in file seneca.js, in function api_act
```javascript
// Perform an action. The properties of the first argument are matched against
  // known patterns, and the most specific one wins.
  function api_act () {
    var self = this
    var spec = Common.parsePattern(self, arrayify(arguments), 'done:f?')
    var args = spec.pattern
    var actdone = spec.done
     **if (hasProperty(arguments,"nextChain")){\
          // Replace with our done wrapper
      }
     **
    args = _.extend(args, self.fixedargs)
////.....
}
```

**Comment by mcdonnelldean** [comment]
We do have chaining, I need to investigate if it works post 2.0. Once I have more I will report back.

**Comment by mcdonnelldean** [comment]
@immanuel192 So the chaining we have will run all at the same time, it doesn't do the above. This could be a nice decoration (use seneca.decorate). It won't make it into the core api since we are trying to reduce it's current size in favour of a more modular based system.
