### ISSUE TITLE
http url prefix

### ISSUE THREAD

**Issue by m3l7** [senecajs/seneca#371]
hello,

I'm trying to set up a http proxy/balancer for my seneca configuration.
Let's say ms1 wants to call ms2: ideally an url like    http://proxy/ms2/act    would be perfect, so that the proxy can redirect the request to the proper host:port

The alternative would be to have n proxy installed on n different ports, each for a single ms cluster.

Is there a way to add a prefix to client calls?

P.S. I don't want to use the client balancer or mesh plugin (both have big disadvantages)

**Comment by geek** [comment]
@m3l7 you may try [consul](https://www.consul.io/docs/agent/dns.html) which does support some balancing.  You can also use nginx and consul-template as a way to have a proxy that updates with changes to services.

**Comment by m3l7** [comment]
ok, in my original idea I was thinking about having a nginx instance running on a single port, but configuring nginx to run in multiple ports is very simple and it can be done in a single config file.

I think this can be closed
