### ISSUE TITLE
seneca.export() doesn't initialize the transport/utils correctly

### ISSUE THREAD

**Issue by drahnieR** [senecajs/seneca#373]
Not sure whether this issue should belong to [seneca](https://github.com/senecajs/seneca) or [seneca-transport](https://github.com/senecajs/seneca-transport). If it's the later case, feel free to close it and i'll file it in seneca-transport.

So I have a transport plugin implemented as below

> module.exports = function(opts) {
>     var seneca = this
>     var tu = seneca.export('transport/utils')
>     ...
> }

While in my application, if i init seneca with options, say `transport.msgprefix`, which is mentioned in the document of seneca-transport.

> var seneca = require('seneca')({
>     transport: {msgprefix: 'myprefix'}
> })
> .use('my-transport')
> .listen()

The option won't be carried into the exported module. (`_msgprefix `is 'seneca_' and all topic related functions won't use the prefix I provided.

Any ideas?

**Comment by mcdonnelldean** [comment]
Hey @drahnieR I think this is related to Transport, I'm going to move it there, see, https://github.com/senecajs/seneca-transport/issues/96

**Comment by drahnieR** [comment]
@mcdonnelldean appreciated
