### ISSUE TITLE
NPM tags

### ISSUE THREAD

**Issue by mcollina** [senecajs/seneca#374]
I think we can do better on the tags on NPM, all those "startup", "mvp", etc things are not relevant anymore. Currently we have:

```
startup, toolkit, product, viable, minimum, framework, micro service, micro services, services, micro-services, microservices, micro-service, microservice, service, micro
```

**Comment by geek** [comment]
Happy to merge in a narrower set of tags.  

Maybe: `microservice`, `toolkit`, `micro-service`, `service`

**Comment by mcdonnelldean** [comment]
@mcollina We can roll this up with the new pre versioning stuff.
