### ISSUE TITLE
debugging with intellij

### ISSUE THREAD

**Issue by rparies** [senecajs/seneca#381]
I realize that this is about intellij , but the issue  is exclusively intellij and seneca. All my node apps debug fine with lots and lots of other packages.

If i run or debug an app using senecajs with intellij the app will run ok.
if i put in a break point anywhere the app hangs. Yes i realize this sounds like an IDE issue. which it probably is.

i am just wondering if anyone using seneca has successfully debugged using intellij or webstorm

also is there a better forum for this topic. there does not seem to be any seneca activity on stackoverflow

**Comment by mcdonnelldean** [comment]
Generally most of the devs working on seneca are using lightweight text editors so it's probably never came up. My first assumption is this has to do with the gate executor but I'm not certain.

What place have you been putting break points. I *think* @ckiss uses webstorm.

**Comment by rparies** [comment]
@mcdonnelldean , thanks for responding
i have tried in a couple of different places. 

here is a very simple sample that i am using. if i put a breakpoint anywhere in here, when i start the debugger it hangs. when i kill the debugger, it then appears to ( in this example ) call the databaseService. if i remove the breakpoints and start the app , thing work as designed

thanks
randy

```
var seneca = require('seneca');

var senecaConfig = {
  errhandler: senecaErrorHandler,
  timeout:99999
};

var paymentService = seneca(senecaConfig)
  .use( 'payment' )
  .use('seneca-rabbitmq-transport-v2')
  .listen( {type:'rabbitmq',url:'amqp://localhost',pin:'role:PaymentService'} )
  .client( {type:'rabbitmq',url:'amqp://localhost',pin:'role:DatabaseService,cmd:createTransaction'} )
  .client( {type:'rabbitmq',url:'amqp://localhost',pin:'role:DatabaseService,cmd:getTransactionById'} )
  .client( {type:'rabbitmq',url:'amqp://localhost',pin:'role:DatabaseService,cmd:getGatewayCfg'} )
  .client( {type:'rabbitmq',url:'amqp://localhost',pin:'role:DatabaseService,cmd:getNextSequenceNumber'} );

  paymentService.act({role:'DatabaseService',cmd:'getGatewayCfg',service:'GatewayServices',id:39},console.log);

function senecaErrorHandler( err ) {
  return false;
}

```

**Comment by ckiss** [comment]
hi @rparies @mcdonnelldean, yeah I am using webstorm and I've been using the debugger in a couple of occasions and I had no issues.

@rparies not sure what you mean by app hangs when you put a breakpoint? isn't supposed to stop at the breakpoint?

**Comment by rparies** [comment]
yeah its really weird. for example in the code above. if i put a breakpoint paymentService.act and start the debugger, the debugger never gets to or breaks at the paymentService.act,
so i though i would press the pause to see where i was at in the code and that did nothing. (sure sounds like IDE correct?)
At this point if i  kill the debugger then it seems to execute the paymentService.act. 
if i start the debugger without any breakpoints, it executes the  paymentService.act immediately .

i have tried intellij 15 and 16. @ckiss are you using webstorm? i thought webstorm was a subset of intellij. Maybe i should try webstorm

thanks guys for your help

**Comment by ckiss** [comment]
@rparies I haven't used intellij but if behaves the same in webstorm I assume it's from some configuration in WS. WS have some really good documentation about how to run & debug your Node.js app. Can you check this? https://www.jetbrains.com/help/webstorm/2016.1/running-and-debugging-node-js.html?origin=old_help

**Comment by ckiss** [comment]
@rparies also you need to `.act` on `seneca.ready`. Check this [seneca ready](http://senecajs.org/api/#ready-callback-)

**Comment by rparies** [comment]
thanks @ckiss. As far as the debug doc,  the problem is exclusive to seneca. All my other node apps run and debug just fine in the IDE

**Comment by geek** [comment]
@rparies have you tried [node-inspector](https://www.npmjs.com/package/node-inspector) directly?  I have success with using it when a console.log won't cut it.

**Comment by mcdonnelldean** [comment]
@rparies I have a feeling this has to do with the gate executor and error handling in seneca. These are coming out in the next couple of versions. For now there isn't anything I can see to resolve it. As soon as those two features come out I'll update this thread.
