### ISSUE TITLE
API request id param being overriden

### ISSUE THREAD

**Issue by naomifeehanmoran** [senecajs/seneca#384]
when running the shop example code from the getting-started repo, the id param passed to the request is being overridden by what looks like a system id.

### Steps to reproduce:

1. update getting-started package.json as follows:

`"dependencies": {
    "body-parser": "^1.13.2",
    "express": "^4.13.1",
    "seneca": "2.0.0"
  },
  "devDependencies": {
    "seneca-entity": "0.0.1"
  }`

2. update app-all.js to use the external entity:

`var seneca = require( 'seneca' )()
      .use('entity')
      .use( 'api-all' )`

3. update shop-service.js to use entity:

`require( 'seneca' )()
  .use('entity')
  .use( 'shop' )`

4. run the following:
$ node math-pin-service.js --seneca.log.all
$ node shop-stats.js --seneca.log.all
$ node shop-service.js --seneca.log.all
$ node app-all.js --seneca.log.all

5. app-all.js will produce the following output:
`null $-/-/product:{id=xxx;name=Apple;price=1.99}`

6. hit this endpoint replacing 'xxx' with your local value
http://localhost:3000/api/shop/get?id=xxx

7. check the output in app-all.js and you can see that the id is not that passed in the url param
eg.
`... DEBUG   act api         IN  hy78wmrvdrg6/jneet1bfdb5a   path:shop,role:api  {path:shop,role:api,operation:get,id:msihhhx7ub6g/1459344039496/14255/-,did:(3vbzzeyc755g),fixedargs:{},context ENTRY   (vf7li64pnmvr)  -   -   -

... DEBUG   act client$         IN  69va8fkq0p6m/jneet1bfdb5a   role:shop   {role:shop,id:msihhhx7ub6g/1459344039496/14255/-,get:product}   ENTRY   (kuzq2zd9unxa)  CLIENT  -   -
... DEBUG   act client$         OUT 69va8fkq0p6m/jneet1bfdb5a   role:shop   null    EXIT    (kuzq2zd9unxa)  CLIENT  nabulojm4mjn/1459343944073/14151/-  9   -

... DEBUG   act api         OUT hy78wmrvdrg6/jneet1bfdb5a   path:shop,role:api  null    EXIT    (vf7li64pnmvr)  -   nabulojm4mjn/1459343944073/14151/-  12  -
`

I have observed this issue back to Seneca 1.1.0.

This looks to be similar to this previously closed issue https://github.com/senecajs/seneca/issues/348

**Comment by naomifeehanmoran** [comment]
Hey @geek any update on this? :)

**Comment by geek** [comment]
@naomifeehanmoran unfortunately not yet.  I removed myself from the assignment as I will likely not get to it this week.

**Comment by mcdonnelldean** [comment]
@naomifeehanmoran Just a heads up on this. I got it with entities too. The problem is entities is setting the id to be the id of entity when it loads.

**Comment by AdrianRossouw** [comment]
this looks like ti might be occurring somewhere in here : https://github.com/senecajs/seneca-mem-store/blob/master/mem-store.js#L72

**Comment by indr** [comment]
I tried to use the rjrodger/seneca-jsonrest-api plugin and encountered this problem. The pull request senecajs/seneca-web#70 might fix this issue.
