### ISSUE TITLE
seneca.make gone?

### ISSUE THREAD

**Issue by dpjanes** [senecajs/seneca#388]
with version 2.0.0, this code from the Getting Started page

    $ npm install seneca
    $ node
    var seneca = require('seneca')()
    var product = seneca.make('product')

says seneca.make is undefined. This works with version 1.2.0

**Comment by mcdonnelldean** [comment]
Hey @dpjanes yeah we are in the middle of updating the docs. You just need to install and include a new plugin so

`npm install seneca-entity` and then `seneca.use('entity')`

**Comment by bnusunny** [comment]
Please do update the document. This could save people's time and avoid the frustration for the new comers.
