### ISSUE TITLE
In what way should we implement publish-subscribe pattern?

### ISSUE THREAD

**Issue by pioneer32** [senecajs/seneca#389]
I'm looking for a way to move our project from self-written bicycles to Seneca. At the present time, we use Nginx as a load-balancer for request-response-style services and RabbitMQ as message-bus for publish-subscribe messaging. I viewed a lot of materials regarding Seneca and its ideas, and I'm totally confused since I tried to find how to implement the following patterns that we use:
1. One publisher and several subscribers (one-to-one pattern), we use one queue with RabbitMQ round-robin balancing (i.e. queue for processing files).
2. One-to-many. One service publishes a message to exchange and RabbitMQ puts it into several queues, i.e. when we get new changes from op-log (event-sourcing), we publish it into AMQP broker and several subscribers get and process it.

I've looked at seneca-amqp-transport and so on, but I have found nothing useful because when I invoke act() I have to wait for calling done() on server-side (instead when message is put into exchange).
On the application layer, I don't need to care about either the message is handled on the other end of the pipe or not. I just want to be sure that message is successfully placed into the pipe.

Would it be possible to implement these patterns with Seneca?
Any help will be highly appreciated )

**Comment by timoweiss** [comment]
Did you have a look at https://github.com/rjrodger/seneca-mesh
When registering the plugin, you could define the `model` property inside `listen` according your needs:
```javascript
// borrowed from https://github.com/nodezoo/nodezoo-info/blob/master/srv/start.js
seneca.use('mesh', {
    auto: true,
    listen: [
      {pin: 'role:search,cmd:upsert', model: 'consume'},
      {pin: 'role:search,cmd:search', model: 'consume'},
      {pin: 'role:info,info:updated', model: 'observe'}
    ]
  })
```
`consume`: request-response
`observe`: subscribing (without supplying a result) 

Disclaimer: I just set up some tests to play around with this. I haven't used it in prod so far. But maybe @mcdonnelldean could have a look at this.

**Comment by mcdonnelldean** [comment]
@pioneer32 Yeah so we use mesh and two sets of patterns when we want something like above. I'm currently writing some stuff with Redis queues to see how that works out. I'll ping you a link when done. You can also write custom transports if needs be, that would allow you to link to seneca how you like.

**Comment by mcdonnelldean** [comment]
Closing for now @pioneer32 If you need any more help feel free to reopen.
