### ISSUE TITLE
Versioning and Blue-Green Deploys with AMQP

### ISSUE THREAD

**Issue by iantanwx** [senecajs/seneca#390]
Hi everyone, 

Great work with Seneca. I am building a new project with Seneca at its core, which also happens to be my first SOA app. 

My question pertains to using a message bus instead of http calls for inter service communication. Presently I have a front end api stubbed out, using a set of client Seneca plugins to provide an interface to each microservice. They're just a set of acts that get thrown into a co routine with a circuit breaker implementation to orchestrate calls to the web facing API. 

With nginx, blue greens are fairly simple - just load balance each set of instances behind an nginx node and control which set gets called with nginx config. Unfortunately matters get more complicated when using rabbitmq, since if both sets of instances are simultaneously deployed they may return different data models. 

A simple solution I thought of would be to include service api versions in the binding key (i.e. Act pattern), so, for example 'user:profile:0.0.1', so that I can easily do a blue green by switching out sets of web api instances that sit behind nginx, modifying their client pkugins to use the right version. This does couple the web api to its micro services it depends on more than I can say im comfortable with however. 

Any ideas would be greatly appreciated. Help a micro services noob out!! Thanks!

**Comment by geek** [comment]
@iantanwx there is definitely not a correct answer for all occasions when it comes to this question.  One solution, though, would be to have a separate message bus instance for each of the environments you want to be able to switch between.

**Comment by iantanwx** [comment]
@geek thanks for the help!

Correct me if I am wrong -- using the proposed method, I would have to:

1. Set up a new RabbitMQ cluster in the prod VPC
2. Set all producers and consumers to connect to the new cluster using env vars or such
3. Restart all producers and consumers to connect to the new cluster when I want to switch to a new version of a microservice

Would this not introduce down time since in this case, all the NodeJS containers are listening to the old cluster? I would have to restart them, since they bootstrapped with the old cluster's network address. 

The only way I can think of to get around this is to reproduce the entire set of services in another VPC and then just switch the load balancer(s) to point to the web APIs sitting in this new VPC.

This would appear to be a little bit time-consuming and maybe impossible if we have hundreds of containers running in many ECS instances.

If I'm wrong, please let me know, and thanks again for your help!

**Comment by geek** [comment]
@iantanwx its one idea, definitely not the correct answer for all occasions... but it would allow for two separate environments to switch between.

That being said, your original idea of adding a version to the messages should also work and prevent you from needing separate rabbit instances.

**Comment by iantanwx** [comment]
@geek Thanks! I am now starting to favour direct good old HTTP with something like Swarm and Consul over a message bus. It just seems that a message bus would add too much operational and code complexity to a project that's already complex as it stands.

**Comment by iantanwx** [comment]
@geek looks like it's time for me to fire up my Pi cluster and test both methods out.

**Comment by geek** [comment]
@iantanwx agreed, take a look at http://containerbuddy.io/ if you are using consul.

**Comment by iantanwx** [comment]
@geek is there a difference between containerbuddy and registrator?

**Comment by mcdonnelldean** [comment]
I'd say this is best moved to https://gitter.im/senecajs/seneca :D
