### ISSUE TITLE
Loghandler undefined

### ISSUE THREAD

**Issue by tfoutrein** [senecajs/seneca#392]
Hello 
When i try the exemple on the Loggin with seneca page / Log handlers i've always the same result : 

**TypeError: Cannot read property 'file' of undefined 
**

so i can't manage the log configuration of my microservice
i've the last version of seneca , here is my package.json file
[package.zip](https://github.com/senecajs/seneca/files/206578/package.zip)

thank you very much in advance

**Comment by tfoutrein** [comment]
Can you help me please ?

**Comment by geek** [comment]
@tfoutrein can you link to a gist with your code and the output you are getting.

**Comment by mcdonnelldean** [comment]
@tfoutrein On the pages there is a little funny icon that lets you select the sub heading of the section you are reading. Can you post that link here? That way we can see which part of the tutorial you are having issues with.

As @geek if you put your code in a gist it would really help.

**Comment by tfoutrein** [comment]
Hello, my problem concern this part of the tutorial http://senecajs.org/tutorials/logging-with-seneca.html#log-handlers 

and here is the gist https://gist.github.com/tfoutrein/710f179be7f0e8eb00525b8b22d9218a

thank you in advance for your help

**Comment by mcdonnelldean** [comment]
@tfoutrein Super, it will be a little while before we get back to this but I'll check the example and see if there are issues

**Comment by tfoutrein** [comment]
but it's very annoying for me , i can't manage the log system without this or just with the command line system and that's not very practical

**Comment by mcdonnelldean** [comment]
@tfoutrein So basically the problem here is the docs are out of date. If you head to our [Gitter][] Channel folks are in discussion as how best to proceed.

[Gitter]: https://gitter.im/senecajs/seneca

**Comment by mcdonnelldean** [comment]
Merged with #413

**Comment by cm45t3r** [comment]
It would be much appreciated if official docs are updated.
