### ISSUE TITLE
left join query using mysql-store

### ISSUE THREAD

**Issue by AmitVirpara** [senecajs/seneca#393]
how to create left join query using mysql-store

**Comment by mihaidma** [comment]
@AmitVirpara seneca stores doesn't support at this moment left join with mongo style syntax but you can make direct queries like in the following sample:
https://github.com/senecajs/seneca-store-test/blob/master/store-test.js#L1087

**Comment by mihaidma** [comment]
@AmitVirpara I will close this issue, please reopen if there are more issues

**Comment by AmitVirpara** [comment]
thanks
