### ISSUE TITLE
using seneca tcp client with non-seneca tcp server

### ISSUE THREAD

**Issue by ro70** [senecajs/seneca#394]
Is this possible at all? If yes, how do I have to do it? What server response is the seneca client expecting exactly? I could post some code sample of my trials if that would help...

**Comment by ro70** [comment]
Seems that I found a solution. For whomever is interested in:

The tcp-server receives a json like the following from the seneca-tcp-client:
```
{
  "id":"...",
  "kind":"act",
  "origin":"...",
  "track":["..."],
  "time":{
    "client_sent":...
  },
  "act":{
    "role":"...",
    "cmd":"...",
    ...
  }
}
```

The tcp-server has to respond to the seneca-tcp-client with a json like:
```
{
  "id":"...",
  "kind":"res",  <-- change from "act" to "res"
  "origin":"...",
  "track":["..."],
  "time":{
    "client_sent":...
  },
  "act":{
    "role":"...",
    "cmd":"...",
    ...
  },
  "res":{
                <-- put your response in here!
  }
}
```
Don't forget to send an "\n" to mark the end of your message.

**Comment by geek** [comment]
@ro70 awesome!  I am not sure where it fits, but happy to add documentation for this.

**Comment by mcdonnelldean** [comment]
Closed and moved to document request Cheers @ro70
