### ISSUE TITLE
seneca.use internal timeouts and high cpu and memory usage

### ISSUE THREAD

**Issue by pibi** [senecajs/seneca#400]
Hello
I'm opening this issue after a discussion on gitter. 
My problem: I'm working on a API server with many APIs grouped by roles. These API are exposed from an API-gateway and every role matches a microservice. 
A single API is quite simple: an HAPI route that acts the related role and command, packed in a seneca plugin.
APIs plugins are located in a folder, on startup a loader plugin reads all the modules and loads every single plugin right from this folder.
Same pattern is used on the microservices to load actions.

We are experiencing random timeout errors on startup whenever the API-gateway tries to load more than 2 plugins. With 3/4 plugins sometimes seneca still fires the ready callback and everything work as expected With 5 or more plugins it simply doesn't work. 

Loader seems to work smoothly on the microservice side, no matter how many action files we are using.

Here the complete error message and program usage:
https://gist.github.com/pibi/c53dfdb1d5196cd9d2fde6d69a9b2669
Here a barebone repo I built to reproduce the issue:
https://github.com/pibi/senecatest

To reproduce the error, simply start the API-gateway:

```
npm install

node api-gateway/api-gateway.js
```

The repo uses 3 plugins, if it works, please retry by cloning the api-gateway/api/dw.js file, rename it and change the SRV_NAME variable.

thanks to @mcdonnelldean and @jreeter I already tried some workaround, with no success:
- using require on seneca.use(): from `seneca.use("filename.js")` to `seneca.use(require("filename.js"))`
- disabling beanstalkd transport

Thank you very much for your support

**Comment by mcdonnelldean** [comment]
@pibi Can you remove the call to ready to test if it's a determinate issue? So basically pretend it doesn't exist. I'm working on a hunch that ready and loading might be the issue.

**Comment by pibi** [comment]
I'm not sure you are referring to #387, but we got the problem also with seneca 0.6.5.
btw, I will do the check, thanks!

**Comment by pibi** [comment]
@mcdonnelldean Just tried. Removing the seneca.ready() doesn't solve the issue.

**Comment by rjrodger** [comment]
@pibi I forked your test repo and ran the api gateway:

```
$ node api-gateway/api-gateway.js
2016-05-08T19:59:51.485Z 9r7tj1z4j82i/1462737591466/41715/- INFO	hello	Seneca/2.0.1/9r7tj1z4j82i/1462737591466/41715/-	
2016-05-08T19:59:51.761Z 9r7tj1z4j82i/1462737591466/41715/- INFO	client	{type:beanstalk,pin:role:*,cmd:*,host:0.0.0.0}	
[ API-GW ] loading  dw
[ API-GW ] loading  pets
[ API-GW ] loading  user
2016-05-08T19:59:59.935Z 9r7tj1z4j82i/1462737591466/41715/- INFO	ready to start
Server running at: http://0.0.0.0:3000
```

This does seem to work - I think?

I would not recommend using readdirSync in this manner - you are subject to random read times, and especially on cloud virtual machines this could easily cause timeouts.

What is the purpose of loading the plugins in this manner?

For a good example of a hapi API based microservice architecture see https://github.com/senecajs/ramanujan

**Comment by mcdonnelldean** [comment]
My bad we moved to gitter on this and basically came to the same conclusion. @pibi I'll close with the provisio that we generally don't recommend using that method since it causes all sorts of weird load issues. Feel free to open if you have more questions or we can continue on gitter too 👍

**Comment by pibi** [comment]
Sorry guys, but we didn't come with this conclusion on gitter. we tried
with express and chairo, the only conclusion was about the inconsistent
fatal$ usage.

Readdirsync is not a problem here, it happens way before the seneca
timeouts.

please, test the "with_init" branch and please try to add some more file to
the api gateway. you should experience a consistent high load time on init
calls and timeout whenever you try to load 5 files.

Il 08 mag 2016 10:16 PM, "Dean McDonnell" <notifications@github.com> ha
scritto:

**Comment by pibi** [comment]
@rjrodger please, take a look at the timestamps:
2016-05-08T19:59:51.761Z 9r7tj1z4j82i/1462737591466/41715/- INFO client {type:beanstalk,pin:role:*,cmd:*,host:0.0.0.0} 
 [ API-GW ] loading dw 
[ API-GW ] loading pets 
[ API-GW ] loading user 
2016-05-08T19:59:59.935Z 9r7tj1z4j82i/

8 seconds to load 3 files after the readdirsync. they are internal timeouts, as you can see by adding some other file on the api folder.

**Comment by mcdonnelldean** [comment]
@pibi Apologies, I had went through the backlog and assumed ye had worked through it. I've reopened but I think we need to distill this problem down into a runnable test so we can reproduce this issue in our suite.

**Comment by mcdonnelldean** [comment]
@pibi Actually a quick verification. If you don't use readdirsync are you still getting the same result? I'd like to limit the moving parts to figure out where to start looking on this.

**Comment by rjrodger** [comment]
@pibi it would still be helpful to understand why you are loading plugins this way
To fully exclude this as an issue, I would modify your test case to load the plugins directly using seneca.use, and see how that affects things

**Comment by pibi** [comment]
@rjrodger is a "convention over code" pattern for a development of many
(>20) microservices in a high distribute team. Readdirsync helps us to keep
the structure simple and consistent (we use it also to load actions, with
no issues)

Please, try to mofify the "with_init” branch, it has better logging, it's
more simple to understand (api file are just placeholder you can clone to
see the load times), it should exclude some paths on seneca internals
(because of the explicit init)

btw, actually we have removed the seneca.use() and we are using hapi
plugins to do the same: it works as expected.

thanks a lot for the support
Il 09 mag 2016 12:26 AM, "Richard Rodger" <notifications@github.com> ha
scritto:
