### ISSUE TITLE
Node v6 support

### ISSUE THREAD

**Issue by mcollina** [senecajs/seneca#409]
@mcollina I (@mcdonnelldean) modified the body of this message to provide an update on this for merging reasons.

It looks to be Node v6 breaks Seneca, see PR #419

The reason seems to be based on changes to, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect

But this needs to be investigated.

**Comment by mcdonnelldean** [comment]
We have a release in November (Major) this dovetails nicely with that

**Comment by mcdonnelldean** [comment]
I wrote the wrong comment :D Yeah @mihaidma It may be an idea once we finish with the test stuff to start adding node@6 to our suite so we can figure out what breaks and doesn't at an org level.

**Comment by mcdonnelldean** [comment]
@mihaidma I want to talk about this today to see what effort there is to add 6 into our suite

**Comment by mihaidma** [comment]
@mcdonnelldean I already evaluated moving to node 6, let's discuss it today

**Comment by mcdonnelldean** [comment]
Awesome stuff!

**Comment by mcdonnelldean** [comment]
I've pushed this out until the August release as we have identified issues when testing V6 across the org. These need to be resolved first.

**Comment by mcdonnelldean** [comment]
This has been added.
