### ISSUE TITLE
Discontinue support for node v0.10

### ISSUE THREAD

**Issue by mcollina** [senecajs/seneca#410]
I propose we discontinue support for node v0.10 on 2016-10-1, following the Node.js Foundation TLS cycle. See https://github.com/nodejs/LTS

**Comment by mcdonnelldean** [comment]
Added to 5.0 Milestone (provisional, may happen sooner)

**Comment by mcdonnelldean** [comment]
Both 0.10 and 0.12 have been dropped for 3.0 via #473 #472
