### ISSUE TITLE
Role of the gate-executor

### ISSUE THREAD

**Issue by mcollina** [senecajs/seneca#411]
In the context of #398 and #402, I'm a bit puzzled by the role of gate-executor.

@rjrodger @geek @mcdonnelldean can you please explain why we are using it?

**Comment by mcdonnelldean** [comment]
I'm still working through it myself....

My understanding is that it allows functions or units of work to be queued in such a way that they are 'gated'.

This gating is what controls order (for instance while seneca is readying I believe it queues up all your calls to client and listen, and act for instance.

The end result is its a manager that allows execution order to be deterministic. 

This is my current understanding. @geek or @rjrodger should have a better understanding of what its for exactly.

I do know if you take it out you will break chaining too.

Kindest Regards,

Dean

**Comment by mcollina** [comment]
Yeah, I'm trying to understand _when_ it is used, and for what purposes. It seems for all acts, but I might be wrong.

It seems it solves problems by executing one thing at a time, which solves ordering, but cripples node. But I might be wrong.

**Comment by mcdonnelldean** [comment]
No I think you are right, it's used for ALL acts and forces consistency this way. @rjrodger has said if we could come up with a lighter more elegant solution it would be preferential but don't underestimate how much of the core it touches (every act as far as I'm aware). I've assigned to @rjrodger as I think it's important to get clarity on what this touches instead of both of us making educated guesses :D

**Comment by rjrodger** [comment]
Actions in general operate in parallel - the gating does not affect this.

What is does do is ensure correct ordering of plugin initialisation and also transport construction, by "gating" actions until the plugins are ready.

**Comment by rjrodger** [comment]
Also, v imp for usability, it makes the chaining API work

**Comment by mcdonnelldean** [comment]
@rjrodger Ah, yeah that makes much more sense alright.

**Comment by mcollina** [comment]
Sorry @rjrodger, I'm still not understanding.

Can you please clarify what is the expected behavior of gating? the gate executor is key piece of the plugin loading mechanism and it has a key role in the error handling. Also, there is a lot of custom error handling for loading plugins as well.

I do not understand why a `setImmediate` is needed: https://github.com/senecajs/gate-executor/blob/master/gate-executor.js#L99. Removing that `setImmediate` break this test: https://github.com/senecajs/gate-executor/blob/master/test/gate-executor.test.js#L315-L377.

**Comment by mcdonnelldean** [comment]
Closing as Matteo has worked through this code.
