### ISSUE TITLE
Move actcache at plugin level

### ISSUE THREAD

**Issue by mcollina** [senecajs/seneca#412]
I think actcache is a thing too risky to have it enabled instance-wide on seneca.

I think we should move it to a plugin (maybe with a decorator):

```js
seneca.use('actcache', { size: 42 })
seneca.addCacheable('a:42', fn)
```

**Comment by mcdonnelldean** [comment]
I would provisionally agree with this. We need to understand if there any gotchas but if we can pull it out as a plugin for back compat and it doesn't go up in flames I support this

**Comment by mcollina** [comment]
First of all, is anybody enabling actcache? It's not even documented (I presume)

**Comment by mcdonnelldean** [comment]
No idea. But I can't change things based on assumption of use. Either way, this falls into the same category as Joi / Logging, once that work is done caching can become an optional addin if that's what the community wants.

I've set this for discussion post the plugins milestone as that makes the most sense for now. We can open it up to the community then to figure out if anyone is using it.

**Comment by mcdonnelldean** [comment]
Possibly related to #401

**Comment by mcdonnelldean** [comment]
Closed as this is now agreed. See, #509
