### ISSUE TITLE
Documentation Blitz

### ISSUE THREAD

**Issue by mcdonnelldean** [senecajs/seneca#413]
We need to blitz documentation before V3 is out. There are some out of date docs and broken samples.

### Concepts to cover
- using ready correctly
- load order
- plugin composition
- cover $fatal usage
- Rework API docs
- Marshaling data when not using plain objects.

Feel free to suggest more.

**Comment by tnolet** [comment]
Probably not the place to say this, but is it possible for fatal$ to be false by default?

**Comment by mcdonnelldean** [comment]
@tnolet This wouldn't be the place for this. For now fatal$ will be true. This will change when error handling changes go in but that is 2ish major versions away.

**Comment by djensen47** [comment]
Where is the PR that solves this issue? I must be really missing something because I can't find the new docs for fatal$.
