### ISSUE TITLE
Change to the asynchronous model of execution

### ISSUE THREAD

**Issue by mcollina** [senecajs/seneca#414]
This stems from #398 and #402, but it is worth its own discussion.

In gate executor, everything `act` is wrapped within a `setImmediate` and a try-catch.
Currently, the role of the try-catch is to allow connecting the _source_ of the act if an exception occurs.
This is needed because the `setImmediate` resets the stack.

Currently an `act()` is asynchronous because an `act()` might go to the network, and its result __must always be asynchronous__.

These two requirements might seem at odd, but there is a solution. Let's consider the current case:

```js
seneca.add('hello:world', function a (msg, done) {
  console.log('this is executed')
  done(null, { something: else })
})
seneca.act({ hello: 'world' }, function b (err, result) {
  console.log('act replied')
})
console.log('after calling act')
```

This currently prints:
1. `after calling act`
2. `this is executed`
3. `act replied`

If act was synchronous:
2. `this is executed`
3. `act replied`
1. `after calling act`

I propose that we wrap the callback in a `nextTick`, to get the following output:
2. `this is executed`
1. `after calling act`
3. `act replied`

This can happen using the https://github.com/npm/dezalgo module, for more context see http://blog.izs.me/post/59142742143/designing-apis-for-asynchrony.

I propose we target 4.0 for this, as it will need to touch the plugin mechanism as well :(.

I think we _might_ swap `setImmediate` with `process.nextTick` (or https://github.com/calvinmetcalf/process-nextick-args) asap (in 3.0), because `setImmediate` is executed after a full I/O cycle, essentially introducing latency for free. However, this might cause bad warning to appear in node v0.10, if we go over the 1000 calls: I don't think this is a problem, as you will likely have a loop if you have 1000 nested acts.

**Comment by mcdonnelldean** [comment]
I'm trying to see if there would be a bigger impact or not to this that I first assume, let me add some sample code to see if these would run as I expect.

```js
'use strict'

var seneca = require('seneca')

function handler (name) {
  return function (msg, done) {
    return done(null, {handler: name})
  }
}

function local (msg, done) {
  this.prior(msg, (err, reply) => {
    return done(null, {handler: reply ? reply.handler : 'none'})
  })
}

function logger (err, reply) {
  console.log(reply)
}

seneca()
  .add('cmd:run', handler('approver'))
  .listen(8260)

seneca()
  .add('cmd:run', handler('rejector'))
  .listen(8270)

seneca()
  .add('cmd:run', local)
  .act('cmd:run', logger)

seneca()
  .client({port: 8270, pin: 'cmd:run'})
  .client({port: 8260, pin: 'cmd:run'})
  .add('cmd:run', local)
  .act('cmd:run', logger)

seneca()
  .client({port: 8260, pin: 'cmd:run'})
  .client({port: 8270, pin: 'cmd:run'})
  .add('cmd:run', local)
  .act('cmd:run', logger)

setTimeout(() => {process.exit()}, 500)

// Output
// { handler: 'none' }
// { handler: 'approver' }
// { handler: 'rejector' }
```

Would this have the same output? Or to put it another way, what does this change do in feature terms.

**Comment by mcollina** [comment]
Yes, it will have the same output. This does not change the communication through transports, but only the in-process (where a more clear error-handling would help).

Feature wise, you should have no difference.
However, this might break some tests that are relying on asynchronous side effects: these kind of tests are usually potential bugs anyway.

**Comment by mcdonnelldean** [comment]
@mcollina As discussed this week, closing due to other work needing to be complete first. Once the initial groundwork is layed we will reframe and replan 👍
