### ISSUE TITLE
Add docs on fatal$

### ISSUE THREAD

**Issue by sabberworm** [senecajs/seneca#416]
I found no mention of the `fatal$` flag on the website. I did get the following error once:

>   ALL ERRORS FATAL: action called with argument fatal$:true (probably a plugin init error, or using a plugin seneca instance, see senecajs.org/fatal.html)

([source](https://github.com/senecajs/seneca/blob/3bf43782235645737060e0ee44cd69a5bf3255ce/lib/common.js#L280))

However, the link [senecajs.org/fatal.html](http://senecajs.org/fatal.html) just 404s. It would be nice if we had a writeup of seneca’s concept of fatal vs. non-fatal action calls. I found it really confusing to understand and still don’t know why the default is for `fatal$` to be `true` in a plugin, which I find very counter-intuitive.

**Comment by mcdonnelldean** [comment]
@sabberworm Good spot, I am actually updating documentation on the site to go live in June so I will add this one to the list, I'll add some code samples too.

**Comment by AdrianRossouw** [comment]
dont forget to document opts.debug.undead: 
https://github.com/senecajs/seneca/blob/2371389120632c26e4f548964f1df976934904b7/lib/common.js#L257
```
var seneca = require('seneca')({
   debug: {
      undead: true
   }
});
```

although hopefully that won't stay necessary forever.

**Comment by mcdonnelldean** [comment]
Merging with #413 @sabberworm this should drop, Monday or Tuesday coming as part of #413. I will ping here when they are ready. I have examples on the API doc showing `$fatal`'s usage

**Comment by djensen47** [comment]
Where can I find the  new API docs that explain `fatal$`'s usage?

I'm guessing Github's search isn't revealing it to me?

**Comment by killerspaz** [comment]
I see a lot of "docs coming soon" replies, and issues quietly closed.

Ever mind following up and keeping to your word?

**Comment by seonixx** [comment]
@mcdonnelldean Can't see any mention of fatal$ in the docs. Did this ever happen? Why close the issue before it is resolved?
