### ISSUE TITLE
Seneca + Joi + nested actions [bug]

### ISSUE THREAD

**Issue by ilyaigpetrov** [senecajs/seneca#417]
Hi. I have issue with nested object validation via Joi. Could you tell me whether this is a bug:
```javascript
'use strict';

const seneca = require('seneca')({ log: 'test' });
const Assert = require('assert');
const Joi = require('joi');

seneca.add({ cmd:'test', foo: { bar: 'nested!' } },
  function (args, cb) {

    console.log('Must never be executed!'); // This message is printed, but mustn't.
    Assert( args.payload, 'No payload' ); // This is thrown, but mustn't.
    return cb(null, { test: 'fix this test' });
  },
  { parambulator: Joi.object().keys({ payload: Joi.object().required() }).required() }
);

seneca.act({ cmd:'test', foo: { bar: 'nested!' } }, function (err) {

  Assert(err, 'No error'); // Must be validation error.
  console.log('Test passed.');
});
```

**Comment by mcdonnelldean** [comment]
Related to #164

**Comment by mcdonnelldean** [comment]
@ilyaigpetrov I think the params may be the wrong way around here.

When I test it using the correct param order I get a perambulator error. I haven't used this functionality before but we have a couple of people with open issues around it. I have it on my list of things to investigate later this week.

I do know that for 3.0 we adding more explicit support for swappable validation, see,

https://github.com/rjrodger/seneca-joi
https://github.com/rjrodger/seneca-parambulator

**Comment by mcdonnelldean** [comment]
@ilyaigpetrov We've corrected an issue with the validation service. Joi will be a first class plugin from 3.x onwards but you can enable it in 2.1 using the legacy flag.

https://github.com/rjrodger/seneca-joi
