### ISSUE TITLE
Possible breaks in Node v6

### ISSUE THREAD

**Issue by mcdonnelldean** [senecajs/seneca#418]
@mihaidma Could you add a PR with v6 attached? I don't want to accept it yet but I think something in seneca is breaking due to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect so I want to see what it is :D

@mcollina Did they move all the apply stuff around?

**Comment by mihaidma** [comment]
@mcdonnelldean 
https://github.com/senecajs/seneca/pull/419

**Comment by mcdonnelldean** [comment]
Merged with #409
