### ISSUE TITLE
Error: seneca: Action PIN responded with result that was not an object or array:

### ISSUE THREAD

**Issue by psnider** [senecajs/seneca#424]
node v5.0.0
seneca 1.4.0

I've just encountered a very painful error, when I switched my app to use a Google Protocol Buffers data feed, from an XML feed.
Although the data representations were slightly different in the two formats, the changes were minor and obvious, and all of my other code stayed the same.

After the switch I started getting this cryptic error:
```
Error: seneca: Action cmd:read-protobuf-file,role:abc responded with result that was not an object or array: {MY_OBJECT_HERE}; Use option strict:{result:false} to allow; arguments were: { role: 'abc',  cmd: 'read-protobuf-file'}
```
After a fair bit of investigation, I discovered in seneca.js#164, function act_done:
```
           !(_.isPlainObject(resdata) ||  
```
which apparently is checking that my response is a plain object!

This seems like a clear error. As long as my object marshals correctly as JSON, what difference does it make whether it's a plain object?

As it turns out, the [Google Protocol Buffer](https://www.npmjs.com/package/protobufjs) library that I use returns objects with a *prototype* field, which then causes it to fail this test.

I changed this line to be:
```
          !((typeof resdata == 'object')||
```
and my code started working again.

Please either accept my change, or explain prominently in the documentation why only "plain" objects are allowed.

**Comment by mcdonnelldean** [comment]
Hey @psnider,

The reasoning behind plain objects is because this is the only way to have a reliable transport.
We tried to marshal objects to json before and this led to weird edge case issues where we had 
quasi marshal support. This basically means you must marshal your data before you send it on.

As the error note says, you can use `strict:{result:false}` in the options you pass to Seneca to disable this check but we generally can't support any issues that arise because of marshaling.

You are correct about the documentation. I will update #413 with a note to add this clearly in the api doc. This change should drop in the next week for the documentation.

Merged with #413

**Comment by psnider** [comment]
Also, please change the error message to be clearer, such as:
> ...responded with result that was not a **plain** object...

**Comment by psnider** [comment]
It seems I resolved the problem by explicitly creating a new object literal.
```
this.add('role:abc,cmd:read', (msg, respond) => {
    readProtoBufDataFeed((error, msg) => {
        // protobuf was created from protobufjs library, and is an object that can be marshalled to JSON
        if (!error) {
            var obj = {
                a: msg.a,
                b: msg.b
            }
        }
        respond(error, obj)
    })
})
```

However, this only changed the top level object. 
It seems that in theory the test ```  !(_.isPlainObject(resdata) ||  ``` should also apply to each referenced object. Does seneca also require that I change the referenced objects as well? And what about plain objects that cannot be easily marshaled? (e.g. with circular references)
This seems complicated.

My understanding of seneca is that I should write every action handler to work with marshalable data (I think JSON.stringify).
I thought this was my responsibility, and didn't realize seneca was trying to enforce this.
In general, it seems that the only reliable way to ensure that data is marshalable is that it is in a Buffer,
or it can be marshaled by JSON.stringify, or similar.

**Comment by mcdonnelldean** [comment]
You need to handle converting the data to a plain object. How you do this is up to your implementation but Seneca will only accept plain objects (literals or things made with new Object()).

As noted above, if you are not happy with that functionality you can turn it off. Seneca will try to send what you gave it. Results will vary by transport.

**Comment by psnider** [comment]
Understood. Thanks...
