### ISSUE TITLE
Plugin name is not set up correctly

### ISSUE THREAD

**Issue by mazzy89** [senecajs/seneca#429]
I'm using Seneca 2.1.0 and this is my project:

``` javascript
'use strict'

require('dotenv').config()

require('seneca')()
  // exsting Seneca plugin
  .use('jwt', {
    key: process.env.KEY
  })
  // my own plugin
  .use('../auth')
  // activate repl
  .repl(42001)
  // connect to the seneca auth listening microservice
  .listen(41001)
```
### Auth plugin

``` javascript
'use strict'

module.exports = function (opts) {
  const seneca = this

  const plugin = 'auth'

  seneca.add('role:auth,cmd:generateToken', generateToken)

  function generateToken (args, done) {
    seneca.act(
      'role:jwt,cmd:sign',
      { payload: args.payload },
      (err, token) => {
        if (err) {
          done(err)
        }

        done(null, token)
      })
  }

  return {
    name: plugin
  }
}
```

In this case the plugin name is not set correctly and in the log it is display ../auth as name

**Comment by mcdonnelldean** [comment]
@mazzy89 Cheers for taking the time to report this. As discussed on gitter this has been confirmed on my end. @rjrodger I need to figure out if this is a regression, lets chat about it on Tuesday.

**Comment by rjrodger** [comment]
In this version of the plugin system log entries that are emitted before the plugin init completes don't use the returned name - it hasn't been returned yet :)

The workaround is to name the plugin function:

```
module.exports = function auth (options) { ... }
```

Later this year we will introduce a streamlined plugin system to address technical debt such as this. It will of course be backwards compatible.

**Comment by mihaidma** [comment]
realted issue: https://github.com/senecajs/seneca/issues/459

**Comment by rjrodger** [comment]
@mihaidma have these changes been made? I don't see a linked resolving commit?

**Comment by mihaidma** [comment]
@rjrodger no, not made yet. I'll put it on the task list

**Comment by thekemkid** [comment]
So, I've reproduced this, but the plugin logs only display './plugin-path' in the init phase, then will be updated with the returned name, after.

All I can suggest doing is adding a log to state './plugin-path updated plugin log name to plugin-name'
