### ISSUE TITLE
Handle fatal errors in production

### ISSUE THREAD

**Issue by StarpTech** [senecajs/seneca#430]
Hi,
what is best practice to handle fatal errors in production? There is no documentation about how to handle errors in seneca. I found something about fixedargs and fatal$: false, undead.... but this seems very tricky and not the convient way.
The link `senecajs.org/fatal.html` in seneca error trace is also down. Seneca is used since 5 years in production. How do you handle errors? I want to understand how it works :)

#398 

Thank you.

**Comment by StarpTech** [comment]
#398

**Comment by mcdonnelldean** [comment]
@StarpTech This is something we are in the middle of in terms of documentation.

In general, fatal errors are just that, fatal. They will crash the process. In production we wire up our microservices to restart when this happens. 

However, there is a distinction between regular errors and fatal errors. Fatal errors should be reserved for when the action is actually fatal. If it is just a business logic failure (one that you know how to handle) you should not use the err-back for this. 

Consider the [following](https://github.com/nodezoo/nodezoo-npm/blob/master/lib/npm.js) code in nodezoo-npm. In the case of this module all of the errors that happen are 'recoverable' meaning they don't need to be fatal. In this instance we use `{ok:false, err: err}` vs `{ok:true, data: data}`. The only time we return a full error in the callback as the first param is when we don't know how to proceed.

Of course, as you alluded to in #398 we are looking to simplify this stuff before the end of the year. The general consensus is we need to be more clear about handling 'transport' errors vs 'process' errors.

Once 3.0.0 drops on the 14th of June I have some time set aside to write up a document on this with clear examples.

**Comment by mcdonnelldean** [comment]
@StarpTech Going to close as answered but as always feel free to reopen if you need more info or have further questions.

**Comment by StarpTech** [comment]
@mcdonnelldean thank you very much it clarifies a lot so you prefer to mark a business logic failure as a flag in the response format instead to passing it in the callback? This means that only fatal errors should be passed directly to the callback? Its a little bit confusing because it works against error-first-callbacks.

**Comment by mcdonnelldean** [comment]
@StarpTech Exactly. I agree on it not being friendly though. It is something we are looking at in depth soon. It needs to be changed for sure but for now this should get you out of a hole.

**Comment by StarpTech** [comment]
@mcdonnelldean This is same way you goes?  I think we should document this. Any beginner would thank you for that.

**Comment by mcdonnelldean** [comment]
Way ahead of you! I'm 50% done on a doc for it for release with 3.0 👍

Kindest Regards,

Dean
