### ISSUE TITLE
Seneca + consult

### ISSUE THREAD

**Issue by jackyphuong** [senecajs/seneca#431]
I am new with Seneca, i found a plug in client load balace. But i dont know Seneca can work with Consult? If posible, how can seneca client can act?

Thanks,

**Comment by mcdonnelldean** [comment]
@jackyphuong I've asked around, unfortunately there is nobody I have access to that has experience with this. I will leave the item open a few more days to see if a community member pops by.

**Comment by jackyphuong** [comment]
@mcdonnelldean  many thanks

**Comment by jackyphuong** [comment]
@mcdonnelldean I just implement this feature with Docker + Consul + Seneca, please ref to https://github.com/jackyphuong/microservice and try it

**Comment by mcdonnelldean** [comment]
Oh nice! I'll take a peek over the weekend.

**Comment by mcdonnelldean** [comment]
@jackyphuong I'm going to close this as the question was how to do this and you now have an implementation. I'm hoping to get a look at this soon. Looks interesting. Please feel free to reopen if you have anymore questions.
