### ISSUE TITLE
Increase `seneca.act` timeout

### ISSUE THREAD

**Issue by shaunwarman** [senecajs/seneca#432]
Is it best practice to act solely on the seneca client when manipulating all seneca options via:
```
seneca.use('options', 'options.js')

var options = seneca.export('options')
```

... where one of the options could be a timeout for seneca actions? I tend to see some seneca timeouts when doing some tests locally. I see that the default action timeout is [11111 ms] (https://github.com/senecajs/seneca/blob/7dcd43011090885c927bc672762236031a875e51/seneca.js#L61-L62)

**Comment by mcdonnelldean** [comment]
I tend to do them separately, eg https://github.com/nodezoo/nodezoo-github/blob/master/srv/start.js

**Comment by shaunwarman** [comment]
Ah, thanks!
