### ISSUE TITLE
Check if matched pattern available

### ISSUE THREAD

**Issue by StarpTech** [senecajs/seneca#433]
Hi,
is it possible to check whether a matched pattern is available without running into a timeout? Thanks

**Comment by mcdonnelldean** [comment]
Yes, you can use `seneca.use(somepattern)` which returns a bool

**Comment by mcdonnelldean** [comment]
Oops fat fingered that answer its actually`seneca.has(pattern)` 😊

**Comment by StarpTech** [comment]
I just thought "whaat" :D thanks!

**Comment by StarpTech** [comment]
@mcdonnelldean but you can only check your registered actions within a plugin right? I want to check across plugins on the same seneca host.

**Comment by mcdonnelldean** [comment]
@StarpTech It will check anything loaded locally and anything that is defined via `.client()` but that doesn't mean it is there, only that there is a handler registered. It won't cross the network to check.

**Comment by mcdonnelldean** [comment]
Closing as answered feel free to open if you have further questions.
