### ISSUE TITLE
Getting an Uncaught TypeError in jsonic while trying to run Seneca with Meteor.

### ISSUE THREAD

**Issue by Kenny4444** [senecajs/seneca#436]
I am getting the following error when trying to use Seneca with Meteor:

Uncaught TypeError: Cannot read property 'jsonic' of undefined jsonic.js:10
(anonymous function)	@	jsonic.js:10
meteorInstall.node_modules.seneca.node_modules.jsonic.jsonic.js	@	jsonic.js:2197
fileEvaluate	@	install.js:141
require	@	install.js:75
meteorInstall.node_modules.seneca.seneca.js	@	seneca.js:13
fileEvaluate	@	install.js:141
require	@	install.js:75
meteorInstall.imports.api.tasks.js	@	tasks.js:4
fileEvaluate	@	install.js:141
require	@	install.js:75
meteorInstall.imports.ui.body.js	@	body.js:5
fileEvaluate	@	install.js:141
require	@	install.js:75
meteorInstall.client.main.js	@	main.js:2
fileEvaluate	@	install.js:141
require	@	install.js:75
(anonymous function)	@	app.js?hash=5593d1e…:375

Here are the repositories that repro this issue:
https://github.com/Kenny4444/senecaMicroService
https://github.com/Kenny4444/senecaMeteor

**Comment by mcdonnelldean** [comment]
@Kenny4444 I haven't used Meteor. This may take some time.

**Comment by mcdonnelldean** [comment]
@Kenny4444 Having reviewed Meteor and it's way of working I don't think Seneca is going to work with it. Seneca is designed to 'own' your backend in a similar way that Meteor does. For that reason it would be my opinion that both are not compatible with each other. 

I'm going to close as incompatible, if you have any questions though, please feel free to reopen. Thanks!
