### ISSUE TITLE
Security question

### ISSUE THREAD

**Issue by ro70** [senecajs/seneca#441]
With
```
# call the color:red action pattern
echo '{"id":"w91/enj","kind":"act","origin":"h5x/146/..77/-","act":{"color":"red"},"sync":true}' | nc 127.0.0.1 10201
```
(see [here](https://github.com/senecajs/seneca-transport))

anyone can call any services. Am I right? If so, how can I prevent this?

**Comment by timoweiss** [comment]
I think you should secure your network in this case.
eg. open only port 443 and authenticate/authorise requests in an API-layer. From there you can dispatch the work that needs to be done to your services.

But yes, from inside the network, your services are "callable".

**Comment by mcdonnelldean** [comment]
Yes, generally your microservice system is internal, any external calls should be handled via a proxy or gateway.

**Comment by mcdonnelldean** [comment]
@ro70 I'm going to close as answered but feel free to reopen with further questions!
