### ISSUE TITLE
Seneca for long running process

### ISSUE THREAD

**Issue by jackyphuong** [senecajs/seneca#442]
Hello, i am trying to find to way to implement long running process such as service to send mail, resize image,... I tried to use amqp but it seems it just supports request-response. Could you please let me know how can implement in Seneca?

Thanks,

**Comment by timoweiss** [comment]
To call something async (fire&forget) you can simply remove the callback of of your seneca.act call:

```javascript
seneca.act({role: 'mailer', cmd: 'send', some: 'data'});
```

Another option could be to immediately call back in the service:

```javascript
seneca.add({role: 'mailer', cmd: 'send'}, function sendMail(args, cb) {
    cb(null, {msg: 'Thank you, I received your request. I will get it done soon.'});

    reallySendMail(args);
});
```

**Comment by mcdonnelldean** [comment]
As @timoweiss says.

We have a sample of this via nodezoo, see https://github.com/nodezoo/nodezoo-docs/blob/master/doc/architecture.md specifically nodezoo-updater and nodezoo-dequeue

**Comment by jackyphuong** [comment]
Thanks, I will try

**Comment by mcdonnelldean** [comment]
Awesome, I'll go ahead and close. Feel free to reopen if you have any more questions.
