### ISSUE TITLE
seneca.util.argprops

### ISSUE THREAD

**Issue by rjrodger** [senecajs/seneca#446]
Is this used anymore? Definitely should be deprecated. Move to legacy for Seneca 3.x and remove in 4.x?

**Comment by mcdonnelldean** [comment]
I'll do a sweep around the core plugins and note them here if I find anything.

**Comment by mcdonnelldean** [comment]
Didn't find anything using it. Because of that, I'll deprecate for 3.x. There will be a notice in the release notes about it. Closed via #489
