### ISSUE TITLE
concurrent call in senecajs

### ISSUE THREAD

**Issue by AkashSouravNayak** [senecajs/seneca#449]
how we can know how many concurrent call can be done in senecajs?

**Comment by mcdonnelldean** [comment]
Hey @AkashSouravNayak could you give me more detail? The answer based on the above is different depending on the context. It depends on transport used, data transfered, etc.

**Comment by AkashSouravNayak** [comment]
Atually i am trying to develop one software using nodejs-mariadb and using senecajs microservice so i want to know how to limit concurrent call from senecajs?

**Comment by mcdonnelldean** [comment]
@AkashSouravNayak It may be best to come have a chat in the Gitter channel https://gitter.im/home/explore I'd need more context as the question is too open ended to give a finite answer.
