### ISSUE TITLE
seneca .load not matching _id field from local database

### ISSUE THREAD

**Issue by jamesf7** [senecajs/seneca#451]
Hi,

Seneca not matching _id field from local database which i recently migrated from live database. Though same query working on live database.

`userEntity.loadPromise({ '_id': new ObjectID(msg.userId) })`

Only difference is local mongodb version is 3.2.8 and compose(live) one is 2.6.9.
Query from robomongo tool on local database working fine.do we missing something in this?
Thanks in advance.

**Comment by rjrodger** [comment]
This issue is best raised on the mongo-store plugin: https://github.com/senecajs/seneca-mongo-store

Some test case code to reproduce would also be useful - thanks!

**Comment by mcdonnelldean** [comment]
Moved to: https://github.com/senecajs/seneca-mongo-store/issues/43
