### ISSUE TITLE
Testing mode

### ISSUE THREAD

**Issue by rjrodger** [senecajs/seneca#454]
Seneca is awkward to use in a unit test context as it is designed to be run as a service.
Current unit testing best practice is to set the log mode to 'test', and use the global error handler:

```
it('my-test', function (done) {
 var seneca_instance = Seneca({log: 'test'}).error(done)
 // tests
})
```

It would be cleaner, _and enable additional test-friendliness behind the scenes_ to be able to say:

```
it('my-test', function (done) {
 var seneca_test_instance = Seneca().test(done)
 // tests
})
```

This would set up appropriate logging etc

/cc @mcdonnelldean @pelger @geek

**Comment by AdrianRossouw** [comment]
why would you pass it the done callback?

wouldn't you end up having to call it twice once you are actually done with your tests.

**Comment by rjrodger** [comment]
Hi @AdrianRossouw !

.test(done) just stores a reference to done that is only called in the case of an error
this means you can ignore the error parameter in test code
in the current version .error(done) does the same thing
example: https://github.com/senecajs/seneca/blob/master/test/sequence.test.js

you do indeed call done once you are finished, but it is always to indicate success

**Comment by AdrianRossouw** [comment]
But isn't the idiosyncratic usage of the code to be 👍 

```

it('some test', function(done) {
  myFunction(arg1, arg2, function(err, result) {
     if (err) return done(err);

     // some tests
     done();

  })
});
```

In that case, (the common one), done would be called more than once.

I don't think we should be calling the done function for the user unless they specifically request it in their flow.

**Comment by rjrodger** [comment]
implemented as above, and seems to work well
