### ISSUE TITLE
seneca.js fatal 404

### ISSUE THREAD

**Issue by auridevil** [senecajs/seneca#456]
While receiving fatal error seneca print this message:
  ALL ERRORS FATAL: action called with argument fatal$:true (probably a plugin init error, or using a plugin seneca instance, see **senecajs.org/fatal.html)**
    at ....

but **senecajs.org/fatal.html** doesn't exists on the server (404)

**Comment by mcdonnelldean** [comment]
Moved to https://github.com/senecajs/senecajs.org/issues/236
