### ISSUE TITLE
backlog in lib/transport.js would never get send

### ISSUE THREAD

**Issue by dimichgh** [senecajs/seneca#464]
I am not sure if this is used, but while looking at the code I found that this part does not seem to be right: https://github.com/senecajs/seneca/blob/master/lib/transport.js#L145

Should it internally use liveclient when working on backlog instead of the one that populates backlog?

``` js
function sendnext () {
          if (!sendqueue.length) {
            sendclient = liveclient
          }
          else {
            var tosend = sendqueue.shift()
            liveclient.send.call(tosend.instance, tosend.args, tosend.done)
            // BAD: sendclient.send.call(tosend.instance, tosend.args, tosend.done)
            setImmediate(sendnext)
          }
        }
```

**Comment by mcdonnelldean** [comment]
@rjrodger Could you comment here?

**Comment by rjrodger** [comment]
This queue has been removed, as the updated gate-executor handles this case.
