### ISSUE TITLE
Is there any work being done gRpc

### ISSUE THREAD

**Issue by grandmore** [senecajs/seneca#465]
Is there any work being done on using [gRpc](http://www.grpc.io) as the transport layer instead of http/tcp?

I have been working my way through it over the weekend and realise that it would be very beneficial to Seneca.js.

1. built in health checks
2. faster and smaller (3 orders of magnitude)
3. hooks for logging & tracing.
4. bidirectional traffic
etc etc

I was looking at how to add tracing using [Zpkin](http://zipkin.io) to Seneca and found that using gRpc would provide a nice approach.

There is a good article on the speed differences when etcd have tested [gRPC vs JSON RPC](https://blog.gopheracademy.com/advent-2015/etcd-distributed-key-value-store-with-grpc-http2/) along with a good [video presentation](https://www.youtube.com/watch?v=-2sWDr3Z0Wo) about it's use at Square

The round trip of messages between services is dropped from 1.6ms to 120μs. This alone is extremely beneficial.

**Comment by mcdonnelldean** [comment]
@grandmore No plans right now. Having said that, we certainly wouldn't be upset if someone wanted to explore a gRpc transport.

**Comment by grandmore** [comment]
I am going to look into it today as it solves a lot issues for me. I assume there be a few unknowns but hopefully no 'gotchas'.

If it works I'll contribute the code.

Thanks.

**Comment by grandmore** [comment]
I have looked into adding grpc, but from what I can see it will not be straight forwards as there is a lot of reliance on the [transport/transport-utils.js](https://github.com/dimichgh/seneca-transport/blob/master/lib/transport-utils.js) library in many of seneca components, namely seneca-transport, seneca-mesh and seneca-balance.

In order to use grpc these three libraries would need to be updated as well as they all use node's Net library whereas grpc uses the http/2 and does not need the Net libraries, however it does integrate with it.

Sadly I don't have enough familiarity with Seneca to do this quickly, so I'm going to work with the tcp transport as an interim until I can get help from you guys on the right approach.

Cheers.
