### ISSUE TITLE
Nested modules loosing transport configuration

### ISSUE THREAD

**Issue by RamonDonnell** [senecajs/seneca#466]
I have a simple nested module setup as seen in the code below, using redid-transport as an example.

````javascript
// app.js
seneca
	.use(require('./redis-transport'))
	.use(require('./subModule'))
	// .add('role:pub,cmd:something', react) // [1] works
	.listen( {
		type:'redis',
		pins:[
			'role:pub,cmd:something'
		]})

//subModule.js
module.exports = function () {
	const seneca = this
	this.use(require('./subSubModule'))
	// .add('role:pub,cmd:something', react) // [2] works
}

//subSubModule.js
module.exports = function () {
	const seneca = this
	this.add('role:pub,cmd:something', react) // [3] does not work !
}
````

[1], [2] work, but [3] in the second level nested module does not.

When the app starts it should subscribe on redis with the 'role:pub,cmd:something' pattern. Monitoring this with redis-cli, [1] & [2] both subscribe, [3] does not. 

I added a dynamic property to seneca in app.js and it appears in both sub modules, so seems to be the correct context. I haven't had this problem in seneca 1.0, and it has appears after upgrading to 2.1.

Workaround is to only go one module deep.

Bug or am I missing something?

**Comment by mcdonnelldean** [comment]
@RamonDonnell Maybe it's a bug in redis? The code above is not complete so is untestable. I came up with this sample, over http, that works as expected,

```js
'use strict'

var seneca = require('seneca')
var service = seneca()
var tester = seneca()



function subSubModule () {
  this.add('role:pub,cmd:something', (msg, done) => {
    done(null, {echo: msg})
  })
}

function subModule () {
  this.use(subSubModule)
}



service
  .use(subModule)
  .listen({
    type: 'http',
    port: '4040',
    pins: [
      'role:pub,cmd:something'
    ]
  })

service.ready(() => {
  tester.client({
    port: 4040,
    pins: [
      'role:pub,cmd:something'
    ]
  })

  tester.act('role:pub,cmd:something', (err, msg) => {
    console.log('error is: ' + err)
    console.log('msg is: \n' + JSON.stringify(msg, null, 2))
    process.exit()
  })
})
```

It essentially does the same thing, wire up sub modules. The result I get is,

```bash
2016-08-08T09:07:17.981Z z4b3achexwu3/1470647237961/59543/- INFO	hello	Seneca/2.0.1/z4b3achexwu3/1470647237961/59543/-	
2016-08-08T09:07:18.398Z c8cimbvny89p/1470647238392/59543/- INFO	hello	Seneca/2.0.1/c8cimbvny89p/1470647238392/59543/-	
2016-08-08T09:07:18.416Z z4b3achexwu3/1470647237961/59543/- INFO	listen	{type:http,port:4040,pins:[role:pub,cmd:something]}	
2016-08-08T09:07:18.647Z c8cimbvny89p/1470647238392/59543/- INFO	client	{port:4040,pins:[role:pub,cmd:something]}	
error is: null
msg is: 
{
  "echo": {
    "role": "pub",
    "cmd": "something",
    "transport$": {
      "track": [
        "c8cimbvny89p/1470647238392/59543/-"
      ],
      "origin": "c8cimbvny89p/1470647238392/59543/-",
      "time": {
        "client_sent": "1470647238665"
      }
    },
    "ungate$": true,
    "tx$": "lz4pwarpdhyk",
    "meta$": {
      "id": "90fizhcrp2yf/lz4pwarpdhyk",
      "tx": "lz4pwarpdhyk",
      "start": 1470647238705,
      "pattern": "cmd:something,role:pub",
      "action": "(djmk90e73lb5)",
      "entry": true,
      "chain": [],
      "sync": true
    }
  }
}
```

I left in the meta info too so you can see it goes over transport,

**Comment by RamonDonnell** [comment]
@mcdonnelldean following your sample, I replaced with latest seneca-redis-transport.

```javascript
'use strict'

var seneca = require('seneca')
var service = seneca()
var tester = seneca({timeout:1000})



function subSubModule () {
	this.add('role:pub,cmd:something', (msg, done) => {
		done(null, {echo: msg})
	})
}

function subModule () {
	this.use(subSubModule)
}



service
	.use('redis-transport')
	// .use(subModule)       // timeout
	// .use(subSubModule) // works as per http example
	.listen({
		type: 'redis',
		pins: [
			'role:pub,cmd:something'
		]

	})

service.ready(() => {
	tester
		.use('redis-transport')
		.client({
			type: 'redis',
			pins: [
				'role:pub,cmd:something'
			]
	})

	tester.act('role:pub,cmd:something', (err, msg) => {
		console.log('error is: ' + err)
		console.log('msg is: \n' + JSON.stringify(msg, null, 2))
		process.exit()
	})
})
```

uncomment  .use(subModule) results in tester timeout (with no redis subscribe)  ; or
uncomment  .use(subSubModule) works as per the http sample (with a redis subscribe as expected).

You'll need 
redis installed (no password)
npm seneca-redis-transport 

As another test I pulled out redid-transport.js into the project and installed the latest dependencies with the same result.

Is this seneca or the redis transport plugin?

Where is the best place to find a transport plugin reference? 
I took a look at seneca-transport/lib/http.js but its very different to seneca-redis-transport.

**Comment by mcdonnelldean** [comment]
@RamonDonnell Looks like a Redis issue. That plugin is on a list of things to fix in the next 3 weeks. If this is a bug we should get to it soon. I don't think it is seneca proper since http works as expected.

**Comment by RamonDonnell** [comment]
I'm happy to have a look at redis, as I've been through it in detail and I've got an async redis version I'm working on with the same issue.

Which transport plugin is the best to use as a reference ?

**Comment by mcdonnelldean** [comment]
@RamonDonnell Good stuff! [redis-queue-transport](https://github.com/senecajs/seneca-redis-queue-transport) is decent. As is the standard one (http + tcp)

Honestly all the transports are a little icky and being worked on soon so any help is much appreciated. 

We also have a gitter channel which I try to check 1 per day https://gitter.im/senecajs/seneca which is a good place to ask questions.

**Comment by mcdonnelldean** [comment]
Closed as redis-transport issue

**Comment by mihaidma** [comment]
@RamonDonnell we renamed the seneca-redis-transport: https://github.com/senecajs/seneca-redis-pubsub-transport
