### ISSUE TITLE
the tcp transport does not work

### ISSUE THREAD

**Issue by grandmore** [senecajs/seneca#467]
@dimichgh has fixed it in a PR. When will you update this version to bring in the fix for the seneca transport? https://github.com/senecajs/seneca-mesh/issues/40

I have forked seneca in order to get the update but it would be more convenient if it was brought into the the current version.

Thanks.

**Comment by mihaidma** [comment]
mesh was moved to senecajs org and will be reviewed today. Should not take more than 1-2 days
