### ISSUE TITLE
Logging - tracing

### ISSUE THREAD

**Issue by StarpTech** [senecajs/seneca#481]
Hi,
what is best-practice to log my microservice infrastructure with senecajs? Which tools do you use?
How can I track, Latency, timeout problems or discovering the call chain of all responsible services?
Thanks.

**Comment by mcdonnelldean** [comment]
From Seneca 3.0 you will be able to directly swap out the logger. Given everything goes through this you can pull stats from it in a less latent way than listening for all of the messages.

See https://github.com/senecajs/seneca/blob/master/docs/examples/basics-custom-logger.js

Seneca logs everything that happens, when a plugin loads, when it is ready, when an act enters, and when it leaves. You could do a couple of things here. You could log it all to ELK or even track the data locally and generate timings and latency. You could then send these off to Elastic or some time-series database.

**Comment by mcdonnelldean** [comment]
@StarpTech I'm going to go ahead and close as answered. We will have a couple of loggers to demonstrate this in more detail for 3.0 in a little over a week.

**Comment by StarpTech** [comment]
HI @mcdonnelldean sounds great I am very excited to see the imrovements of 3.0

**Comment by brandonros** [comment]
I can't find this in the documentation. Where is it
