### ISSUE TITLE
recover data form 

### ISSUE THREAD

**Issue by jamaikarima** [senecajs/seneca#484]
Hi,
I am new to seneca. I recover the data form(HTML form) with JSON , 
how can I recover it with seneca ?
how can i send data to JSON (or HTML ) ?

**Comment by mcdonnelldean** [comment]
@jamaikarima You wouldn't.

Generally, you would use Hapi or Express or some other HTTP server to talk to the browser. This would then talk to one or more seneca microservices.

Please see: http://senecajs.org/docs/tutorials/getting-started.html

**Comment by jamaikarima** [comment]
@mcdonnelldean thank's for the response,
i already use express server to talk with the browser my problem is how get the data form and use it as an input data
