### ISSUE TITLE
http://senecajs.org/get-started/ not found

### ISSUE THREAD

**Issue by mojochao** [senecajs/seneca#485]
The quick start link from the main page directs to http://senecajs.org/get-started/ which isn't found.

**Comment by mcdonnelldean** [comment]
Hey @mojochao cheers for letting me know. We have a bug in the plugin that rewrites the URLs in our website. Should be fixed soon. You can find the doc at the URL  http://senecajs.org/docs/tutorials/getting-started.html for now.

I have this issue noted on the site repo too so I will go ahead and close this. Cheers!
