### ISSUE TITLE
Run plugin tests against the PR branch

### ISSUE THREAD

**Issue by mihaidma** [senecajs/seneca#492]
Travis runs tests with seneca also against seneca plugins. The issue is that for plugins the tests are running against master. Check if Travis has an env variable that specifies the PR branch and run plugin tests against it.

For seneca itself the tests are running against the PR branch.

**Comment by mcdonnelldean** [comment]
@mihaidma Can we call this done?

**Comment by mihaidma** [comment]
it is done, i'll close it
