### ISSUE TITLE
move action caching into a plugin

### ISSUE THREAD

**Issue by rjrodger** [senecajs/seneca#509]
the actcache is causing more problems that it solves

**Comment by mcdonnelldean** [comment]
@rjrodger What do we loose here? So I understand. Reviewing the code it looks like actcache is supposed to handle idempotency in messages, is that correct?

**Comment by rjrodger** [comment]
action caching is a special case of a more general set of distributed error handling strategies - it's not special as such, as has no more claim to be in core than others (e.g retries).

in any case, this would be discussion for 4.0 - this issue is just a reminder :)

**Comment by mcdonnelldean** [comment]
Awesome. Makes sense. Shouldn't be a huge job.

**Comment by mcdonnelldean** [comment]
Note. Feature is off by default as of seneca 3.0

**Comment by rjrodger** [comment]
obsoleted by common.History introduced in 3.4.0
