### ISSUE TITLE
Error passing `seneca.log` args?

### ISSUE THREAD

**Issue by marcopiraccini** [senecajs/seneca#516]
Seneca 3.0.0, node v6.3.1. 
test.js: 
```
var seneca = require('seneca')()
```
Launching it: `node ex1.js --seneca.log.quiet`, I get:
```
TypeError: Legacy.parse_command_line is not a function
    at module.exports (/home/marco/workspace-seneca/seneca-in-practice/node_modules/seneca/lib/optioner.js:81:14)
    at make_seneca (/home/marco/workspace-seneca/seneca-in-practice/node_modules/seneca/seneca.js:253:23)
```

**Comment by mcdonnelldean** [comment]
Hey @marcopiraccini The flags are part of the legacy logger. You need to load 'seneca-legacy-logger' to go back to the old one.

Alternatively,

```
var seneca = require('seneca')({log: 'silent'})
```

Should work with the new logger.

**Comment by mcdonnelldean** [comment]
Marked as regression. We should do a better job of handling this case when the legacy logger is not loaded.

**Comment by linde12** [comment]
Weird. I'm almost certain that the flags were working for me with 3.0.0 yesterday, but today it crashes just like @marcopiraccini said.

Is there any docs on the new logger? I wish to pass it a type filter and see all "ACT" messages if it's possible

**Comment by mihaidma** [comment]
@linde12 see: [the Seneca API](https://github.com/senecajs/senecajs.org/blob/master/src/pages/api/index.md#loglevelentry-)

Also see:
https://github.com/senecajs/seneca/issues/523
https://github.com/senecajs/seneca/issues/522

**Comment by linde12** [comment]
@mihaidma Ah, yes, i glanced at those but i thought it was incomplete since the "filter options" from the legacy logger were missing. Anyway, thanks for the heads up!

**Comment by mcdonnelldean** [comment]
https://github.com/senecajs/seneca/issues/531
