### ISSUE TITLE
es6/es7 support

### ISSUE THREAD

**Issue by xpepermint** [senecajs/seneca#519]
I know that Promises has been discussed here but using bluebird is kind of old stuff. Are there any plans to support Promises (+async/await)? I believe that many developers ignore this package due to the lack of ES6/ES7 support.

**Comment by benjamin658** [comment]
Use babel to enable ES6/ES7 feature

**Comment by mcdonnelldean** [comment]
@xpepermint There are now current plans for Promises / Async right now outside of making sure third party extensions, like Bluebird work accordingly.

**Comment by hacknaked** [comment]
Any roadmap or update on this?
