### ISSUE TITLE
Seneca init should not log hello

### ISSUE THREAD

**Issue by doliver3** [senecajs/seneca#521]
Seneca init logs hello in its init
  seneca.log.info({kind: 'notice', notice: 'hello'})

Someone viewing the logs would assume this is a mistake since 'Hello world' apps are typically just example apps.

There should be an option to disable this. Alternatively the text should be more informative such as "Seneca initialization started"

**Comment by mcdonnelldean** [comment]
@doliver3 Agreed. The notice is also happening before custom loggers have inited. The plan is to move this lower and change it to Seneca <id> instance started.
