### ISSUE TITLE
Best practices to log entries and catch errors in 3.0.0

### ISSUE THREAD

**Issue by afoninsky** [senecajs/seneca#523]
What's the best practice to handle seneca logs and errors? I've made quick research over code and issue, and still don't get it

**1) Logs handling**
Usecase exmaples: i want to send all my logs into external logstash storage, or output to various streams (sdtout for info, stderr for error) so docker can catch it

https://github.com/senecajs/seneca/blob/master/docs/examples/custom-logger.js

With this code:
```javascript
module.exports = {
	createSenecaLogger() {
		function SenecaLogger () {}
		SenecaLogger.preload = function () {
			return {
				extend: {
					logger: (context, payload) => {
						// here i should place my own logger
						console.log(`incoming log message with level: ${payload.level}`)
					}
				}
			}
		}
		return SenecaLogger
	}
}
```
```javascript
const { createSenecaLogger } = require('../src/utils')
const seneca = require('seneca')({
	legacy: {
		logging: false
	}
})

seneca
	.use(createSenecaLogger())
```

I'm getting output:
```
{"kind":"notice","notice":"hello","level":"info","seneca":"dt8ngg4s9bua/1473023131618/18074/3.0.0/-","when":1473023131655}
incoming log message with level: debug
...
```

Expected output:
```
incoming log message with level: info
incoming log message with level: debug
...
```
Looks like first message is not handled by `legacy` logger handler.
If it's `legacy` option - is there somewhere available improved best practice logging handling?

**2) Errors catching**
Usecase examples: i want my nodejs process fails on fatal or not catched errors so kubernetes could launch "all-this-cool-cluster-health-recovery-stuff", or external lib from opb***.com could catch error and send to awesome dashboard UI

Instead, _completly all_ errors are catched by seneca at the moment, which breaks all external logic and make this framework not usable in production. Unfortunately, i _WANT_ to use seneca in production - because i like the this approach (given that i have not read yet "the tao of microservices" book :)

https://github.com/senecajs/seneca/issues/398

**Comment by StarpTech** [comment]
Hi @afoninsky the current approach to handle errors is to ignore them I mean you have to create your own error handling:

1. Business errors (user not found etc..): return something like `{ success: false, result : ... }`
2. All other are fatal.

I create a repository with all my problems with the current implementation https://github.com/senecajs/seneca/issues/514 Your're welcome to complement my issue and tests.

**Comment by mihaidma** [comment]
@afoninsky these are some sample logger implementations:
- You can see here a logstash sample implementation: https://github.com/senecajs/seneca-logstash-logger/blob/master/logstash.js,
- Logentries: https://github.com/senecajs/seneca-logentries-logger/blob/master/logentries.js,
- Custom logger sample: https://github.com/senecajs/seneca/blob/master/docs/examples/custom-logger.js

We also added API documentation, see here the log.level: https://github.com/senecajs/senecajs.org/blob/master/src/pages/api/index.md
I am working now on updating the `Logging with seneca` article.

You can process the logs in any way you need with a custom logger and output anything you need.
By default the `legacy` logger is disabled and none of your messages are supposed to be handled by it.

**Comment by Yumonra07** [comment]
@mihaidma What are the best practices with logging requests that span over multiple microservices? I'm thinking with using an auto-generated id per request to make logs relateable to eachother, is there any implementation in seneca for this?

**Comment by mcdonnelldean** [comment]
@afoninsky The problem you are having above is actually a bug. The log message for hello happens too soon, before the custom logger is set. See, #521

**Comment by afoninsky** [comment]
@mihaidma @mcdonnelldean - thank you for your responses

@mcdonnelldean what about second (more important) questions - "Errors catching"
is there any roadmap?

**Comment by mcdonnelldean** [comment]
@afoninsky Ok so from your example above, if you change this to

```js
const { createSenecaLogger } = require('../src/utils')
const seneca = require('seneca')({
    internal: {
        logger: createSenecaLogger()
    }
})
```

Instead of loading the plugin it will work. I am updating the examples to account for this. We need to load the logger as soon as possible so it's best not to load it as a plugin (which are loaded some time after logging has started).

As for problem 2, yup error handling sucks, we are working on it to enable the above. For now for the above you can use,

```
const { createSenecaLogger } = require('../src/utils')
const seneca = require('seneca')({
    errhandler: (err) => { return true || false}
})
```

Based on, https://github.com/senecajs/seneca/blob/master/test/error.test.js#L155 It's not ideal, but it should allow you to catch the error and handle it. 

@afoninsky @StarpTech I'll add some error handling examples over the weekend using transport to show what's available right now.

**Comment by StarpTech** [comment]
@mcdonnelldean thanks.

**Comment by mcdonnelldean** [comment]
Folks, I'm going to close but if you have more questions please feel free to ask. as of [3.1](https://github.com/senecajs/seneca/releases/tag/v3.1.0) There are examples for both logging and some error handling in. We will add more in time.
