### ISSUE TITLE
Examples need change around loggers

### ISSUE THREAD

**Issue by paolochiodi** [senecajs/seneca#530]
I'd suggest a couple of things to add based on my experience:

- [ ] Make clear that log level isn't handled by seneca 3, but is devoted to the logger implementation
- [ ]  Update the examples to remove the removed option `legacy: { logging: false } ` (i.e. see https://github.com/senecajs/seneca/blob/master/docs/examples/custom-logger.js#L34)

**Comment by mcdonnelldean** [comment]
First one is done. Second one is now handled by seneca-log-filters which is on PR #536
