### ISSUE TITLE
this can support run with pm2? because pm2 run as cluster multi node instances.

### ISSUE THREAD

**Issue by arden** [senecajs/seneca#534]
this can support run with pm2? because pm2 run as cluster multi node instances.

**Comment by mcdonnelldean** [comment]
@arden No idea, I don't see a reason it couldn't

**Comment by OriginalEXE** [comment]
I'm using pm2 with Seneca inside Docker containers and have no issues.

**Comment by mcdonnelldean** [comment]
@arden Seems this is fine. If you have any questions after trying, please let us know!
