### ISSUE TITLE
option 'log' not working as expected

### ISSUE THREAD

**Issue by blanchma** [senecajs/seneca#541]
Not sure if is a bug or a misuse of my side:

var seneca = require('seneca')({
  log: 'any'
});

Any option there: print, any, silent has the same effect: no more logging at all.

**Comment by mihaidma** [comment]
this is the log documentation: http://senecajs.org/api/#log-level-entry-
From seneca 3.x.x you can use either:
```
var seneca = Seneca({
  log: { level: 'debug+' }
})
```
or use an alias:
```
var seneca = Seneca({
  log: 'all'
})
```
What version of seneca do you use? 3.0.0?
In 3.1.0 we added support for all previous aliases (like `print`, `any`) but that is not published yet.

**Comment by mcdonnelldean** [comment]
[3.1](https://github.com/senecajs/seneca/releases/tag/v3.1.0) is now out and should correct this

**Comment by rodmaz** [comment]
Would you guys please mind to share what `debug+` as a logging level means? It seems (at least in Seneca 3.4.3) that if we set the level to `debug`, instead of `debug+`, we don't get the logs as expected.
