### ISSUE TITLE
TypeError: Legacy.parse_command_line is not a function

### ISSUE THREAD

**Issue by vishwasvadavi** [senecajs/seneca#544]
This error is related to senecajs (a microservices framework for nodejs)
When I try to run

node sales-tax.js --seneca.log.print
I get the following error

D:\SENECA\sales-tax\node_modules\seneca\lib\optioner.js:81 Legacy.parse_command_line(argv.seneca.log, ^

I tried installing "seneca legacy logger" using

"npm install seneca-legacy-logger"

and used it in the javascript program as follows

var seneca = require( 'seneca' )({ internal: {logger: require('seneca-legacy-logger')} })
But still the same error persists

Need some clarifications on it. Thank you in advance

**Comment by mcdonnelldean** [comment]
@vishwasvadavi Yes there was a problem with the loggers. Specifically the problem is --seneca.log.print not being handled. 3.1 is out later today to fix this.

**Comment by mcdonnelldean** [comment]
[3.1](https://github.com/senecajs/seneca/releases/tag/v3.1.0) is now out and should correct this

**Comment by vishwasvadavi** [comment]
Thank you @mcdonnelldean for your valuable response. I will try with the latest release and get back with the results.
