### ISSUE TITLE
Crash on --seneca.log.all

### ISSUE THREAD

**Issue by pepelazz** [senecajs/seneca#547]
Use seneca 3.1.0
`node name0.js --seneca.log.all`

error in line source/seneca/lib/optioner.js:98
`/source/seneca/lib/optioner.js:98
      var logType = Object.keys(logSpec.level)
                           ^

TypeError: Cannot convert undefined or null to object
    at parse_command_line (/test_seneca/source/seneca/lib/optioner.js:98:28)
    at module.exports (/test_seneca/source/seneca/lib/optioner.js:79:7)
    at make_seneca (/test_seneca/source/seneca/seneca.js:253:23)
    at init (/test_seneca/source/seneca/seneca.js:184:16)`

**Comment by mihaidma** [comment]
I could reproduce it. Will push a fix for it.

**Comment by mihaidma** [comment]
@pepelazz the command line format is : `--seneca.log.level.all`

**Comment by mihaidma** [comment]
close via https://github.com/senecajs/seneca/pull/551

**Comment by mihaidma** [comment]
@mcdonnelldean i just realized we should support `--seneca.log.all` beside the `--seneca.log.level.all`.

**Comment by mcdonnelldean** [comment]
Yup,

The filter should support it directly. Do you want to add to the filter and bump? We can do a minor release then

Kindest Regards,

Dean

On 19 Sep 2016, at 09:16, Mihai Dima <notifications@github.com<mailto:notifications@github.com>> wrote:


@mcdonnelldean<https://github.com/mcdonnelldean> i just realized we should support --seneca.log.all beside the --seneca.log.level.all.

-
