### ISSUE TITLE
Promise support for act/add/wrap

### ISSUE THREAD

**Issue by jluchiji** [senecajs/seneca#548]
My company has been using Seneca in production for over a year now, and we have relied on a custom plugin to add promise support to Seneca. Here is the github repo for the plugin:

[seneca-as-promised](https://github.com/jluchiji/seneca-as-promised)

Since I see that you have plans to include promise support into the Seneca itself, I thought it would be a good idea to share my existing work in that direction. This plugin has been in production for a few months now, and we have not encountered any issues with it so far.

Speaking of which, I would also really appreciate any feedback in case this plugin is doing anything it shouldn't.

**Comment by kristianmandrup** [comment]
Please mention this plugin as an option. This is 2017. To hell with callbacks!

**Comment by StarpTech** [comment]
Callback has still a performance benefit over Promises or Generators. Particularly in the transport layer performance is very important. There is no need to create a project for this. You can create a small abstraction to promisify all callbacks to promises but be careful that your `this` has the correct context. As maintainer I wouldn't provide this as an option. It operates out of the core.

**Comment by kristianmandrup** [comment]
Sure, avoid stateful services and messing with `this`! 
Thanks for the tutorial link.

[Bluebird promises benchmark](https://github.com/petkaantonov/bluebird/tree/master/benchmark)

Funny how Bluebird performs way (x4 or more) better than native promises!

[why-are-native-es6-promises-slower-and-more-memory-intensive-than-bluebird](http://softwareengineering.stackexchange.com/questions/278778/why-are-native-es6-promises-slower-and-more-memory-intensive-than-bluebird)

**Comment by StarpTech** [comment]
@kristianmandrup when I mean `this` I talk about to get the right context if you have calls which based on each other. This important for logging and tracing.

**Comment by kristianmandrup** [comment]
Okay, thanks for clearing that up! I recall looking at Seneca two years ago but didn't seem quite ready. Nice to see the progress since then! Ready to use it now, callbacks or not :)
At least with micro services there should be limited callback hell!

**Comment by rjrodger** [comment]
@kristianmandrup correct - you don't really run into too many callback problems with small services.
