### ISSUE TITLE
Issues with mem store

### ISSUE THREAD

**Issue by marcopiraccini** [senecajs/seneca#550]
First point: is mem-store still started by default?

If I run (seneca 3.1, seneca-entity 1.3.0, this example is from the seneca doc):
```
var seneca = require('seneca')()
.use('entity')

seneca.ready(function () {
  var apple = seneca.make$('fruit')
  apple.name = 'Pink Lady'
  apple.price = 0.99

  apple.save$(function (err, apple) {
    console.log("apple.id = " + apple.id)
  })
})
```

I get: `{"notice":"seneca: No matching action pattern found for { role: 'basic',  cmd: 'generate_id',  name: 'fruit',  base: undefined,  zone: undefined }...`

So I specify the `default_plugins` (probably the doc on https://github.com/senecajs/seneca-mem-store is outdated):

```
var seneca = require('seneca')({
  default_plugins: {
    'mem-store': true
  }
})
.use('entity')

seneca.ready(function () {
  var apple = seneca.make$('fruit')
  apple.name = 'Pink Lady'
  apple.price = 0.99

  apple.save$(function (err, apple) {
    console.log("apple.id = " + apple.id)
  })
})

```

...but I get (second and main problem): 

`{"notice":"seneca: No matching action pattern found for { cmd: 'save',  role: 'entity',  ent: $-/-/fruit;id=;{name:Pink Lady,price:0.99},  name: 'fruit',  base: undefined,  zone: undefined }`

Am I missing something in conf?

**Comment by mihaidma** [comment]
Updated the readme, removed the default_plugin sample: https://github.com/senecajs/seneca-mem-store/pull/60.
The code example from readme is correct.
