### ISSUE TITLE
Graceful shutdown behavior is not working as expected

### ISSUE THREAD

**Issue by gongxiancao** [senecajs/seneca#583]
I found this issue when I tried to deal with graceful shutdown for seneca-amqp-transport plugin:

Expected behavior: 
Calling seneca.close() causes the server stop receiving and processing new tasks, but wait for the current tasks to be finished.

Actual behavior:
Calling seneca.close() causes the server to wait for all current tasks to complete. But during the processing of the current tasks, it continue receiving and processing new tasks. If the task is coming fast enough, it will last forever (if not timeout).

Please tell me that I'm wrong on this point.

**Comment by rjrodger** [comment]
Calling seneca.close will stop all further action calls - which may break calls in progress if they make more calls - this is a bug that needs to be fixed.

There is also the question of how shutdown should handle new requests - these should just be rejected - that should be the case,  but you seem to have discovered a case where it is not - do you have a unit test / script that can demonstrate this?

**Comment by rjrodger** [comment]
@gongxiancao I created a new repository for reproducing Seneca bugs: https://github.com/senecajs/repro - if you have some code that can show this bug that would b great thanks :)

**Comment by jiripospisil** [comment]
@rjrodger Reproduced at https://github.com/senecajs/repro/pull/1

**Comment by jiripospisil** [comment]
@rjrodger Any news on this?

**Comment by rjrodger** [comment]
@jiripospisil thanks for the repro PR - verifying this my side.

I think the fix is to only reject new top level actions, rather than all actions. This allows child actions to complete within currently executing top level actions.

**Comment by geronime** [comment]
Hello @rjrodger, any update on this issue, please?

**Comment by geronime** [comment]
ping
