### ISSUE TITLE
.use(seneca.export('web')) throws 'requires middleware functions'

### ISSUE THREAD

**Issue by LogOg** [senecajs/seneca#585]
Trying the tutorial http://senecajs.org/getting-started/
When trying to run node app.js I am getting the following originating from the line 
'.use(seneca.export('web'))'

/Users/macbookpro/worknode/microservice/node_modules/express/lib/application.js:209
    throw new TypeError('app.use() requires middleware functions');
    ^
TypeError: app.use() requires middleware functions
    at Function.use (/Users/macbookpro/worknode/microservice/node_modules/express/lib/application.js:209:11)
    at Object.<anonymous> (/Users/macbookpro/worknode/microservice/app.js:10:3)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:382:7)
    at startup (bootstrap_node.js:137:9)

This is the app.js code I have

var seneca = require('seneca')()
	.use('api2')
	.client({type:'tcp',pin:'role:math'})

var app = require('express')()
	.use(require('body-parser').json())
	.use(seneca.export('web')) //this is line 10 as run
	
	.listen(3000)

**Comment by gegana** [comment]
http://senecajs.org/getting-started/
outdated?

**Comment by LogOg** [comment]
No it is still an issue and while Googling for a fix I found someone else who had the same issue and had no reply on their question.

I have got everything to that point in the 'Getting Started' working and have not found anything that solved it yet.

It might be that I have not done something I need to do but have carefully looked over the steps again and again but there is nothing I have done different. I think as a 'Getting Started' it really needs to all just work as scripted else people are going to lose interest which would be a pity because it is a great framework for micro-services.

This line '.use(seneca.export('web'))' is throwing the error 'app.use() requires middleware functions' as mentioned above and would love to get it solved because I really like this framework and have invested time getting to know it...thx

**Comment by tswaters** [comment]
Docs are out of date.

I've submitted a PR to getting-started and senecajs.org that updates everything to be proper with 1.x+ of seneca-web:

https://github.com/senecajs-attic/getting-started/pull/12
https://github.com/senecajs/senecajs.org/pull/281

**Comment by LogOg** [comment]
Awesome thank you, loved Seneca so very happy that can now get the TCP working nicely and will definitely help everyone learning this great new tech :)

**Comment by rjrodger** [comment]
Thank you @tswaters !
