### ISSUE TITLE
Is Seneca still maintained?

### ISSUE THREAD

**Issue by StarpTech** [senecajs/seneca#593]
Dear Senecajs,

https://github.com/senecajs/seneca/graphs/commit-activity

we get no informations about the status of this opensource project. Just a handful of questions were answered in Slack. If you look in the issues you can find lots of untouched issues. The same situation is in the ecosystem of seneca. Lots of people trust in it and did hard work to be familiar with this framework and I think some people already use it in production and facing with issues which can not be fixed easily. The biggest point is the missing documentation about the internal fundamentals/concepts of seneca. That's one of the reason why the community can't run it alone. This is not fair. It's opensource but seneca is in charge of this ship. The [roadmap ](http://senecajs.org/roadmap/) was not kept and not updated. Please give us an update. Thank you.

Btw: Everybody can understand that there are more important things as to maintain an opensource project but I think there is always time to bring the community up to date.

Update (05.01.2017):
Because of this situation I created [Hemera](https://github.com/hemerajs/hemera) perhaps someone can use it too.

**Comment by pinxue** [comment]
It is really annoying to advertise your project this way, especially your project is not an alternative at all. 

I expected more active support from the maintainer, too. But with last PR merged in 1 month it is obviously maintained.

**Comment by StarpTech** [comment]
@pinxue it seems that you don't understand my intention. I'm working with senecajs since 2 years.  I contributed to the Framework and help people to get familiar with it. All the points I mentioned you can double check. I open this issue because the activity of the maintainer has reduced dramatically. There are lots of issues but the most important fact is that nobody talks with the community although promises were not kept see Roadmap. This is no advertising. I recommend my opensource project for people who have issues which cannot be easy solves because missing documentation or just unanswered questions since weeks.  I dont want to implement a clone of seneca. Please inform you before you blame someone with good intentions.

**Comment by rjrodger** [comment]
@StarpTech A lot of my time has been taken up with https://www.manning.com/books/the-tao-of-microservices recently - that's nearly done now. I'll be returning to more active maintenance from January 2017 onwards.

Seneca was first released in 2010 - this is a long term project. I do feel documentation has a higher priority at the moment than code however - hence new tutorials such as: http://senecajs.org/docs/tutorials/unit-testing.html

With respect to Hemera I'm fully supportive of your efforts - this is open source after all :)

**Comment by StarpTech** [comment]
Hi @rjrodger thanks for your words and I agree documentation is at the moment more important. I just want to get some vital signs from the maintainers. In the last months I had the feeling that nobody helped us no matter how big the issue was especially since the big topic of "error handling" but good to hear from you. Are you planning to change the roadmap?

**Comment by gregory** [comment]
@StarpTech looks like sencajs has NATS transport now https://github.com/cmfatih/seneca-nats-transport

**Comment by StarpTech** [comment]
@gregory the transport was not the reason to create hemera.

>We want to create a toolkit which is responsible for everything expect the transport. We don't need overall transport independence. We trust in a well tested system. The wrong path in error-handling, logging and tracing are one of the reasons why we couldn't use existing solutions.

https://hemerajs.github.io/hemera/5_hemera_vs_seneca.html

**Comment by toanz** [comment]
@StarpTech totally agree with you . we are really appreciate your effort
