### ISSUE TITLE
timeout not getting applied with seneca.options()

### ISSUE THREAD

**Issue by blueshirts** [senecajs/seneca#596]
In attempting to set the global timeout for seneca it seems to get picked up properly when you initialize seneca with the timeout.

    const seneca = Seneca({timeout: options})

If you attempt to set the timeout after the fact by using the options() function the value is saved though I don't believe it's in affect.  Calls will still timeout after 22222ms.

    const seneca = Seneca()
    seneca.options({timeout: 60000})

**Comment by blueshirts** [comment]
I believe this may be because the GateExector gets created on initialization with a timeout value though is never updated when seneca.options() is invoked.

https://github.com/senecajs/seneca/blob/master/seneca.js#L482

    GateExecutor({
        timeout: so.timeout
    })

**Comment by rjrodger** [comment]
Thanks! Yes, it's a bug.

I'd really appreciate a pull request with a unit test. :)
You don't have to fix the bug - a failing unit test is very useful by itself.

And please consider yourself a contributor and add an entry to: https://github.com/senecajs/seneca/blob/master/package.json

Every contribution helps - thanks again!
Richard

**Comment by blueshirts** [comment]
I wrote a test and confirmed that this was an issue in the master commit from 12/9.  The same test passes on the current master code base so it looks like the issue is now resolved.

**Comment by blueshirts** [comment]
I added a pull request for the test case.

https://github.com/senecajs/seneca/pull/634
