### ISSUE TITLE
Can last version of Seneca be used with node v7.x?

### ISSUE THREAD

**Issue by Snowy27** [senecajs/seneca#607]
Our team is going to convert to the latest version of node, as well as adding Seneca to our toolkit. The npm page specifies that Seneca is working with node v4.x, 5.x. Is there any that will make Seneca not to work properly with newer node versions?

**Comment by ericnograles** [comment]
@Snowy27 we've been rolling Seneca on Node LTS (6.10.0) without any issues in Heroku.  Can't say about 7.x, though.

**Comment by rjrodger** [comment]
Yeah, builds on 5 and 7 too: https://travis-ci.org/rjrodger/seneca/builds/221032742

**Comment by nfantone** [comment]
@rjrodger `README.md` still says _"Node: 4.x, 6.x, 8.x"_, though.
