### ISSUE TITLE
Expose a service to public

### ISSUE THREAD

**Issue by zhaoyao91** [senecajs/seneca#608]
Image such an architecture:
Build a lot of micro services, some of them are private, and some of them should be opened to public.
Then, create seneca clients in client apps, such as browser or Android, and make `act` to well known public seneca server.

The problems are:
- for a group of services, how to expose some to public while keep others private?
- how can client make use of these services as easy as `seneca.act` on the server?

Thanks

**Comment by davd33** [comment]
It is said in the Tao of microservices that:
"The microservice architecture does not offer any inherent security benefits, and does introduce new attack vectors if care is not taken. In particular, there is a very common temptation to share microservice messages with the outside world. This is very dangerous, as it exposes every microservice as an attack surface.
There must be an absolute separate, a "Demilitarized Zone" (DMZ) between the internal world of microservice messages, and communication with the outside world."

**Comment by zhaoyao91** [comment]
thanks

**Comment by dgonzalez** [comment]
@zhaoyao91 you might want to have a look to seneca-web which might well suit what you want to do: https://github.com/senecajs/seneca-web
