### ISSUE TITLE
meta$ should only be in action function parameter message

### ISSUE THREAD

**Issue by rjrodger** [senecajs/seneca#619]
meta$ in submitted messages (to seneca.act) should be ignored. This allows easy  copying of msgs to resend.

**Comment by rjrodger** [comment]
message directives ($ suffix) need to be added explicitly

**Comment by rjrodger** [comment]
you should not need to use `seneca.util.clean` to resubmit a message

**Comment by jmatsushita** [comment]
This would also help when asserting object deep equality which fails currently because of the meta$ key in the parent object. `util.clean` doesn't work with the inherited property necessitating manual cleaning (parse/stringify):

```
Object
├─┬ [[Parent]] : Object
│ ├─┬ [[Parent]] : Object
│ │ ├── [[Parent]] : null
│ │ ├─┬ Key: "hasOwnProperty"
│ │ │ └── [Function hasOwnProperty]
│ │ ├─┬ Key: "constructor"
│ │ │ └── [Function Object]
│ │ ├─┬ Key: "toString"
│ │ │ └── [Function toString]
│ │ ├─┬ Key: "toLocaleString"
│ │ │ └── [Function toLocaleString]
│ │ ├─┬ Key: "valueOf"
│ │ │ └── [Function valueOf]
│ │ ├─┬ Key: "isPrototypeOf"
│ │ │ └── [Function isPrototypeOf]
│ │ ├─┬ Key: "propertyIsEnumerable"
│ │ │ └── [Function propertyIsEnumerable]
│ │ ├─┬ Key: "__defineGetter__"
│ │ │ └── [Function __defineGetter__]
│ │ ├─┬ Key: "__lookupGetter__"
│ │ │ └── [Function __lookupGetter__]
│ │ ├─┬ Key: "__defineSetter__"
│ │ │ └── [Function __defineSetter__]
│ │ ├─┬ Key: "__lookupSetter__"
│ │ │ └── [Function __lookupSetter__]
│ │ └─┬ Key: "__proto__"
│ │   └── null
│ └─┬ Key: "meta$"
│   └── Object
├─┬ Key: "status"
│ └── "ok"
└─┬ Key: "events"
  └── "blah"
```

**Comment by rjrodger** [comment]
agreed seneca.util.clean should remove prototype as well to handle this case

**Comment by rjrodger** [comment]
meta has been moved to a separate parameter of action and action callback functions

**Comment by rjrodger** [comment]
seneca-transport needs to be updated to fully remove as still added if legacy.transport = true (default in 3.x)
