### ISSUE TITLE
fatal$ is set as true for all plugins

### ISSUE THREAD

**Issue by suyuan1203** [senecajs/seneca#644]
```
seneca.use(function web(options){
  var seneca = this;
  router.get('/upload', function(){
    seneca.act('role:upload', function(err, result){
      console.log('---------------------');
    });
  });
}, {
  router: router
});
```

if the seneca.act inside the plugin fails, seneca will terminate itself.

The I saw the code inside plugin.js

```
function make_delegate (instance, plugin) {
  // Adjust Seneca API to be plugin specific.
  var delegate = instance.delegate({
    plugin$: {
      name: plugin.name,
      tag: plugin.tag
    },

    // Act calls inside the plugin definition function are not gated.
    // ungate$: true,
    fatal$: true
  })

```
It seems fatal$ is set as true for all plugins which will make seneca die.
Inside seneca.js line 1119
```
if (msg.fatal$) {
          return instance.die(out.err)
        }
```
Can anybody explain why seneca choose to set fatal$ as true?

**Comment by rjrodger** [comment]
Hi @suyuan1203, this is by design. All actions in the plugin definition, and also the init action, need to complete successfully. Otherwise the plugin would be in a corrupt state.

To bypass this use the setting debug.undead = true - that is as bad as it sounds though :)

This needs an FAQ

**Comment by rjrodger** [comment]
Added an FAQ for this: http://senecajs.org/faq/#q-fatal

**Comment by W1U02** [comment]
@rjrodger I think it would be better to throw an exception instead of kill the process. It gives user a chance to fix the error.
