### ISSUE TITLE
DeprecationWarning: 'root' is deprecated, use 'global'

### ISSUE THREAD

**Issue by W1U02** [senecajs/seneca#654]
When run seneca with node v7.9, it will show the following warning:
```
DeprecationWarning: 'root' is deprecated, use 'global'
```

After a few tracing, I found the following code in `seneca.js` line 1647
```javascript
data.seneca = null == data.seneca ? root.id : data.seneca
```
I have no idea about this because root.id is defined in a function but not in the global scope.

**Comment by W1U02** [comment]
Sorry,duplicated with #566
Close this issue

**Comment by chippawah** [comment]
@W1U02 Not to bother but I can't seem to find the conclusion or workaround for this issue after reading through 566's comments. What's your current solution?
