### ISSUE TITLE
getting started

### ISSUE THREAD

**Issue by jerowe** [senecajs/seneca#673]
I'm trying to get started with seneca, but the logs look different from the docs.

```
var seneca = require('seneca')()

seneca.act({
  cmd: 'salestax',
  net: 100
}, function(err, result) {
  if (err) return console.error(err)
  console.log(result.total)
});


seneca.add( {cmd:'salestax'}, function(args,callback){
  var rate= 0.23
  var total = args.net * (1+rate)
  console.log('there should be a log');
  callback(null,{total:total})
});
```

```
➜  seneca node math.js 
there should be a log
123
{"kind":"notice","notice":"hello seneca 17xcm57xu1f6/1503447137672/2184/3.4.2/-","level":"info","seneca":"17xcm57xu1f6/1503447137672/2184/3.4.2/-","when":1503447137795}
```

But the docs say it should look something like:

```
[-isodate-]    INFO    init    start
[-isodate-]    INFO    init    end
123
```

FYI - There are also a few broken urls to an examples folder in this repo.

**Comment by amanagarwal2189** [comment]
As far as I know, it doesnt really matter. You are getting your output there and everything will work as expected. It is possible that those are the screenshots from earlier versions of seneca.  I would move past seeing '**123**' :)
Check for and report the broken links on the website here.. some might have already been reported.
https://github.com/senecajs/senecajs.org/issues

**Comment by jerowe** [comment]
I agree that I am still getting the information, but when I looked at the docs I expected for seneca to set up an initial logger in a log4j kind of style. It doesn't, and that is fine because I can set up my own logger, ;-) but I found that a little misleading. 

I know I clicked on at least one broken link. I'll go see if I can find the others.

**Comment by rjrodger** [comment]
sorry - that's an issue with the docs. For nice logs, try seneca.test('print')
