### ISSUE TITLE
prior call raising `cannot call act of undefined`

### ISSUE THREAD

**Issue by tswaters** [senecajs/seneca#677]
Upgrading to 3.4.x from 3.2.x and hit the error mentioned in the subject line, `cannot call act of undefined`.  This was the code that worked before:

```js
this.wrap('cmd:some-pin', function (msg, done) {
  var prior = this.prior
  doSomeOtherThing(msg, function (err) {
    if (err) { return done(err)
    prior(msg, done)
  })
})
```
Now that `do_act` has been replaced with `this.act` in the `delegate.prior` definition:

* before: https://github.com/senecajs/seneca/blob/v3.2.0/seneca.js#L1614
* after: https://github.com/senecajs/seneca/blob/v3.4.2/seneca.js#L1243

It is throwing an error about being unable to call `act` of undefined.

...Of course, this can be done a bit better in the code example above.  Instead of pulling out `prior` from `this` and later using it, we could use arrow functions and use `this.prior` throughout.

Still, I think in the interest of being explicit -- if `this` binding is required to be something special for it to work at all, there should be a bind call in there somewhere, i.e.:

```
delegate.prior = function () {
  ...
}.bind(delegate)
```

Right now whether or not calling this function works depends completely on the calling context, which might have a completely different `this` binding.

**Comment by rjrodger** [comment]
try:

```
this.wrap('cmd:some-pin', function (msg, done) {
  var seneca = this
  doSomeOtherThing(msg, function (err) {
    if (err) { return done(err)
    seneca.prior(msg, done)
  })
})
```
