### ISSUE TITLE
Is this project still developed and maintained?

### ISSUE THREAD

**Issue by zhaoyao91** [senecajs/seneca#688]
I noticed that it has not been updated for about 2 month, and the targets of roadmap are far from being implemented. Is there any plan?

**Comment by sirudog** [comment]
I have the same confusion and question as @zhaoyao91 
Especially because I have just introduced seneca to my company and stated to use it as the basis of our system built of microservices. For now I am happy with it, it does what I want, but looking at the amount of issues and some discussions on gitter (https://gitter.im/senecajs/seneca) lately started to make me worry.

**Comment by bryanpham85** [comment]
I got the same doubt with you two. @rjrodger we are all eager to hear reassuring statement from you!

**Comment by wzrdtales** [comment]
ping @rjrodger

**Comment by wzrdtales** [comment]
Last statement of @rjrodger has been here https://github.com/senecajs/seneca/issues/593

Do you have an update on this? I totally understand if things do go under the radar, happens to me too regularly. However, is there still a team working behind seneca or is it just you? Do you have long term plans? Do you need support?

Seneca after all is a great project, we use it for several projects and it works really good for us. There are untreated issues, where we build tooling around ourself and we going to continue to submit patches to the project to make it even better. However, it would be good to know if we can count on you to review merge requests or if this is totally beyond your limits. And if so, do you yet planned how this project may continue? I'm eager to hear from you :)

**Comment by wzrdtales** [comment]
ping @rjrodger Since you have been very active today, I'm bugging you again :)

**Comment by cjnqt** [comment]
ping @rjrodger - I think this is still an important question

**Comment by nfantone** [comment]
I cannot speak for @rjrodger, but some transport plugins are still actively maintained such as `seneca-amqp-transport`.

I apologize to everyone for the lack of voices in here.

**Comment by fluidnotions** [comment]
I published the seneca-zyre-transport on npm a while back it seems to work
well enough will continue to develop it as I need to
