### ISSUE TITLE
Run in browser?

### ISSUE THREAD

**Issue by flowt-au** [senecajs/seneca#699]
Hi.
I am exploring using microservices as a way to compose a web-app ie run it in a browser. I am transitioning from "old school" monolithic to microservices and am fairly new to Node etc.

The app has lots of business logic in the client with data storage a mixture of server via REST/JSON and local data via pouchdb. 

The initial iteration was MVC which got messy pretty quickly. Next was MVVM which was much better but still coupled. Then I tried a global event bus as a way to decouple which was an improvement but still didn't feel right. 

I want a system whereby I can use my Gherkin specs to run the app "headless" ie only run the models with no views at all to test the business logic. Then implement the model states as view representations with whatever renderer, persistence, logging, etc I go with.

So, in theory microservices fits the bill with its loose coupling, composition, etc. 

Could I use Seneca in the browser? Can I simply Browserify it (or similar)? Is it even a good idea?

Any thoughts or directions would be helpful.

Thanks,
Murray

**Comment by rjrodger** [comment]
Hi There - yes you can - it's still very alpha, but we'll be using it in production soon for voxgig.com - you need a client side: https://github.com/voxgig/seneca-browser and a server side: https://github.com/voxgig/seneca-handler and tracing: https://github.com/voxgig/seneca-component

**Comment by flowt-au** [comment]
Thanks Richard! I will look at it. 

And thanks for your book too - very helpful in crystallising an (experimental) approach for client side code.

Go well,
Murray
