### ISSUE TITLE
Versions of lodash before 4.17.5 are vulnerable to prototype pollution.

### ISSUE THREAD

**Issue by notquitedilbert** [senecajs/seneca#702]
Lodash needs to be upgraded as per the advice below

https://nodesecurity.io/advisories/577
https://snyk.io/vuln/npm:lodash:20180130

**Comment by rjrodger** [comment]
Fixed on master, will be included in next release.
Thank You!

**Comment by notquitedilbert** [comment]
Thanks 

Did you also check the dependencies for seneca - a lot of them are also using a vulnerable version of lodash (you seem to be a contact for most of them)

I'm using `nsp check` to identify security issues https://www.npmjs.com/package/nsp
