### ISSUE TITLE
sync/async question with hapi / HTTP 500

### ISSUE THREAD

**Issue by PKrause79** [senecajs/seneca#704]
Hello,

being new to JavaScript and Seneca on Windows 10, I want to build a very simle api-gateway service with hapi, for external http access (port 5001) to my seneca internal microservices (port 5002, 5003). I copied code from many demo´s with hapi, but none of them is working. I have the problem, that the act command seems to be asynchronously (btw. in the seneca documentation it was said that it will be executed sync, because I set a callback in the act-method), but hapi routes seems to need an immediate / sync answer, I will always get a HTTP 500 error. If I set a return value (see "dummy" in my code) manually in the hapi route, I am getting HTTP 200, but the seneca.act command was not executed in this case and the reply is not used.

Can anybody look at my code and tell me what I did wrong?

**api-gateway.js**
```
'use strict';
var hapi = require('hapi');
var seneca = require('seneca')({tag: 'api-gateway'})
    .client({type: 'http', port: 5003})
    .listen({type: 'http', port: 5002});
  
// create a webserver 
const webserver = hapi.server({
      port: 5001,
      routes: {
          cors: true
          }
  });
  
webserver.route({
    method: 'GET',
    path: '/',
    handler: function(request, reply) {
        seneca.act(
            {
                role: 'demo', 
                cmd: 'hello'
            },  
            function (err, result) 
            {
                    if (err)
                    {
                        console.log(err);
                        reply(err);
                    } 
                    else
                    {
                        console.log(result);
                        reply(result);
                    }
            }
        );
        console.log('dummy');
        return 'dummy'; // return 'This line is reached before "act" is coming back with its result!? So, the result of "act" is never returned by webserver! Without this line I am getting HTTP 500 ';
    }
});

// Start the server
async function start() {

     // enable logging "hapi-pino"-plugin
    
     await webserver.register({
        plugin: require('hapi-pino'),
        options: {
            prettyPrint: true,
            logEvents: ['response']
        }
    });

    try {
        await webserver.start();
    }
    catch (err) {
        console.log(err);
        process.exit(1);
    }

    console.log(seneca.id);
    console.log(seneca.tag);
    console.log(seneca.version);
    console.log('API-Gateway up and running at:', webserver.info.uri);

};

start();
```

**Comment by danielo515** [comment]
You need to wrap seneca.act into a promise and return that promise. There are examples on seneca docs. A seneca action will neber be sync

**Comment by PKrause79** [comment]
Are you sure that Promise is the right answer, since hapi was changed to async/await? I tried multiple hours by using the doc examples, but cannot get this simple application to run and getting more and more frustrated - even not with promises (bluebird -> seems not to work, code is not executed synchronously, because "!!!!!!!!!! bad here !!!!!!!!" is shown instead of the result)

```javascript
'use strict';

var hapi = require('hapi');
var seneca = require('seneca')({tag: 'api-gateway'})
  .client({type: 'http', port: 5003})
  .listen({type: 'http', port: 5002});
var senecaPromise = require('bluebird');
var act = senecaPromise.promisify(seneca.act, {context: seneca});  

// create a webserver 
const webserver = hapi.server({
    port: 5001,
    routes: {
        cors: true
        }
});

webserver.route({
    method: 'GET',
    path: '/',
    handler: function(request, h) { 
        act({role: 'demo', cmd: 'hello'})
        .then(function (result) {
            console.log(result);
            return result;
        })
        .catch(function (err) {
            console.log(err);
            return err;
        });
        console.log('!!!!!!!!!!!!!!!!!! bad here !!!!!!!!!!!!!!!!');
    }
});
```

I also do not understand, why in this example it seems to work with hapi and without promises: https://github.com/nodezoo/nodezoo-web/blob/master/web.js 

Any help? What about seneca-web - do I need this to solve my problem?

**Comment by danielo515** [comment]
Seems that you are somewhat confused about how javascript actually works.
Javascript (and of course node) will execute all the synchronous code it can, save any asynchronous code "for later" and then, when all the sync actions have ended, it starts to execute the asynchronous pieces of code. In your case you are telling JS, hey, here is my code, the pieces inside the promise are async. Since your console.log is outside any promise it is executed as soon as it is possible, which is before your code inside the promises.

Async/await is just syntactic sugar over promises. Hapi has moved to async await, but what they are actually doing is accepting promises as handler response. Async functions automatically return a promise, so they are convenient in this case.

You have two choices now: move your console.log inside the promise chain:

```js
'use strict';

var hapi = require('hapi');
var seneca = require('seneca')({tag: 'api-gateway'})
  .client({type: 'http', port: 5003})
  .listen({type: 'http', port: 5002});
var senecaPromise = require('bluebird');
var act = senecaPromise.promisify(seneca.act, {context: seneca});  

// create a webserver 
const webserver = hapi.server({
    port: 5001,
    routes: {
        cors: true
        }
});

webserver.route({
    method: 'GET',
    path: '/',
    handler: function(request, h) { 
        act({role: 'demo', cmd: 'hello'})
        .then(function (result) {
            console.log(result);
            console.log('!!!!!!!!!!!!!!!!!! bad here !!!!!!!!!!!!!!!!');
            return result;
        })
        .catch(function (err) {
            console.log(err);
            return err;
        });
    }
});
```

Or just use await keyword inside an async function:

```js
'use strict';

var hapi = require('hapi');
var seneca = require('seneca')({tag: 'api-gateway'})
  .client({type: 'http', port: 5003})
  .listen({type: 'http', port: 5002});
var senecaPromise = require('bluebird');
var act = senecaPromise.promisify(seneca.act, {context: seneca});  

// create a webserver 
const webserver = hapi.server({
    port: 5001,
    routes: {
        cors: true
        }
});

webserver.route({
    method: 'GET',
    path: '/',
    handler: async (request, h) => { 
        const result = await act({role: 'demo', cmd: 'hello'})
        console.log(result);
        console.log('!!!!!!!!!!!!!!!!!! bad here !!!!!!!!!!!!!!!!');
        return result;
    }
});
```

You can defer the error handling to hapi, which will return a 500 for any unhandled error.

Regards

**Comment by PKrause79** [comment]
Thank you very much for your suggestions - that helped a lot!

**Comment by danielo515** [comment]
Glad to hear that!

**Comment by rjrodger** [comment]
Thank you @danielo515 !!!
