### ISSUE TITLE
Typescript defintion files, updated ?

### ISSUE THREAD

**Issue by appsolutegeek** [senecajs/seneca#716]
Hi,

I was searching around for some typescript definition files, I found one of npm under the @types scope but it seems pretty out of date.

Does anybody know if there is an alternative types file around ?

Or is this going to be supported internally ?

Thanks in advance

**Comment by rjrodger** [comment]
@appsolutegeek would you be up for it?

**Comment by appsolutegeek** [comment]
@rjrodger hi, actually I am now using nestjs, I haven't been using this framework for a while so I am probably not the right person to do this.
