### ISSUE TITLE
Seneca troubles on App Engine (Google Cloud Platform)

### ISSUE THREAD

**Issue by jfbaquerocelis** [senecajs/seneca#731]
Hi everyone! Actually I have a project with **SenecaJS**. My database is in **PostgreSQL** and I'm using Sequelize for it. But, I'm having an error when I want to use my app in production. The error like this:

```
{
  "eraro": true,
  "orig": {},
  "code": "act_execute",
  "seneca": true,
  "package": "seneca",
  "msg": "seneca: Action action:get,entity:user failed: [TIMEOUT].",
  "details": {
    "message": "[TIMEOUT]",
    "pattern": "action:get,entity:user",
    "instance": "Seneca/bp/-",
    "orig$": {},
    "message$": "[TIMEOUT]",
    "plugin": {}
  },
  "callpoint": "at Object.act_tm [as ontm] (/app/node_modules/seneca/seneca.js:936:52)",
  "message": "seneca: Action action:get,entity:user failed: [TIMEOUT].",
  "name": "Error"
}
```

**DEVELOPMENT**: I must say that I've had some troubles with the *http transport* timeout because my querys are too slowly (I'll refactor) but I've increase the timeout for the client and the server.

```javascript
seneca.listen({
  ...
  timeout: 30000
})
seneca.client({
  ...
  timeout: 30000
})
```

So, I decided connect with **Cloud SQL** (My database is on it) through a [proxy](https://cloud.google.com/sql/docs/mysql/quickstart-proxy-test) for test in development and it's works. Then I don't know what happening in production environment neither I know if the trouble is seneca. I've follow [the google cloud documentation](https://cloud.google.com/sql/docs/postgres/connect-app-engine) but I don't know because show me **[TIMEOUT]** error.

**What I Think**
1. I think so the database connection isn't work (although the log show me `Ready for new connections` `Listening on /cloudsql/{project}:{zone}:{instance}/.s.PGSQL.5432 for {project}:{zone}:{instance}`) It's rare.
2. I think so the http transport has troubles on App Engine (It could be about configuration).

Thanks for reading. Regards! :pray: :+1: :smiley:

**Comment by rjrodger** [comment]
Thanks for your question! Please use stackoverflow for Seneca usage questions, and Github for bug reports and feature discussions. Seneca on stackoverflow: https://stackoverflow.com/questions/tagged/seneca
