### ISSUE TITLE
Can't run with hapi

### ISSUE THREAD

**Issue by shijiebei2014** [senecajs/seneca#739]
This is the parts of code:
var config = {
  routes: Routes,
  adapter: require('seneca-web-adapter-hapi'),
  context: Hapi.server({port: 4000})
}
var seneca = Seneca()
  .use(SenecaWeb, config)
  .ready(async ()=> {
    var server = seneca.export('web/context')() 
    try {
    	var promise = await server.start() // TypeError: Method Map.prototype.forEach called on incompatible receiver #<Map>
    	console.log('server started on: ' + server.info.uri)	
    } catch(e) {
    	console.error('err:', e)
    }
  })

**Comment by shijiebei2014** [comment]
I'm confused about thant config.context !== seneca.export('web/context')()

**Comment by MikeLindenau** [comment]
Seems like this is more a question around `seneca-web`? I would recommend posting this issue here  https://github.com/senecajs/seneca-web/issues

**Comment by shijiebei2014** [comment]
Thanks. I'm not sure that the problem is related to seneca.export or senece-web

**Comment by shijiebei2014** [comment]
The bug follows:
the file "seneca/lib/plugins.js"  resolve_options --> seneca.util.Optioner --> use-plugin module --> optioner module --> Hoek.clone results in map lost

**Comment by rjrodger** [comment]
Hoek.clone no longer used
