### ISSUE TITLE
compress / gzip response

### ISSUE THREAD

**Issue by theblackneko** [senecajs/seneca#750]
Hello, 

One of my endpoints returns a response that has  ~10mb, and I would like to enable gzip compression on that response. 

I tried applying the compression middleware to express but it has no effect.
Can somebody please help?

app.js:
'use strict';

const Express = require("express");
const compression = require('compression')
const Seneca  = require("seneca");
const Web     = require("seneca-web");
const dotenv = require('dotenv');
dotenv.config();

const Router = require("./plugins/Router");
const app = Express();
app.use(compression());

const config = {
    routes: Router,
    adapter: require('seneca-web-adapter-express'),
    context: app
};

const seneca = Seneca()
    .use(require("./plugins/v2.2/SenecaMap"))
    .use(require("./plugins/v2.3/SenecaMap"))
    .use(Web, config)
    .ready(() => {
        const server = seneca.export('web/context')();
        server.listen(process.env.SERVICE_PORT, () => {
            console.log("server started on: " + process.env.SERVICE_PORT )
        });
    });

**Comment by theblackneko** [comment]
And also is there a method to send a stream response ?

**Comment by rjrodger** [comment]
Please post this question stackoverflow rather than adding as an issue.
Also this issue applies to seneca-web-adapter-express more than the core seneca library.

I would not generate large messages like this directly. Instead consider storing the response and streaming separately.
