### ISSUE TITLE
lodash dependency still used in lib/common.js

### ISSUE THREAD

**Issue by yhuiban** [senecajs/seneca#787]
Hello,
The lodash dependency was removed from package.json, but it seems that lib/common.js still use it.

**Comment by r3verser** [comment]
same here

**Comment by yiluhukai** [comment]
Did you resove. this problem? I also meet it.

**Comment by r3verser** [comment]
> Did you resove. this problem? I also meet it.

just install lodash with
`npm i --save lodash`

**Comment by rjrodger** [comment]
Fixed now in 3.20.5
Thanks!
