### ISSUE TITLE
"notice":"seneca: The definition action for the plugin mesh has failed: Cannot read property 'length' of undefined (api.js:304:28)

### ISSUE THREAD

**Issue by hnv-hn** [senecajs/seneca#793]
Hi,

after reinstalling seneca version 3.20.1, I got the error from seneca/lib/api.js. For some reason, the variable deps in my case is undefined. But it worked well with the last version.

in the last version was: _.every(deps, ... 
in currently version is: for (var i=0; i < deps.length;...

Can someone, please, fix it?
Thank you very much.

https://github.com/senecajs/seneca/blob/4982f082d6f173bc7d890236f8746f13ada0bc9f/lib/api.js#L300

**Comment by wzrdtales** [comment]
duplicate of #792, just downgrade to 3.20.3 worked for me

**Comment by hnv-hn** [comment]
Thank you, wzrdtales.

I'm using version 3.20.1.
