### ISSUE TITLE
logging should be object based

### ISSUE THREAD

**Issue by rjrodger** [senecajs/seneca#90]
logging needs a refactor anyway

[Trello Card](https://trello.com/c/l9CaGeeh/84-seneca-logging-should-be-object-based)

**Comment by AdrianRossouw** [comment]
@rjrodger @geek 

I just want to point out that logging is something that has come up in the gitter channel a few times.
we need a better solution to this, and  @mcollina was pointing out https://github.com/mcollina/pino to me today, and this came up.

**Comment by mcollina** [comment]
I'm happy to help in adjusting pino and/or reviewing any changes to Seneca.
Also we should be able to have a post-processing utility to build a trace for a microservice invocation, and maybe generate a nice visualization of that too (cc @davidmarkclements for that!).

BTW, pino is 3x faster than bunyan and 5x faster than bole and winston.

**Comment by rjrodger** [comment]
I feel it too - logging has been bugging me for a long time - it is due for update for Seneca 3.0 out Jun 14th. However we will start reworking immediately after Seneca 2.0 Mar 22nd!

**Comment by AdrianRossouw** [comment]
@brycereynolds pinging you because tracing microservice invocation

**Comment by davidmarkclements** [comment]
we also know how to shave another 100ms per log off of pino with a slight
alteration to log output (hint: toISOString is real expensive)

for microservice tracing I'm thinking I can recycle work (and knowledge
gained) from creating 0x and use it to visualize microservice tracing -
e.g. flame graphs for microservices (also sunbursts and treemaps).

On Tue, Mar 8, 2016 at 2:15 PM, Adrian Rossouw <notifications@github.com>
wrote:

> @brycereynolds <https://github.com/brycereynolds> pinging you because
> tracing microservice invocation
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/senecajs/seneca/issues/90#issuecomment-193798975>.
>



-- 
David Mark Clements Ltd is a company registered in Northern Ireland.
Registered number: NI617728. Registered office: Unit 22a, Pennybridge
Industrial Estate,
Ballymena, Antrim, BT42 3HB

**Comment by mcdonnelldean** [comment]
@davidmarkclements I think you should create a full thread for that, lots of interest being generated around that stuff, I'd like to see your thoughts on tracing.

On logs, yup, they are not even bad, they are dangerous, @mcollina and I spent 3 hours wasted on Tuesday chasing down an empty object that wasn't empty at all. Logs that manipulate the values they have been given are not useful.

@rjrodger Have you any specific plans you'd like to try or is it all up for discussion? I'd like to see @mcollina + someone try a pino spike, it's pretty much the same as every other logger but he reckons it's fast as horses, which would do no harm.

**Comment by davidmarkclements** [comment]
> I'd like to see @mcollina <https://github.com/mcollina> + someone try a
pino spike,

I'd like to be the someone

On Thu, Mar 10, 2016 at 10:26 AM, Dean McDonnell <notifications@github.com>
wrote:

> @davidmarkclements <https://github.com/davidmarkclements> I think you
> should create a full thread for that, lots of interest being generated
> around that stuff, I'd like to see your thoughts on tracing.
>
> On logs, yup, they are not even bad, they are dangerous, @mcollina
> <https://github.com/mcollina> and I spent 3 hours wasted on Tuesday
> chasing down an empty object that wasn't empty at all. Logs that manipulate
> the values they have been given are not useful.
>
> @rjrodger <https://github.com/rjrodger> Have you any specific plans you'd
> like to try or is it all up for discussion? I'd like to see @mcollina
> <https://github.com/mcollina> + someone try a pino spike, it's pretty
> much the same as every other logger but he reckons it's fast as horses,
> which would do no harm.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/senecajs/seneca/issues/90#issuecomment-194779034>.
>



-- 
David Mark Clements Ltd is a company registered in Northern Ireland.
Registered number: NI617728. Registered office: Unit 22a, Pennybridge
Industrial Estate,
Ballymena, Antrim, BT42 3HB

**Comment by mcdonnelldean** [comment]
Merged with #397
