### ISSUE TITLE
why there is Hard limit on timeout

### ISSUE THREAD

**Issue by rsharma-prismhr** [senecajs/seneca#932]
https://github.com/senecajs/seneca/blob/5c7e72258cfe49e91653a17186c7aad60e56f82e/seneca.ts#L56
Why there is a hard limit of 22 seconds here?

Can this be increased or configured?

**Comment by lilsweetcaligula** [comment]
Hi @rsharma-prismhr, if you want to configure the timeout in Seneca, try passing the `timeout` option to the Seneca constructor:
```javascript
const seneca = Seneca({ timeout: 10e3 })
```
For reference: https://github.com/senecajs/seneca/blob/5c7e72258cfe49e91653a17186c7aad60e56f82e/test/timeout.test.js#L17
