### ISSUE TITLE
Flux with Seneca

### ISSUE THREAD

**Issue by av4me** [senecajs/seneca#99]
Any thoughts on using Flux tools like [RefluxJS](https://github.com/spoike/refluxjs) or [Fluxxor](http://fluxxor.com/) with Seneca?

[Trello Card](https://trello.com/c/hgOkWXlv/86-seneca-flux-with-seneca)

**Comment by rjrodger** [comment]
I'll need to understand it more deeply. However the basic idea certainly seems in the same concept space as seneca!

**Comment by yieme** [comment]
The Flux process flow as [one-way](https://github.com/banderson/generator-flux-react): 
![](https://camo.githubusercontent.com/af83e410700fb3e2eccd66144ba7d61bf7fe24cd/687474703a2f2f66616365626f6f6b2e6769746875622e696f2f666c75782f696d672f666c75782d73696d706c652d66382d6469616772616d2d6578706c61696e65642d31333030772e706e67)

The Seneca process flow while mainly is two-way, it can be used one-way and so you should be able to implement a Flux style flow with Seneca.

Seneca transports look to be a good fit for the arrows between the Flux components: Action -> Dispatch -> Store -> View -> ...   If you wanted to enforce separation then using separate buses might be an option.

Seneca Stores are more an ORM where Flux Stores contain the business logic and emit change events. Seneca Flux Stores would wrap all Seneca Store operations for proper isolation and emit appropriate events.

Unsure how View would fit in as I'm unsure if Seneca runs on the browser.

**Comment by mcdonnelldean** [comment]
@yieme Hi,

So I actually have some experience with flux. In general I would say Seneca sit's __after__ your flux implementation. As you say flux is very directional, like CQRS. This makes it particularly suited to stateless UI's. On the browser side I would look to actual flux implementations as they are highly optimised for this pattern.

Seneca tends to be more suited to microservice to microservice communication. It supports all different sorts of directional communication to the multitude of ways microservices tend to interact with each other.

An 'app' is usually a client off of a number of microservices. With this in mind it tends to make more sense to design the app using patterns and libs designed to make cracking UI's. Your 'apps' then talk to one or more Seneca powered servers, which can in turn talk with each other.

There is some work on going to show different ways to wire up an 'app' component to a number of microservices. One of the items on the list is to demonstrate a React based app which will include a flux like architecture on the frontend and Seneca on the backend. When these are ready (in the early new year most likely) I will leave a note on this issue.

For now I am going to close as an answered question awaiting demo code. If you have any more questions, or need to ask anything else please feel free to reopen, thanks for the question :D
